# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Web::BaseController`.
# Please instead update this file by running `bin/tapioca dsl Web::BaseController`.


class Web::BaseController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
