# typed: true
# frozen_string_literal: true

# Renders the permission catalogue for humans (docs/permissions.md) and for the
# Vue app (a TypeScript union), so neither can drift from app/lib/permissions.rb.
module PermissionsExport
  HEADER = "<!-- Generated by `bin/rails permissions:export` from app/lib/permissions.rb. Do not edit. -->"

  def self.markdown
    [HEADER, "", "# Permissions", "", section("Merchant", Permissions::MERCHANT, merchant: true), "",
     section("Operator", Permissions::OPERATOR, merchant: false), ""].join("\n")
  end

  def self.typescript
    <<~TS
      // Generated by `bin/rails permissions:export` from app/lib/permissions.rb. Do not edit.
      export type MerchantPermission =
      #{union(merchant_permissions)}

      export type OperatorPermission =
      #{union(operator_permissions)}
    TS
  end

  def self.merchant_permissions = Permissions::CATALOGUE.keys.reject { |p| p.start_with?("ops.") }.sort
  def self.operator_permissions = Permissions::CATALOGUE.keys.select { |p| p.start_with?("ops.") }.sort

  def self.union(names) = names.map { |n| %(  | "#{n}") }.join("\n") + ";"

  def self.section(title, roles, merchant:)
    names = merchant ? merchant_permissions : operator_permissions
    head = "| Permission | Description | #{roles.keys.join(' | ')} | Sensitive |"
    sep = "|---|---|#{roles.keys.map { ':-:' }.join('|')}|:-:|"
    rows = names.map do |name|
      entry = Permissions::CATALOGUE.fetch(name)
      cells = roles.values.map { |perms| perms.include?(name) ? "✓" : "" }
      "| `#{name}` | #{entry.fetch(:description)} | #{cells.join(' | ')} | #{entry.fetch(:sensitive) ? 'yes' : ''} |"
    end
    ["## #{title}", "", head, sep, *rows].join("\n")
  end
end
