# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ast` gem.
# Please instead update this file by running `bin/tapioca gem ast`.


# pkg:gem/ast#lib/ast.rb:13
module AST; end

# pkg:gem/ast#lib/ast/node.rb:40
class AST::Node
  # pkg:gem/ast#lib/ast/node.rb:72
  def initialize(type, children = T.unsafe(nil), properties = T.unsafe(nil)); end

  # pkg:gem/ast#lib/ast/node.rb:172
  def +(array); end

  # pkg:gem/ast#lib/ast/node.rb:181
  def <<(element); end

  # pkg:gem/ast#lib/ast/node.rb:153
  def ==(other); end

  # pkg:gem/ast#lib/ast/node.rb:177
  def append(element); end

  # pkg:gem/ast#lib/ast/node.rb:56
  def children; end

  # pkg:gem/ast#lib/ast/node.rb:118
  def clone; end

  # pkg:gem/ast#lib/ast/node.rb:168
  def concat(array); end

  # pkg:gem/ast#lib/ast/node.rb:253
  def deconstruct; end

  # pkg:gem/ast#lib/ast/node.rb:115
  def dup; end

  # pkg:gem/ast#lib/ast/node.rb:85
  def eql?(other); end

  # pkg:gem/ast#lib/ast/node.rb:61
  def hash; end

  # pkg:gem/ast#lib/ast/node.rb:211
  def inspect(indent = T.unsafe(nil)); end

  # pkg:gem/ast#lib/ast/node.rb:57
  def to_a; end

  # pkg:gem/ast#lib/ast/node.rb:229
  def to_ast; end

  # pkg:gem/ast#lib/ast/node.rb:204
  def to_s(indent = T.unsafe(nil)); end

  # pkg:gem/ast#lib/ast/node.rb:187
  def to_sexp(indent = T.unsafe(nil)); end

  # pkg:gem/ast#lib/ast/node.rb:237
  def to_sexp_array; end

  # pkg:gem/ast#lib/ast/node.rb:43
  def type; end

  # pkg:gem/ast#lib/ast/node.rb:133
  def updated(type = T.unsafe(nil), children = T.unsafe(nil), properties = T.unsafe(nil)); end

  protected

  # pkg:gem/ast#lib/ast/node.rb:98
  def assign_properties(properties); end

  # pkg:gem/ast#lib/ast/node.rb:264
  def fancy_type; end

  private

  # pkg:gem/ast#lib/ast/node.rb:107
  def original_dup; end
end

# pkg:gem/ast#lib/ast/processor.rb:8
class AST::Processor
  include ::AST::Processor::Mixin
end

# pkg:gem/ast#lib/ast/processor/mixin.rb:240
module AST::Processor::Mixin
  # pkg:gem/ast#lib/ast/processor/mixin.rb:284
  def handler_missing(node); end

  # pkg:gem/ast#lib/ast/processor/mixin.rb:251
  def process(node); end

  # pkg:gem/ast#lib/ast/processor/mixin.rb:274
  def process_all(nodes); end
end

# pkg:gem/ast#lib/ast/sexp.rb:20
module AST::Sexp
  # pkg:gem/ast#lib/ast/sexp.rb:26
  def s(type, *children); end
end
