# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca gem bigdecimal`.


# pkg:gem/bigdecimal#lib/bigdecimal.rb:13
class BigDecimal < ::Numeric
  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def %(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def *(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:127
  def **(y); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def +(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def +@; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def -(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def -@; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def /(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def <(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def <=(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def <=>(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def ==(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def ===(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def >(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def >=(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def _decimal_shift(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def _dump(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def abs; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def add(_arg0, _arg1); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def ceil(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def clone; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def coerce(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def div(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def divmod(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def dup; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def eql?(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def exponent; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def finite?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def fix; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def floor(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def frac; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def hash; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def infinite?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def inspect; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def modulo(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def mult(_arg0, _arg1); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def n_significant_digits; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def nan?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def nonzero?; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:147
  def power(y, prec = T.unsafe(nil)); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def precision; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def precision_scale; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def quo(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def remainder(_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def round(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def scale; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def sign; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def split; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:262
  def sqrt(prec); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def sub(_arg0, _arg1); end

  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:110
  def to_d; end

  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:90
  def to_digits; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def to_f; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def to_i; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def to_int; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def to_r; end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def to_s(format = T.unsafe(nil)); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def truncate(*_arg0); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:10
  def zero?; end
end

# pkg:gem/bigdecimal#lib/bigdecimal.rb:14
module BigDecimal::Internal
  class << self
    # pkg:gem/bigdecimal#lib/bigdecimal.rb:21
    def coerce_to_bigdecimal(x, prec, method_name); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:33
    def coerce_validate_prec(prec, method_name, accept_zero: T.unsafe(nil)); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:87
    def float_log(x); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:53
    def infinity_computation_result; end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:67
    def nan_computation_result; end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:75
    def newton_loop(prec, initial_precision: T.unsafe(nil), safe_margin: T.unsafe(nil)); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:94
    def taylor_sum_binary_splitting(x, ds, prec); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:60
    def underflow_computation_result; end
  end
end

# pkg:gem/bigdecimal#lib/bigdecimal.rb:17
BigDecimal::Internal::EXTRA_PREC = T.let(T.unsafe(nil), Integer)

BigDecimal::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/bigdecimal#lib/bigdecimal.rb:288
module BigMath
  private

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:336
  def _exp_binary_splitting(x, prec); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:356
  def exp(x, prec); end

  # pkg:gem/bigdecimal#lib/bigdecimal.rb:303
  def log(x, prec); end

  class << self
    # pkg:gem/bigdecimal#lib/bigdecimal.rb:356
    def exp(x, prec); end

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:303
    def log(x, prec); end

    private

    # pkg:gem/bigdecimal#lib/bigdecimal.rb:336
    def _exp_binary_splitting(x, prec); end
  end
end

# pkg:gem/bigdecimal#lib/bigdecimal/util.rb:141
class Complex < ::Numeric
  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:164
  def to_d(precision = T.unsafe(nil)); end
end

# pkg:gem/bigdecimal#lib/bigdecimal/util.rb:116
class Rational < ::Numeric
  # pkg:gem/bigdecimal#lib/bigdecimal/util.rb:135
  def to_d(precision = T.unsafe(nil)); end
end
