# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `connection_pool` gem.
# Please instead update this file by running `bin/tapioca gem connection_pool`.


# pkg:gem/connection_pool#lib/connection_pool/version.rb:1
class ConnectionPool
  # pkg:gem/connection_pool#lib/connection_pool.rb:90
  def initialize(options = T.unsafe(nil), &block); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:219
  def auto_reload_after_fork; end

  # pkg:gem/connection_pool#lib/connection_pool.rb:222
  def available; end

  # pkg:gem/connection_pool#lib/connection_pool.rb:167
  def checkin(force: T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:157
  def checkout(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:153
  def discard_current_connection(&block); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:227
  def idle; end

  # pkg:gem/connection_pool#lib/connection_pool.rb:212
  def reap(idle_seconds = T.unsafe(nil), &block); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:206
  def reload(&block); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:198
  def shutdown(&block); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:217
  def size; end

  # pkg:gem/connection_pool#lib/connection_pool.rb:121
  def then(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool.rb:106
  def with(options = T.unsafe(nil)); end

  class << self
    # pkg:gem/connection_pool#lib/connection_pool.rb:52
    def after_fork; end

    # pkg:gem/connection_pool#lib/connection_pool.rb:44
    def wrap(options, &block); end
  end
end

# pkg:gem/connection_pool#lib/connection_pool.rb:42
ConnectionPool::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/connection_pool#lib/connection_pool.rb:5
class ConnectionPool::Error < ::RuntimeError; end

# pkg:gem/connection_pool#lib/connection_pool.rb:70
module ConnectionPool::ForkTracker
  # pkg:gem/connection_pool#lib/connection_pool.rb:71
  def _fork; end
end

# pkg:gem/connection_pool#lib/connection_pool.rb:49
ConnectionPool::INSTANCES = T.let(T.unsafe(nil), ObjectSpace::WeakMap)

# pkg:gem/connection_pool#lib/connection_pool.rb:7
class ConnectionPool::PoolShuttingDownError < ::ConnectionPool::Error; end

# pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:19
class ConnectionPool::TimedStack
  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:25
  def initialize(size = T.unsafe(nil), &block); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:50
  def <<(obj, options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:149
  def decrement_created; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:131
  def empty?; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:143
  def idle; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:137
  def length; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:20
  def max; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:63
  def pop(timeout = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:38
  def push(obj, options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:111
  def reap(idle_seconds, &block); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:97
  def shutdown(reload: T.unsafe(nil), &block); end

  private

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:173
  def connection_stored?(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:155
  def current_time; end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:181
  def fetch_connection(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:213
  def idle_connections?(idle_seconds); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:201
  def reserve_idle_connection(idle_seconds); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:189
  def shutdown_connections(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:221
  def store_connection(obj, options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:230
  def try_create(options = T.unsafe(nil)); end

  # pkg:gem/connection_pool#lib/connection_pool/timed_stack.rb:165
  def try_fetch_connection(options = T.unsafe(nil)); end
end

# pkg:gem/connection_pool#lib/connection_pool.rb:9
class ConnectionPool::TimeoutError < ::Timeout::Error; end

# pkg:gem/connection_pool#lib/connection_pool/version.rb:2
ConnectionPool::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:2
class ConnectionPool::Wrapper < ::BasicObject
  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:5
  def initialize(options = T.unsafe(nil), &block); end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:35
  def method_missing(name, *args, **kwargs, &block); end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:25
  def pool_available; end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:17
  def pool_shutdown(&block); end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:21
  def pool_size; end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:29
  def respond_to?(id, *args); end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:13
  def with(&block); end

  # pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:9
  def wrapped_pool; end
end

# pkg:gem/connection_pool#lib/connection_pool/wrapper.rb:3
ConnectionPool::Wrapper::METHODS = T.let(T.unsafe(nil), Array)

module Process
  extend ::ConnectionPool::ForkTracker
  extend ::RedisClient::PIDCache::CoreExt
  extend ::ActiveSupport::ForkTracker::CoreExt
end
