# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-cli` gem.
# Please instead update this file by running `bin/tapioca gem dry-cli`.


# pkg:gem/dry-cli#lib/dry/cli.rb:6
module Dry
  class << self
    # pkg:gem/dry-cli#lib/dry/cli.rb:230
    def CLI(registry_or_command = T.unsafe(nil), &block); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli.rb:10
class Dry::CLI
  # pkg:gem/dry-cli#lib/dry/cli.rb:46
  def initialize(command_or_registry = T.unsafe(nil), &block); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:64
  def call(arguments: T.unsafe(nil), out: T.unsafe(nil), err: T.unsafe(nil)); end

  private

  # pkg:gem/dry-cli#lib/dry/cli.rb:211
  def anonymous_registry(&block); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:154
  def build_command(command); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:199
  def command?(command); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:89
  def err; end

  # pkg:gem/dry-cli#lib/dry/cli.rb:167
  def error(result); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:160
  def help(command, prog_name); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:81
  def kommand; end

  # pkg:gem/dry-cli#lib/dry/cli.rb:85
  def out; end

  # pkg:gem/dry-cli#lib/dry/cli.rb:140
  def parse(command, arguments, names); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:98
  def perform_command(arguments); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:114
  def perform_registry(arguments); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:77
  def registry; end

  # pkg:gem/dry-cli#lib/dry/cli.rb:185
  def signal_exception(exception); end

  # pkg:gem/dry-cli#lib/dry/cli.rb:173
  def spell_checker(result, arguments); end

  class << self
    # pkg:gem/dry-cli#lib/dry/cli.rb:29
    def command?(command); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/option.rb:142
class Dry::CLI::Argument < ::Dry::CLI::Option
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:145
  def argument?; end
end

# pkg:gem/dry-cli#lib/dry/cli/banner.rb:11
module Dry::CLI::Banner
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:85
    def arguments(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:130
    def build_subcommands_list(subcommands); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:19
    def call(command, name); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:71
    def command_arguments(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:57
    def command_description(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:49
    def command_examples(command, name); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:33
    def command_name(name); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:39
    def command_name_and_arguments(command, name); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:79
    def command_options(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:63
    def command_subcommands(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:98
    def extended_command_arguments(command); end

    # pkg:gem/dry-cli#lib/dry/cli/banner.rb:107
    def extended_command_options(command); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/command.rb:11
class Dry::CLI::Command
  extend ::Forwardable

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def arguments(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def default_params(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def description(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def examples(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def optional_arguments(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def options(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def params(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def required_arguments(*args, **_arg1, &block); end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:381
  def subcommands(*args, **_arg1, &block); end

  protected

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:410
  def err; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:424
  def out; end

  class << self
    # pkg:gem/dry-cli#lib/dry/cli/command.rb:197
    def argument(name, options = T.unsafe(nil)); end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:335
    def default_params; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:67
    def desc(description); end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:103
    def example(*examples); end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:14
    def inherited(base); end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:316
    def option(name, options = T.unsafe(nil)); end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:349
    def optional_arguments; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:327
    def params; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:343
    def required_arguments; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:355
    def subcommands; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:369
    def superclass_arguments; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:375
    def superclass_options; end

    # pkg:gem/dry-cli#lib/dry/cli/command.rb:361
    def superclass_variable_dup(var); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/command.rb:29
module Dry::CLI::Command::ClassMethods
  # pkg:gem/dry-cli#lib/dry/cli/command.rb:40
  def arguments; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:32
  def description; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:36
  def examples; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:44
  def options; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:48
  def subcommands; end

  # pkg:gem/dry-cli#lib/dry/cli/command.rb:48
  def subcommands=(_arg0); end
end

# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:9
class Dry::CLI::CommandRegistry
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:12
  def initialize; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:40
  def get(arguments); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:19
  def set(name, command, aliases, hidden); end
end

# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:237
class Dry::CLI::CommandRegistry::Chain
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:244
  def initialize; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:250
  def append(&callback); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:240
  def chain; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:256
  def run(context, **args); end
end

# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:184
class Dry::CLI::CommandRegistry::LookupResult
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:195
  def initialize(node, arguments, names, found); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:228
  def after_callbacks; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:191
  def arguments; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:222
  def before_callbacks; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:210
  def children; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:216
  def command; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:204
  def found?; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:187
  def names; end
end

# pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:80
class Dry::CLI::CommandRegistry::Node
  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:111
  def initialize(parent = T.unsafe(nil)); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:107
  def after_callbacks; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:149
  def alias!(key, child); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:91
  def aliases; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:155
  def aliases!(aliases); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:103
  def before_callbacks; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:87
  def children; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:175
  def children?; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:99
  def command; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:95
  def hidden; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:163
  def hidden!(hidden); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:136
  def leaf!(command); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:169
  def leaf?; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:130
  def lookup(token); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:83
  def parent; end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:124
  def put(parent, key); end

  # pkg:gem/dry-cli#lib/dry/cli/command_registry.rb:142
  def subcommands!(command); end
end

# pkg:gem/dry-cli#lib/dry/cli/errors.rb:9
class Dry::CLI::Error < ::StandardError; end

# pkg:gem/dry-cli#lib/dry/cli/inflector.rb:7
module Dry::CLI::Inflector
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/inflector.rb:10
    def dasherize(input); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/errors.rb:26
class Dry::CLI::InvalidCallbackError < ::Dry::CLI::Error
  # pkg:gem/dry-cli#lib/dry/cli/errors.rb:29
  def initialize(callback); end
end

# pkg:gem/dry-cli#lib/dry/cli/option.rb:9
class Dry::CLI::Option
  # pkg:gem/dry-cli#lib/dry/cli/option.rb:20
  def initialize(name, options = T.unsafe(nil)); end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:116
  def alias_names; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:27
  def aliases; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:87
  def argument?; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:69
  def array?; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:58
  def boolean?; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:75
  def default; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:33
  def desc; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:81
  def description_name; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:63
  def flag?; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:12
  def name; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:16
  def options; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:94
  def parser_options; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:40
  def required?; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:46
  def type; end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:126
  def valid_value?(value); end

  # pkg:gem/dry-cli#lib/dry/cli/option.rb:52
  def values; end
end

# pkg:gem/dry-cli#lib/dry/cli/parser.rb:12
module Dry::CLI::Parser
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:16
    def call(command, arguments, prog_name); end

    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:72
    def match_arguments(command_arguments, arguments, default_values); end

    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:42
    def parse_required_params(command, arguments, prog_name, parsed_options); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/parser.rb:96
class Dry::CLI::Parser::Result
  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:125
  def initialize(arguments: T.unsafe(nil), error: T.unsafe(nil), help: T.unsafe(nil)); end

  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:117
  def arguments; end

  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:121
  def error; end

  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:133
  def error?; end

  # pkg:gem/dry-cli#lib/dry/cli/parser.rb:139
  def help?; end

  class << self
    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:111
    def failure(error = T.unsafe(nil)); end

    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:99
    def help; end

    # pkg:gem/dry-cli#lib/dry/cli/parser.rb:105
    def success(arguments = T.unsafe(nil)); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/program_name.rb:9
module Dry::CLI::ProgramName
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/program_name.rb:16
    def call(names = T.unsafe(nil), program_name: T.unsafe(nil)); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/program_name.rb:12
Dry::CLI::ProgramName::SEPARATOR = T.let(T.unsafe(nil), String)

# pkg:gem/dry-cli#lib/dry/cli/registry.rb:10
module Dry::CLI::Registry
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:261
  def after(command_name, callback = T.unsafe(nil), &blk); end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:173
  def before(command_name, callback = T.unsafe(nil), &blk); end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:269
  def get(arguments); end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:78
  def register(name, command = T.unsafe(nil), aliases: T.unsafe(nil), hidden: T.unsafe(nil), &block); end

  private

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:288
  def _callback(callback, blk); end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:279
  def command(command_name); end

  class << self
    # pkg:gem/dry-cli#lib/dry/cli/registry.rb:13
    def extended(base); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/registry.rb:275
Dry::CLI::Registry::COMMAND_NAME_SEPARATOR = T.let(T.unsafe(nil), String)

# pkg:gem/dry-cli#lib/dry/cli/registry.rb:308
class Dry::CLI::Registry::Prefix
  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:311
  def initialize(registry, prefix, aliases, hidden); end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:321
  def register(name, command = T.unsafe(nil), aliases: T.unsafe(nil), hidden: T.unsafe(nil), &block); end

  private

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:343
  def prefix; end

  # pkg:gem/dry-cli#lib/dry/cli/registry.rb:339
  def registry; end
end

# pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:12
module Dry::CLI::SpellChecker
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:15
    def call(result, arguments); end

    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:27
    def cmd_to_spell(arguments, result_names); end

    # pkg:gem/dry-cli#lib/dry/cli/spell_checker.rb:33
    def ignore?(cmd); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/errors.rb:17
class Dry::CLI::UnknownCommandError < ::Dry::CLI::Error
  # pkg:gem/dry-cli#lib/dry/cli/errors.rb:20
  def initialize(command_name); end
end

# pkg:gem/dry-cli#lib/dry/cli/usage.rb:11
module Dry::CLI::Usage
  class << self
    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:54
    def arguments(command); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:19
    def call(result); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:91
    def command_name(result, name); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:85
    def commands(result); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:33
    def commands_and_arguments(result); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:69
    def description(command); end

    # pkg:gem/dry-cli#lib/dry/cli/usage.rb:77
    def justify(string, padding, usage); end
  end
end

# pkg:gem/dry-cli#lib/dry/cli/usage.rb:15
Dry::CLI::Usage::ROOT_COMMAND_WITH_SUBCOMMANDS_BANNER = T.let(T.unsafe(nil), String)

# pkg:gem/dry-cli#lib/dry/cli/usage.rb:14
Dry::CLI::Usage::SUBCOMMAND_BANNER = T.let(T.unsafe(nil), String)

# pkg:gem/dry-cli#lib/dry/cli/version.rb:6
Dry::CLI::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/dry-cli#lib/dry/cli/errors.rb:13
class Dry::CLI::ValueError < ::Dry::CLI::Error; end
