# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-retry` gem.
# Please instead update this file by running `bin/tapioca gem faraday-retry`.


# pkg:gem/faraday-retry#lib/faraday/retriable_response.rb:4
module Faraday; end

# pkg:gem/faraday-retry#lib/faraday/retriable_response.rb:6
class Faraday::RetriableResponse < ::Faraday::Error; end

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:6
module Faraday::Retry; end

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:19
class Faraday::Retry::Middleware < ::Faraday::Middleware
  include ::Faraday::Retryable

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:143
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:183
  def build_exception_matcher(exceptions); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:149
  def calculate_sleep_amount(retries, env); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:163
  def call(env); end

  private

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:220
  def calculate_rate_limit_reset(env); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:227
  def calculate_retry_after(env); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:232
  def calculate_retry_interval(retries); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:243
  def parse_retry_header(env, header); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:204
  def retry_request?(env, exception); end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:209
  def rewind_files(body); end
end

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:22
Faraday::Retry::Middleware::DEFAULT_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:26
Faraday::Retry::Middleware::IDEMPOTENT_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:35
class Faraday::Retry::Middleware::Options < ::Faraday::Options
  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:63
  def backoff_factor; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:67
  def exceptions; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:87
  def exhausted_retries_block; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:51
  def interval; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:59
  def interval_randomness; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:47
  def max; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:55
  def max_interval; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:71
  def methods; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:79
  def retry_block; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:75
  def retry_if; end

  # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:83
  def retry_statuses; end

  class << self
    # pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:39
    def from(value); end
  end
end

# pkg:gem/faraday-retry#lib/faraday/retry/middleware.rb:37
Faraday::Retry::Middleware::Options::DEFAULT_CHECK = T.let(T.unsafe(nil), Proc)

# pkg:gem/faraday-retry#lib/faraday/retry/version.rb:5
Faraday::Retry::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/faraday-retry#lib/faraday/retry/retryable.rb:5
module Faraday::Retryable
  # pkg:gem/faraday-retry#lib/faraday/retry/retryable.rb:6
  def with_retries(env:, options:, retries:, body:, errmatch:); end

  private

  # pkg:gem/faraday-retry#lib/faraday/retry/retryable.rb:38
  def exhausted_retries(options, env, exception); end

  # pkg:gem/faraday-retry#lib/faraday/retry/retryable.rb:34
  def retries_zero?(retries, env, exception); end
end
