# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `globalid` gem.
# Please instead update this file by running `bin/tapioca gem globalid`.


# pkg:gem/globalid#lib/global_id/version.rb:2
class GlobalID
  extend ::ActiveSupport::Autoload

  # pkg:gem/globalid#lib/global_id/global_id.rb:49
  def initialize(gid, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:81
  def ==(other); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def app(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:94
  def as_json(*_arg0); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def deconstruct_keys(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:84
  def eql?(other); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:53
  def find(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:86
  def hash; end

  # pkg:gem/globalid#lib/global_id/global_id.rb:57
  def model_class; end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def model_id(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def model_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def params(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:90
  def to_param; end

  # pkg:gem/globalid#lib/global_id/global_id.rb:47
  def to_s(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/globalid#lib/global_id/global_id.rb:46
  def uri; end

  class << self
    # pkg:gem/globalid#lib/global_id/global_id.rb:10
    def app; end

    # pkg:gem/globalid#lib/global_id/global_id.rb:32
    def app=(app); end

    # pkg:gem/globalid#lib/global_id/global_id.rb:12
    def create(model, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/global_id.rb:36
    def default_locator(default_locator); end

    # pkg:gem/globalid#lib/global_id.rb:22
    def deprecator; end

    # pkg:gem/globalid#lib/global_id.rb:17
    def eager_load!; end

    # pkg:gem/globalid#lib/global_id/global_id.rb:22
    def find(gid, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/global_id.rb:26
    def parse(gid, options = T.unsafe(nil)); end

    private

    # pkg:gem/globalid#lib/global_id/global_id.rb:41
    def parse_encoded_gid(gid, options); end
  end
end

# pkg:gem/globalid#lib/global_id/identification.rb:29
module GlobalID::Identification
  # pkg:gem/globalid#lib/global_id/identification.rb:41
  def to_gid(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/identification.rb:47
  def to_gid_param(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/identification.rb:38
  def to_global_id(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/identification.rb:111
  def to_sgid(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/identification.rb:117
  def to_sgid_param(options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/identification.rb:108
  def to_signed_global_id(options = T.unsafe(nil)); end
end

# pkg:gem/globalid#lib/global_id/locator.rb:5
module GlobalID::Locator
  class << self
    # pkg:gem/globalid#lib/global_id/locator.rb:21
    def default_locator; end

    # pkg:gem/globalid#lib/global_id/locator.rb:21
    def default_locator=(_arg0); end

    # pkg:gem/globalid#lib/global_id/locator.rb:71
    def fetch(gid, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:35
    def locate(gid, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:104
    def locate_many(gids, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:147
    def locate_many_signed(sgids, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:125
    def locate_signed(sgid, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:179
    def locator_for(gid); end

    # pkg:gem/globalid#lib/global_id/locator.rb:171
    def use(app, locator = T.unsafe(nil), &locator_block); end

    private

    # pkg:gem/globalid#lib/global_id/locator.rb:188
    def fetch_record(gid, options); end

    # pkg:gem/globalid#lib/global_id/locator.rb:184
    def find_allowed?(gid, only = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/locator.rb:198
    def normalize_app(app); end

    # pkg:gem/globalid#lib/global_id/locator.rb:194
    def parse_allowed(gids, only = T.unsafe(nil)); end
  end
end

# pkg:gem/globalid#lib/global_id/locator.rb:206
class GlobalID::Locator::BaseLocator
  # pkg:gem/globalid#lib/global_id/locator.rb:211
  def locate(gid, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/locator.rb:219
  def locate_many(gids, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/locator.rb:207
  def model_class(gid); end

  private

  # pkg:gem/globalid#lib/global_id/locator.rb:243
  def find_records(model_class, ids, options); end

  # pkg:gem/globalid#lib/global_id/locator.rb:253
  def model_id_is_valid?(gid); end

  # pkg:gem/globalid#lib/global_id/locator.rb:257
  def primary_key(model_class); end
end

# pkg:gem/globalid#lib/global_id/locator.rb:283
class GlobalID::Locator::BlockLocator
  # pkg:gem/globalid#lib/global_id/locator.rb:284
  def initialize(block); end

  # pkg:gem/globalid#lib/global_id/locator.rb:292
  def locate(gid, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/locator.rb:296
  def locate_many(gids, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/locator.rb:288
  def model_class(gid); end
end

# pkg:gem/globalid#lib/global_id/locator.rb:7
class GlobalID::Locator::Error < ::StandardError; end

# pkg:gem/globalid#lib/global_id/locator.rb:6
class GlobalID::Locator::InvalidModelIdError < ::StandardError; end

# pkg:gem/globalid#lib/global_id/locator.rb:12
class GlobalID::Locator::RecordNotFound < ::GlobalID::Locator::Error; end

# pkg:gem/globalid#lib/global_id/locator.rb:17
class GlobalID::Locator::RecordUnavailable < ::GlobalID::Locator::Error; end

# pkg:gem/globalid#lib/global_id/locator.rb:262
class GlobalID::Locator::UnscopedLocator < ::GlobalID::Locator::BaseLocator
  # pkg:gem/globalid#lib/global_id/locator.rb:263
  def locate(gid, options = T.unsafe(nil)); end

  private

  # pkg:gem/globalid#lib/global_id/locator.rb:268
  def find_records(model_class, ids, options); end

  # pkg:gem/globalid#lib/global_id/locator.rb:272
  def unscoped(model_class); end
end

# pkg:gem/globalid#lib/global_id/railtie.rb:10
class GlobalID::Railtie < ::Rails::Railtie; end

# pkg:gem/globalid#lib/global_id/version.rb:3
GlobalID::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/globalid#lib/global_id/verifier.rb:5
class GlobalID::Verifier < ::ActiveSupport::MessageVerifier
  private

  # pkg:gem/globalid#lib/global_id/verifier.rb:11
  def decode(data, **_arg1); end

  # pkg:gem/globalid#lib/global_id/verifier.rb:7
  def encode(data, **_arg1); end
end

# pkg:gem/globalid#lib/global_id/signed_global_id.rb:5
class SignedGlobalID < ::GlobalID
  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:60
  def initialize(gid, options = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:72
  def ==(other); end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:58
  def expires_at; end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:76
  def inspect; end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:58
  def purpose; end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:70
  def to_param; end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:67
  def to_s; end

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:58
  def verifier; end

  private

  # pkg:gem/globalid#lib/global_id/signed_global_id.rb:81
  def pick_expiration(options); end

  class << self
    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:9
    def expires_in; end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:9
    def expires_in=(_arg0); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:11
    def parse(sgid, options = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:25
    def pick_purpose(options); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:17
    def pick_verifier(options); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:9
    def verifier; end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:9
    def verifier=(_arg0); end

    private

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:51
    def raise_if_expired(expires_at); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:30
    def verify(sgid, options); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:41
    def verify_with_legacy_self_validated_metadata(sgid, options); end

    # pkg:gem/globalid#lib/global_id/signed_global_id.rb:35
    def verify_with_verifier_validated_metadata(sgid, options); end
  end
end

# pkg:gem/globalid#lib/global_id/signed_global_id.rb:6
class SignedGlobalID::ExpiredMessage < ::StandardError; end

# pkg:gem/globalid#lib/global_id/uri/gid.rb:8
class URI::GID < ::URI::Generic
  # pkg:gem/globalid#lib/global_id/uri/gid.rb:29
  def app; end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:111
  def deconstruct_keys(_keys); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:30
  def model_id; end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:30
  def model_name; end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:30
  def params; end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:106
  def to_s; end

  protected

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:122
  def query=(query); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:133
  def set_params(params); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:116
  def set_path(path); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:128
  def set_query(query); end

  private

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:140
  def check_host(host); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:145
  def check_path(path); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:150
  def check_scheme(scheme); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:199
  def parse_query_params(query); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:158
  def set_model_components(path, validate = T.unsafe(nil)); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:178
  def validate_component(component); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:192
  def validate_model_id(model_id_part); end

  # pkg:gem/globalid#lib/global_id/uri/gid.rb:185
  def validate_model_id_section(model_id, model_name); end

  class << self
    # pkg:gem/globalid#lib/global_id/uri/gid.rb:92
    def build(args); end

    # pkg:gem/globalid#lib/global_id/uri/gid.rb:76
    def create(app, model, params = T.unsafe(nil)); end

    # pkg:gem/globalid#lib/global_id/uri/gid.rb:68
    def parse(uri); end

    # pkg:gem/globalid#lib/global_id/uri/gid.rb:52
    def validate_app(app); end
  end
end

# pkg:gem/globalid#lib/global_id/uri/gid.rb:138
URI::GID::COMPONENT = T.let(T.unsafe(nil), Array)

# pkg:gem/globalid#lib/global_id/uri/gid.rb:38
URI::GID::COMPOSITE_MODEL_ID_DELIMITER = T.let(T.unsafe(nil), String)

# pkg:gem/globalid#lib/global_id/uri/gid.rb:37
URI::GID::COMPOSITE_MODEL_ID_MAX_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/globalid#lib/global_id/uri/gid.rb:34
class URI::GID::InvalidModelIdError < ::URI::InvalidComponentError; end

# pkg:gem/globalid#lib/global_id/uri/gid.rb:33
class URI::GID::MissingModelIdError < ::URI::InvalidComponentError; end

# pkg:gem/globalid#lib/global_id/uri/gid.rb:40
URI::GID::URI_PARSER = T.let(T.unsafe(nil), URI::RFC3986_Parser)
