# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `google-protobuf` gem.
# Please instead update this file by running `bin/tapioca gem google-protobuf`.


# pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:8
module Google; end

# pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:9
module Google::Protobuf
  class << self
    # pkg:gem/google-protobuf#lib/google/protobuf.rb:38
    def decode(klass, proto, options = T.unsafe(nil)); end

    # pkg:gem/google-protobuf#lib/google/protobuf.rb:42
    def decode_json(klass, json, options = T.unsafe(nil)); end

    def deep_copy(_arg0); end
    def discard_unknown(_arg0); end

    # pkg:gem/google-protobuf#lib/google/protobuf.rb:30
    def encode(msg, options = T.unsafe(nil)); end

    # pkg:gem/google-protobuf#lib/google/protobuf.rb:34
    def encode_json(msg, options = T.unsafe(nil)); end
  end
end

# pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:33
class Google::Protobuf::AbstractMessage
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def ==(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def [](_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def []=(_arg0, _arg1); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clone; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def dup; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def eql?(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def freeze; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def frozen?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def hash; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def inspect; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def method_missing(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_h; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_s; end

  private

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def respond_to_missing?(*_arg0); end

  class << self
    def decode(*_arg0); end
    def decode_json(*_arg0); end
    def descriptor; end
    def encode(*_arg0); end
    def encode_json(*_arg0); end
  end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::Descriptor
  include ::Enumerable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each_oneof; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def file_descriptor; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def lookup(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def lookup_oneof(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def msgclass; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::DescriptorPool
  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def add_serialized_file(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def lookup(_arg0); end

  class << self
    def generated_pool; end
  end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::EnumDescriptor
  include ::Enumerable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def enummodule; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def file_descriptor; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def is_closed?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def lookup_name(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def lookup_value(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf.rb:16
class Google::Protobuf::Error < ::StandardError; end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::FieldDescriptor
  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clear(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def default; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def get(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def has?(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def has_presence?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def is_packed?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def json_name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def label; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def number; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def repeated?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def required?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def set(_arg0, _arg1); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def submsg_name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def subtype; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def type; end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::FileDescriptor
  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf.rb:46
Google::Protobuf::IMPLEMENTATION = T.let(T.unsafe(nil), Symbol)

# pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:10
module Google::Protobuf::Internal; end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::Internal::Arena; end

# pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:42
class Google::Protobuf::Internal::LegacyObjectCache
  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:43
  def initialize; end

  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:49
  def get(key); end

  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:71
  def try_add(key, value); end

  private

  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:86
  def purge; end
end

Google::Protobuf::Internal::OBJECT_CACHE = T.let(T.unsafe(nil), Google::Protobuf::Internal::ObjectCache)

# pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:25
class Google::Protobuf::Internal::ObjectCache
  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:26
  def initialize; end

  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:31
  def get(key); end

  # pkg:gem/google-protobuf#lib/google/protobuf/internal/object_cache.rb:35
  def try_add(key, value); end
end

Google::Protobuf::Internal::SIZEOF_LONG = T.let(T.unsafe(nil), Integer)
Google::Protobuf::Internal::SIZEOF_VALUE = T.let(T.unsafe(nil), Integer)

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::Map
  include ::Enumerable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def ==(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def [](_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def []=(_arg0, _arg1); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clear; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clone; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def delete(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def dup; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def freeze; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def frozen?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def has_key?(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def hash; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def inspect; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def keys; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def length; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def merge(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def size; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_h; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def values; end
end

# pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:10
module Google::Protobuf::MessageExts
  mixes_in_class_methods ::Google::Protobuf::MessageExts::ClassMethods

  # pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:28
  def to_hash; end

  # pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:20
  def to_json(options = T.unsafe(nil)); end

  # pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:24
  def to_proto(options = T.unsafe(nil)); end

  class << self
    # pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:13
    def included(klass); end
  end
end

# pkg:gem/google-protobuf#lib/google/protobuf/message_exts.rb:17
module Google::Protobuf::MessageExts::ClassMethods; end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::MethodDescriptor
  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def client_streaming; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def input_type; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def output_type; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def server_streaming; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::OneofDescriptor
  include ::Enumerable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf.rb:20
Google::Protobuf::PREFER_FFI = T.let(T.unsafe(nil), FalseClass)

# pkg:gem/google-protobuf#lib/google/protobuf.rb:17
class Google::Protobuf::ParseError < ::Google::Protobuf::Error; end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::RepeatedField
  include ::Enumerable
  extend ::Forwardable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def &(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def *(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def +(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def -(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def <<(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def <=>(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def ==(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def [](*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def []=(_arg0, _arg1); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def assoc(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def at(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def bsearch(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def bsearch_index(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clear; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def clone; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def collect!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def combination(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def compact(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def compact!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def concat(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def count(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def cycle(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:104
  def delete(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:104
  def delete_at(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def delete_if(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def difference(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def dig(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def drop(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def drop_while(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def dup; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def each_index(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:92
  def empty?; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def eql?(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def fetch(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def fill(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def find_index(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:58
  def first(n = T.unsafe(nil)); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def flatten(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def flatten!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def freeze; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def frozen?; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def hash; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def include?(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def index(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def insert(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def inspect(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def intersection(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def join(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:151
  def keep_if(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:69
  def last(n = T.unsafe(nil)); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def length; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:99
  def map; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:152
  def map!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def pack(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def permutation(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:81
  def pop(n = T.unsafe(nil)); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def pretty_print(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def pretty_print_cycle(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def product(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def push(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def rassoc(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:153
  def reject!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def repeated_combination(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def repeated_permutation(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def replace(_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def reverse(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def reverse!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def rindex(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def rotate(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def rotate!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def sample(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def select!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def shelljoin(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:104
  def shift(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def shuffle(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def shuffle!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def size; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:97
  def slice(*_arg0); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:104
  def slice!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def sort!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def sort_by!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_ary; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def to_s(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def transpose(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def union(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def uniq(*args, **_arg1, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:116
  def uniq!(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:104
  def unshift(*args, &block); end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:98
  def values_at; end

  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:47
  def |(*args, **_arg1, &block); end

  private

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def pop_one; end

  class << self
    private

    # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:103
    def define_array_wrapper_method(method_name); end

    # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:115
    def define_array_wrapper_with_result_method(method_name); end
  end
end

# pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:159
class Google::Protobuf::RepeatedField::ProxyingEnumerator < ::Struct
  # pkg:gem/google-protobuf#lib/google/protobuf/repeated_field.rb:160
  def each(*args, &block); end
end

# pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
class Google::Protobuf::ServiceDescriptor
  include ::Enumerable

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def initialize(_arg0, _arg1, _arg2); end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def each; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def file_descriptor; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def name; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def options; end

  # pkg:gem/google-protobuf#lib/google/protobuf_native.rb:13
  def to_proto; end
end

# pkg:gem/google-protobuf#lib/google/protobuf.rb:18
class Google::Protobuf::TypeError < ::TypeError; end
