# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `json` gem.
# Please instead update this file by running `bin/tapioca gem json`.


# pkg:gem/json#lib/json/version.rb:3
module JSON
  private

  # pkg:gem/json#lib/json/common.rb:941
  def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:471
  def fast_generate(obj, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:986
  def fast_unparse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/json#lib/json/common.rb:450
  def generate(obj, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:865
  def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:399
  def load_file(filespec, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:410
  def load_file!(filespec, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:362
  def parse(source, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:384
  def parse!(source, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:518
  def pretty_generate(obj, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:996
  def pretty_unparse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/json#lib/json/common.rb:1006
  def restore(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/json#lib/json/common.rb:976
  def unparse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/json#lib/json/common.rb:694
  def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    # pkg:gem/json#lib/json/common.rb:132
    def [](object, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:217
    def _dump_default_options; end

    # pkg:gem/json#lib/json/common.rb:217
    def _load_default_options; end

    # pkg:gem/json#lib/json/common.rb:217
    def _unsafe_load_default_options; end

    # pkg:gem/json#lib/json/common.rb:245
    def create_id; end

    # pkg:gem/json#lib/json/common.rb:239
    def create_id=(new_value); end

    # pkg:gem/json#lib/json/common.rb:104
    def deprecation_warning(message, uplevel = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:941
    def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:217
    def dump_default_options; end

    # pkg:gem/json#lib/json/common.rb:217
    def dump_default_options=(val); end

    # pkg:gem/json#lib/json/common.rb:471
    def fast_generate(obj, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:986
    def fast_unparse(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/json#lib/json/common.rb:450
    def generate(obj, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:188
    def generator; end

    # pkg:gem/json#lib/json/common.rb:156
    def generator=(generator); end

    # pkg:gem/json#lib/json/common.rb:865
    def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:217
    def load_default_options; end

    # pkg:gem/json#lib/json/common.rb:217
    def load_default_options=(val); end

    # pkg:gem/json#lib/json/common.rb:399
    def load_file(filespec, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:410
    def load_file!(filespec, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:362
    def parse(source, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:384
    def parse!(source, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:146
    def parser; end

    # pkg:gem/json#lib/json/common.rb:149
    def parser=(parser); end

    # pkg:gem/json#lib/json/common.rb:518
    def pretty_generate(obj, opts = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:996
    def pretty_unparse(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/json#lib/json/common.rb:1006
    def restore(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/json#lib/json/common.rb:191
    def state; end

    # pkg:gem/json#lib/json/common.rb:191
    def state=(_arg0); end

    # pkg:gem/json#lib/json/common.rb:976
    def unparse(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/json#lib/json/common.rb:694
    def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/json#lib/json/common.rb:217
    def unsafe_load_default_options; end

    # pkg:gem/json#lib/json/common.rb:217
    def unsafe_load_default_options=(val); end

    private

    # pkg:gem/json#lib/json/common.rb:1019
    def const_missing(const_name); end

    # pkg:gem/json#lib/json/common.rb:214
    def deprecated_singleton_attr_accessor(*attrs); end

    # pkg:gem/json#lib/json/common.rb:196
    def on_mixed_keys_hash(hash, do_raise); end
  end
end

# pkg:gem/json#lib/json/common.rb:1045
class JSON::Coder
  # pkg:gem/json#lib/json/common.rb:1070
  def initialize(options = T.unsafe(nil), &as_json); end

  # pkg:gem/json#lib/json/common.rb:1088
  def dump(object, io = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:1091
  def generate(object, io = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:1097
  def load(source); end

  # pkg:gem/json#lib/json/common.rb:1106
  def load_file(path); end

  # pkg:gem/json#lib/json/common.rb:1100
  def parse(source); end
end

# pkg:gem/json#lib/json/ext/generator/state.rb:6
class JSON::Ext::Generator::State
  # pkg:gem/json#lib/json/ext/generator/state.rb:13
  def initialize(opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/ext/generator/state.rb:78
  def [](name); end

  # pkg:gem/json#lib/json/ext/generator/state.rb:92
  def []=(name, value); end

  # pkg:gem/json#lib/json/ext/generator/state.rb:23
  def configure(opts); end

  # pkg:gem/json#lib/json/ext/generator/state.rb:36
  def merge(opts); end

  # pkg:gem/json#lib/json/ext/generator/state.rb:42
  def to_h; end

  # pkg:gem/json#lib/json/ext/generator/state.rb:73
  def to_hash; end
end

# pkg:gem/json#lib/json/ext.rb:9
class JSON::Ext::Parser
  # pkg:gem/json#lib/json/ext.rb:17
  def initialize(source, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/ext.rb:26
  def parse; end

  # pkg:gem/json#lib/json/ext.rb:22
  def source; end

  class << self
    # pkg:gem/json#lib/json/ext.rb:11
    def parse(_arg0, _arg1); end
  end
end

# pkg:gem/json#lib/json/ext.rb:32
JSON::Ext::Parser::Config = JSON::Ext::ParserConfig

# pkg:gem/json#lib/json/common.rb:298
class JSON::Fragment < ::Struct
  # pkg:gem/json#lib/json/common.rb:299
  def initialize(json); end

  # pkg:gem/json#lib/json/common.rb:298
  def json; end

  # pkg:gem/json#lib/json/common.rb:298
  def json=(_); end

  # pkg:gem/json#lib/json/common.rb:307
  def to_json(state = T.unsafe(nil), *_arg1); end

  class << self
    # pkg:gem/json#lib/json/common.rb:298
    def [](*_arg0); end

    # pkg:gem/json#lib/json/common.rb:298
    def inspect; end

    # pkg:gem/json#lib/json/common.rb:298
    def keyword_init?; end

    # pkg:gem/json#lib/json/common.rb:298
    def members; end

    # pkg:gem/json#lib/json/common.rb:298
    def new(*_arg0); end
  end
end

# pkg:gem/json#lib/json/common.rb:268
class JSON::GeneratorError < ::JSON::JSONError
  # pkg:gem/json#lib/json/common.rb:271
  def initialize(message, invalid_object = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:276
  def detailed_message(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/json#lib/json/common.rb:269
  def invalid_object; end
end

# pkg:gem/json#lib/json/common.rb:1111
module JSON::GeneratorMethods
  # pkg:gem/json#lib/json/common.rb:1119
  def to_json(state = T.unsafe(nil), *_arg1); end
end

# pkg:gem/json#lib/json/generic_object.rb:9
class JSON::GenericObject < ::OpenStruct
  # pkg:gem/json#lib/json/generic_object.rb:59
  def as_json(*_arg0); end

  # pkg:gem/json#lib/json/generic_object.rb:51
  def to_hash; end

  # pkg:gem/json#lib/json/generic_object.rb:63
  def to_json(*a); end

  # pkg:gem/json#lib/json/generic_object.rb:55
  def |(other); end

  class << self
    # pkg:gem/json#lib/json/generic_object.rb:11
    def [](*_arg0); end

    # pkg:gem/json#lib/json/generic_object.rb:45
    def dump(obj, *args); end

    # pkg:gem/json#lib/json/generic_object.rb:25
    def from_hash(object); end

    # pkg:gem/json#lib/json/generic_object.rb:17
    def json_creatable=(_arg0); end

    # pkg:gem/json#lib/json/generic_object.rb:13
    def json_creatable?; end

    # pkg:gem/json#lib/json/generic_object.rb:19
    def json_create(data); end

    # pkg:gem/json#lib/json/generic_object.rb:40
    def load(source, proc = T.unsafe(nil), opts = T.unsafe(nil)); end
  end
end

# pkg:gem/json#lib/json/common.rb:367
JSON::PARSE_L_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/json#lib/json/common.rb:480
JSON::PRETTY_GENERATE_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/json#lib/json/common.rb:152
JSON::Parser = JSON::Ext::Parser

# pkg:gem/json#lib/json/common.rb:259
class JSON::ParserError < ::JSON::JSONError
  # pkg:gem/json#lib/json/common.rb:260
  def column; end

  # pkg:gem/json#lib/json/common.rb:260
  def line; end
end

# pkg:gem/json#lib/json/common.rb:8
module JSON::ParserOptions
  class << self
    # pkg:gem/json#lib/json/common.rb:10
    def prepare(opts); end

    private

    # pkg:gem/json#lib/json/common.rb:40
    def array_class_proc(array_class, on_load); end

    # pkg:gem/json#lib/json/common.rb:52
    def create_additions_proc(opts); end

    # pkg:gem/json#lib/json/common.rb:95
    def create_additions_warning; end

    # pkg:gem/json#lib/json/common.rb:29
    def object_class_proc(object_class, on_load); end
  end
end

# pkg:gem/json#lib/json/ext.rb:45
class JSON::ResumableParser
  def initialize(*_arg0); end

  def <<(_arg0); end
  def clear; end

  # pkg:gem/json#lib/json/ext.rb:64
  def empty?; end

  def eos?; end
  def parse; end
  def parsed_bytes; end
  def partial_value; end
  def partial_value?; end
  def rest; end
  def value; end
  def value?; end
end

# pkg:gem/json#lib/json/common.rb:182
JSON::State = JSON::Ext::Generator::State

# pkg:gem/json#lib/json/common.rb:1136
module Kernel
  private

  # pkg:gem/json#lib/json/common.rb:1175
  def JSON(object, opts = T.unsafe(nil)); end

  # pkg:gem/json#lib/json/common.rb:1141
  def j(*objs); end

  # pkg:gem/json#lib/json/common.rb:1156
  def jj(*objs); end
end

# pkg:gem/json#lib/json/common.rb:1180
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::JSON::GeneratorMethods
end
