# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pg` gem.
# Please instead update this file by running `bin/tapioca gem pg`.


# pkg:gem/pg#lib/pg.rb:6
module PG
  include ::PG::Constants

  class << self
    # pkg:gem/pg#lib/pg.rb:87
    def connect(*args, &block); end

    def init_openssl(_arg0, _arg1); end
    def init_ssl(_arg0); end
    def is_threadsafe?; end
    def isthreadsafe; end
    def library_version; end

    # pkg:gem/pg#lib/pg.rb:92
    def make_shareable(obj); end

    # pkg:gem/pg#lib/pg.rb:158
    def require_bigdecimal_without_warning; end

    def threadsafe?; end

    # pkg:gem/pg#lib/pg.rb:81
    def version_string(include_buildnum = T.unsafe(nil)); end
  end
end

class PG::ActiveSqlTransaction < ::PG::InvalidTransactionState; end
class PG::AdminShutdown < ::PG::OperatorIntervention; end
class PG::AmbiguousAlias < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::AmbiguousColumn < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::AmbiguousFunction < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::AmbiguousParameter < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::ArraySubscriptError < ::PG::DataException; end
class PG::AssertFailure < ::PG::PlpgsqlError; end

# pkg:gem/pg#lib/pg.rb:42
PG::BUNDLED_LIBPQ_WITH_UNIXSOCKET = T.let(T.unsafe(nil), T.untyped)

class PG::BadCopyFileFormat < ::PG::DataException; end

# pkg:gem/pg#lib/pg/basic_type_map_based_on_result.rb:56
class PG::BasicTypeMapBasedOnResult < ::PG::TypeMapByOid
  include ::PG::BasicTypeRegistry::Checker

  # pkg:gem/pg#lib/pg/basic_type_map_based_on_result.rb:59
  def initialize(connection_or_coder_maps, registry: T.unsafe(nil)); end
end

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:24
class PG::BasicTypeMapForQueries < ::PG::TypeMapByClass
  include ::PG::BasicTypeRegistry::Checker

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:52
  def initialize(connection_or_coder_maps, registry: T.unsafe(nil), if_undefined: T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:94
  def encode_array_as; end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:79
  def encode_array_as=(pg_type); end

  private

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:156
  def array_encoders_by_klass; end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:104
  def coder_by_name(format, direction, name); end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:163
  def get_array_type(value); end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:98
  def init_encoders; end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:113
  def populate_encoder_list; end

  # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:109
  def undefined(name, format); end
end

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:37
class PG::BasicTypeMapForQueries::BinaryData < ::String; end

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:196
PG::BasicTypeMapForQueries::DEFAULT_ARRAY_TYPE_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:179
PG::BasicTypeMapForQueries::DEFAULT_TYPE_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:60
class PG::BasicTypeMapForQueries::UndefinedDefault
  class << self
    # pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:61
    def call(oid_name, format); end
  end
end

# pkg:gem/pg#lib/pg/basic_type_map_for_queries.rb:40
class PG::BasicTypeMapForQueries::UndefinedEncoder < ::RuntimeError; end

# pkg:gem/pg#lib/pg/basic_type_map_for_results.rb:70
class PG::BasicTypeMapForResults < ::PG::TypeMapByOid
  include ::PG::BasicTypeRegistry::Checker

  # pkg:gem/pg#lib/pg/basic_type_map_for_results.rb:93
  def initialize(connection_or_coder_maps, registry: T.unsafe(nil)); end
end

# pkg:gem/pg#lib/pg/basic_type_map_for_results.rb:73
class PG::BasicTypeMapForResults::WarningTypeMap < ::PG::TypeMapInRuby
  # pkg:gem/pg#lib/pg/basic_type_map_for_results.rb:74
  def initialize(typenames); end

  # pkg:gem/pg#lib/pg/basic_type_map_for_results.rb:79
  def typecast_result_value(result, _tuple, field); end
end

# pkg:gem/pg#lib/pg/basic_type_registry.rb:28
class PG::BasicTypeRegistry
  include ::PG::BasicTypeRegistry::Checker

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:173
  def initialize; end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:216
  def alias_type(format, new, old); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:188
  def coders_for(format, direction); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:307
  def define_default_types; end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:197
  def register_coder(coder); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:229
  def register_default_types; end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:209
  def register_type(format, name, encoder_class, decoder_class); end
end

# pkg:gem/pg#lib/pg/basic_type_registry.rb:151
module PG::BasicTypeRegistry::Checker
  protected

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:161
  def build_coder_maps(conn_or_maps, registry: T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:156
  def check_format_and_direction(format, direction); end
end

# pkg:gem/pg#lib/pg/basic_type_registry.rb:153
PG::BasicTypeRegistry::Checker::ValidDirections = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/basic_type_registry.rb:152
PG::BasicTypeRegistry::Checker::ValidFormats = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/basic_type_registry.rb:33
class PG::BasicTypeRegistry::CoderMap
  # pkg:gem/pg#lib/pg/basic_type_registry.rb:45
  def initialize(result, coders_by_name, format, arraycoder); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:85
  def coder_by_name(name); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:89
  def coder_by_oid(oid); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:81
  def coders; end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:83
  def coders_by_name; end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:82
  def coders_by_oid; end
end

# pkg:gem/pg#lib/pg/basic_type_registry.rb:36
PG::BasicTypeRegistry::CoderMap::DONT_QUOTE_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/basic_type_registry.rb:110
class PG::BasicTypeRegistry::CoderMapsBundle
  # pkg:gem/pg#lib/pg/basic_type_registry.rb:113
  def initialize(connection, registry: T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:142
  def each_format(direction); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:146
  def map_for(format, direction); end

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:111
  def typenames_by_oid; end

  private

  # pkg:gem/pg#lib/pg/basic_type_registry.rb:126
  def init_maps(registry, result); end
end

# pkg:gem/pg#lib/pg/basic_type_registry.rb:309
PG::BasicTypeRegistry::DEFAULT_TYPE_REGISTRY = T.let(T.unsafe(nil), PG::BasicTypeRegistry)

# pkg:gem/pg#lib/pg.rb:101
module PG::BinaryDecoder
  class << self
    private

    def init_date; end
  end
end

class PG::BinaryDecoder::Array < ::PG::CompositeDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Array::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::Boolean < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Boolean::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::Bytea < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Bytea::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::CopyRow < ::PG::CopyDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::CopyRow::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/binary_decoder/date.rb:7
class PG::BinaryDecoder::Date < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg/binary_decoder/date.rb:7
  def decode(*_arg0); end
end

# pkg:gem/pg#lib/pg/binary_decoder/date.rb:7
PG::BinaryDecoder::Date::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::Float < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Float::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::Integer < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Integer::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::String < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::String::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryDecoder::Timestamp < ::PG::SimpleDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::Timestamp::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:19
class PG::BinaryDecoder::TimestampLocal < ::PG::BinaryDecoder::Timestamp
  # pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:20
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:7
class PG::BinaryDecoder::TimestampUtc < ::PG::BinaryDecoder::Timestamp
  # pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:8
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:13
class PG::BinaryDecoder::TimestampUtcToLocal < ::PG::BinaryDecoder::Timestamp
  # pkg:gem/pg#lib/pg/binary_decoder/timestamp.rb:14
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

class PG::BinaryDecoder::ToBase64 < ::PG::CompositeDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::BinaryDecoder::ToBase64::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg.rb:107
module PG::BinaryEncoder; end

class PG::BinaryEncoder::Array < ::PG::CompositeEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Array::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Boolean < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Boolean::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Bytea < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Bytea::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::CopyRow < ::PG::CopyEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::CopyRow::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Date < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Date::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Float4 < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Float4::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Float8 < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Float8::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::FromBase64 < ::PG::CompositeEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::FromBase64::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Int2 < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Int2::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Int4 < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Int4::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Int8 < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Int8::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::String < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::String::CFUNC = T.let(T.unsafe(nil), Object)

class PG::BinaryEncoder::Timestamp < ::PG::SimpleEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::BinaryEncoder::Timestamp::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/binary_encoder/timestamp.rb:13
class PG::BinaryEncoder::TimestampLocal < ::PG::BinaryEncoder::Timestamp
  # pkg:gem/pg#lib/pg/binary_encoder/timestamp.rb:14
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/binary_encoder/timestamp.rb:7
class PG::BinaryEncoder::TimestampUtc < ::PG::BinaryEncoder::Timestamp
  # pkg:gem/pg#lib/pg/binary_encoder/timestamp.rb:8
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

class PG::BranchTransactionAlreadyActive < ::PG::InvalidTransactionState; end

# pkg:gem/pg#lib/pg/cancel_connection.rb:7
class PG::CancelConnection
  include ::Enumerable
  include ::PG::Connection::Pollable

  # pkg:gem/pg#lib/pg.rb:52
  def initialize(conn); end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:44
  def async_cancel; end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:40
  def cancel; end

  # pkg:gem/pg#lib/pg.rb:52
  def error_message; end

  # pkg:gem/pg#lib/pg.rb:52
  def finish; end

  # pkg:gem/pg#lib/pg.rb:52
  def poll; end

  # pkg:gem/pg#lib/pg.rb:52
  def reset; end

  # pkg:gem/pg#lib/pg.rb:52
  def socket_io; end

  # pkg:gem/pg#lib/pg.rb:52
  def start; end

  # pkg:gem/pg#lib/pg.rb:52
  def status; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_cancel; end

  private

  # pkg:gem/pg#lib/pg/cancel_connection.rb:10
  def c_initialize(_arg0); end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:51
  def conninfo_hash; end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:48
  def host; end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:49
  def hostaddr; end

  # pkg:gem/pg#lib/pg/cancel_connection.rb:50
  def port; end
end

class PG::CannotCoerce < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::CannotConnectNow < ::PG::OperatorIntervention; end
class PG::CantChangeRuntimeParam < ::PG::ObjectNotInPrerequisiteState; end
class PG::CardinalityViolation < ::PG::ServerError; end
class PG::CaseNotFound < ::PG::ServerError; end
class PG::CharacterNotInRepertoire < ::PG::DataException; end
class PG::CheckViolation < ::PG::IntegrityConstraintViolation; end

# pkg:gem/pg#lib/pg/coder.rb:6
class PG::Coder
  # pkg:gem/pg#lib/pg/coder.rb:17
  def initialize(hash = T.unsafe(nil), **kwargs); end

  # pkg:gem/pg#lib/pg/coder.rb:39
  def ==(v); end

  # pkg:gem/pg#lib/pg/coder.rb:25
  def dup; end

  # pkg:gem/pg#lib/pg.rb:52
  def flags; end

  # pkg:gem/pg#lib/pg.rb:52
  def flags=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def format; end

  # pkg:gem/pg#lib/pg.rb:52
  def format=(_arg0); end

  # pkg:gem/pg#lib/pg/coder.rb:51
  def inspect; end

  # pkg:gem/pg#lib/pg/coder.rb:60
  def inspect_short; end

  # pkg:gem/pg#lib/pg/coder.rb:43
  def marshal_dump; end

  # pkg:gem/pg#lib/pg/coder.rb:47
  def marshal_load(str); end

  # pkg:gem/pg#lib/pg.rb:52
  def name; end

  # pkg:gem/pg#lib/pg.rb:52
  def name=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def oid; end

  # pkg:gem/pg#lib/pg.rb:52
  def oid=(_arg0); end

  # pkg:gem/pg#lib/pg/coder.rb:30
  def to_h; end
end

# pkg:gem/pg#lib/pg/coder.rb:8
module PG::Coder::BinaryFormatting
  # pkg:gem/pg#lib/pg/coder.rb:9
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

PG::Coder::FORMAT_ERROR_MASK = T.let(T.unsafe(nil), Integer)
PG::Coder::FORMAT_ERROR_TO_PARTIAL = T.let(T.unsafe(nil), Integer)
PG::Coder::FORMAT_ERROR_TO_RAISE = T.let(T.unsafe(nil), Integer)
PG::Coder::FORMAT_ERROR_TO_STRING = T.let(T.unsafe(nil), Integer)
PG::Coder::TIMESTAMP_APP_LOCAL = T.let(T.unsafe(nil), Integer)
PG::Coder::TIMESTAMP_APP_UTC = T.let(T.unsafe(nil), Integer)
PG::Coder::TIMESTAMP_DB_LOCAL = T.let(T.unsafe(nil), Integer)
PG::Coder::TIMESTAMP_DB_UTC = T.let(T.unsafe(nil), Integer)
class PG::CollationMismatch < ::PG::SyntaxErrorOrAccessRuleViolation; end

# pkg:gem/pg#lib/pg/coder.rb:73
class PG::CompositeCoder < ::PG::Coder
  # pkg:gem/pg#lib/pg.rb:52
  def delimiter; end

  # pkg:gem/pg#lib/pg.rb:52
  def delimiter=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def dimensions; end

  # pkg:gem/pg#lib/pg.rb:52
  def dimensions=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def elements_type; end

  # pkg:gem/pg#lib/pg.rb:52
  def elements_type=(_arg0); end

  # pkg:gem/pg#lib/pg/coder.rb:84
  def inspect; end

  # pkg:gem/pg#lib/pg.rb:52
  def needs_quotation=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def needs_quotation?; end

  # pkg:gem/pg#lib/pg/coder.rb:74
  def to_h; end
end

class PG::CompositeDecoder < ::PG::CompositeCoder; end
class PG::CompositeEncoder < ::PG::CompositeCoder; end
class PG::ConfigFileError < ::PG::ServerError; end
class PG::ConfigurationLimitExceeded < ::PG::InsufficientResources; end

# pkg:gem/pg#lib/pg/connection.rb:30
class PG::Connection
  include ::PG::Constants
  include ::PG::Connection::Pollable

  # pkg:gem/pg#lib/pg/connection.rb:673
  def async_cancel; end

  # pkg:gem/pg#lib/pg.rb:52
  def async_close_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_close_prepared(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_describe_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_describe_prepared(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:583
  def async_encrypt_password(password, username, algorithm = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_exec(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_exec_params(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_exec_prepared(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_flush; end

  # pkg:gem/pg#lib/pg/connection.rb:439
  def async_get_copy_data(async = T.unsafe(nil), decoder = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_get_last_result; end

  # pkg:gem/pg#lib/pg/connection.rb:409
  def async_get_result; end

  # pkg:gem/pg#lib/pg/connection.rb:479
  def async_isnonblocking; end

  # pkg:gem/pg#lib/pg/connection.rb:555
  def async_pipeline_sync(*args); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_prepare(*_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:516
  def async_put_copy_data(buffer, encoder = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg/connection.rb:537
  def async_put_copy_end(*args); end

  # pkg:gem/pg#lib/pg.rb:52
  def async_query(*_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:603
  def async_reset; end

  # pkg:gem/pg#lib/pg.rb:52
  def async_set_client_encoding(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:467
  def async_setnonblocking(enabled); end

  # pkg:gem/pg#lib/pg.rb:52
  def backend_pid; end

  # pkg:gem/pg#lib/pg.rb:52
  def block(*_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:626
  def cancel; end

  # pkg:gem/pg#lib/pg/connection.rb:384
  def check_socket; end

  # pkg:gem/pg#lib/pg.rb:52
  def client_encoding=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def close; end

  # pkg:gem/pg#lib/pg.rb:52
  def close_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def close_prepared(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:329
  def conndefaults; end

  # pkg:gem/pg#lib/pg/connection.rb:345
  def conndefaults_hash; end

  # pkg:gem/pg#lib/pg.rb:52
  def connect_poll; end

  # pkg:gem/pg#lib/pg.rb:52
  def connection_needs_password; end

  # pkg:gem/pg#lib/pg.rb:52
  def connection_used_password; end

  # pkg:gem/pg#lib/pg.rb:52
  def conninfo; end

  # pkg:gem/pg#lib/pg/connection.rb:353
  def conninfo_hash; end

  # pkg:gem/pg#lib/pg.rb:52
  def consume_input; end

  # pkg:gem/pg#lib/pg/connection.rb:214
  def copy_data(sql, coder = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def db; end

  # pkg:gem/pg#lib/pg.rb:52
  def decoder_for_get_copy_data; end

  # pkg:gem/pg#lib/pg.rb:52
  def decoder_for_get_copy_data=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def describe_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def describe_prepared(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def discard_results; end

  # pkg:gem/pg#lib/pg.rb:52
  def encoder_for_put_copy_data; end

  # pkg:gem/pg#lib/pg.rb:52
  def encoder_for_put_copy_data=(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:579
  def encrypt_password(password, username, algorithm = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def enter_pipeline_mode; end

  # pkg:gem/pg#lib/pg.rb:52
  def error_message; end

  # pkg:gem/pg#lib/pg.rb:52
  def escape(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def escape_bytea(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def escape_identifier(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def escape_literal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def escape_string(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def exec(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def exec_params(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def exec_prepared(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def exit_pipeline_mode; end

  # pkg:gem/pg#lib/pg.rb:52
  def external_encoding; end

  # pkg:gem/pg#lib/pg.rb:52
  def field_name_type; end

  # pkg:gem/pg#lib/pg.rb:52
  def field_name_type=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def finish; end

  # pkg:gem/pg#lib/pg.rb:52
  def finished?; end

  # pkg:gem/pg#lib/pg.rb:52
  def flush; end

  # pkg:gem/pg#lib/pg.rb:52
  def get_client_encoding; end

  # pkg:gem/pg#lib/pg/connection.rb:428
  def get_copy_data(async = T.unsafe(nil), decoder = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def get_last_result; end

  # pkg:gem/pg#lib/pg/connection.rb:405
  def get_result; end

  # pkg:gem/pg#lib/pg.rb:52
  def host; end

  # pkg:gem/pg#lib/pg.rb:52
  def hostaddr; end

  # pkg:gem/pg#lib/pg/connection.rb:100
  def inspect; end

  # pkg:gem/pg#lib/pg.rb:52
  def internal_encoding; end

  # pkg:gem/pg#lib/pg.rb:52
  def internal_encoding=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def is_busy; end

  # pkg:gem/pg#lib/pg/connection.rb:476
  def isnonblocking; end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_close(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_creat(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_create(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_export(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_import(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_lseek(_arg0, _arg1, _arg2); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_open(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_read(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_seek(_arg0, _arg1, _arg2); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_tell(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_truncate(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_unlink(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lo_write(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def loclose(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def locreat(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def locreate(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def loexport(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def loimport(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lolseek(_arg0, _arg1, _arg2); end

  # pkg:gem/pg#lib/pg.rb:52
  def loopen(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def loread(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def loseek(_arg0, _arg1, _arg2); end

  # pkg:gem/pg#lib/pg.rb:52
  def lotell(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lotruncate(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def lounlink(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def lowrite(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def make_empty_pgresult(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:480
  def nonblocking?; end

  # pkg:gem/pg#lib/pg.rb:52
  def notifies; end

  # pkg:gem/pg#lib/pg.rb:52
  def notifies_wait(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def options; end

  # pkg:gem/pg#lib/pg.rb:52
  def parameter_status(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def pass; end

  # pkg:gem/pg#lib/pg.rb:52
  def pipeline_status; end

  # pkg:gem/pg#lib/pg/connection.rb:551
  def pipeline_sync(*args); end

  # pkg:gem/pg#lib/pg.rb:52
  def port; end

  # pkg:gem/pg#lib/pg.rb:52
  def prepare(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def protocol_version; end

  # pkg:gem/pg#lib/pg/connection.rb:500
  def put_copy_data(buffer, encoder = T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg/connection.rb:530
  def put_copy_end(*args); end

  # pkg:gem/pg#lib/pg/connection.rb:1084
  def query(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def quote_ident(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:591
  def reset; end

  # pkg:gem/pg#lib/pg.rb:52
  def reset_poll; end

  # pkg:gem/pg#lib/pg.rb:52
  def reset_start; end

  # pkg:gem/pg#lib/pg.rb:52
  def send_describe_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def send_describe_prepared(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def send_flush_request; end

  # pkg:gem/pg#lib/pg.rb:52
  def send_pipeline_sync; end

  # pkg:gem/pg#lib/pg.rb:52
  def send_prepare(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def send_query(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def send_query_params(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def send_query_prepared(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def server_version; end

  # pkg:gem/pg#lib/pg.rb:52
  def set_chunked_rows_mode(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def set_client_encoding(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def set_default_encoding; end

  # pkg:gem/pg#lib/pg.rb:52
  def set_error_context_visibility(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def set_error_verbosity(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def set_notice_processor; end

  # pkg:gem/pg#lib/pg.rb:52
  def set_notice_receiver; end

  # pkg:gem/pg#lib/pg.rb:52
  def set_single_row_mode; end

  # pkg:gem/pg#lib/pg/connection.rb:462
  def setnonblocking(enabled); end

  # pkg:gem/pg#lib/pg.rb:52
  def socket; end

  # pkg:gem/pg#lib/pg.rb:52
  def socket_io; end

  # pkg:gem/pg#lib/pg.rb:52
  def ssl_attribute(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def ssl_attribute_names; end

  # pkg:gem/pg#lib/pg/connection.rb:368
  def ssl_attributes; end

  # pkg:gem/pg#lib/pg.rb:52
  def ssl_in_use?; end

  # pkg:gem/pg#lib/pg.rb:52
  def status; end

  # pkg:gem/pg#lib/pg/connection.rb:608
  def sync_cancel; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_close_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_close_prepared(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_describe_portal(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_describe_prepared(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_encrypt_password(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_exec(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_exec_params(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_exec_prepared(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_flush; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_get_copy_data(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_get_last_result; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_get_result; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_isnonblocking; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_pipeline_sync; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_prepare(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_put_copy_data(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_put_copy_end(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_reset; end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_set_client_encoding(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def sync_setnonblocking(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def trace(_arg0); end

  # pkg:gem/pg#lib/pg/connection.rb:308
  def transaction; end

  # pkg:gem/pg#lib/pg.rb:52
  def transaction_status; end

  # pkg:gem/pg#lib/pg.rb:52
  def tty; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map_for_queries; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map_for_queries=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map_for_results; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map_for_results=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def unescape_bytea(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def untrace; end

  # pkg:gem/pg#lib/pg.rb:52
  def user; end

  # pkg:gem/pg#lib/pg.rb:52
  def wait_for_notify(*_arg0); end

  private

  # pkg:gem/pg#lib/pg/connection.rb:793
  def async_connect_or_reset(poll_meth); end

  # pkg:gem/pg#lib/pg.rb:52
  def flush_data=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def reset_start2(_arg0); end

  class << self
    # pkg:gem/pg#lib/pg/connection.rb:1080
    def async_api=(enable); end

    # pkg:gem/pg#lib/pg/connection.rb:882
    def async_connect(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:994
    def async_ping(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:1057
    def async_send_api=(enable); end

    def conndefaults; end

    # pkg:gem/pg#lib/pg/connection.rb:337
    def conndefaults_hash; end

    # pkg:gem/pg#lib/pg/connection.rb:883
    def connect(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:44
    def connect_hash_to_string(hash); end

    def connect_start(*_arg0); end
    def conninfo_parse(_arg0); end
    def encrypt_password(_arg0, _arg1); end
    def escape(_arg0); end
    def escape_bytea(_arg0); end
    def escape_string(_arg0); end

    # pkg:gem/pg#lib/pg/connection.rb:298
    def isthreadsafe; end

    # pkg:gem/pg#lib/pg/connection.rb:870
    def new(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:884
    def open(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:64
    def parse_connect_args(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:985
    def ping(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:37
    def quote_connstr(value); end

    def quote_ident(_arg0); end

    # pkg:gem/pg#lib/pg/connection.rb:885
    def setdb(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:886
    def setdblogin(*args); end

    def sync_connect(*_arg0); end
    def sync_ping(*_arg0); end
    def unescape_bytea(_arg0); end

    private

    # pkg:gem/pg#lib/pg/connection.rb:922
    def connect_to_hosts(*args); end

    # pkg:gem/pg#lib/pg/connection.rb:955
    def host_is_named_pipe?(host_string); end

    # pkg:gem/pg#lib/pg/connection.rb:891
    def resolve_hosts(iopts); end
  end
end

# pkg:gem/pg#lib/pg/connection.rb:120
PG::Connection::BinarySignature = T.let(T.unsafe(nil), String)

# pkg:gem/pg#lib/pg/connection.rb:33
PG::Connection::CONNECT_ARGUMENT_ORDER = T.let(T.unsafe(nil), Array)

# pkg:gem/pg#lib/pg/connection.rb:49
PG::Connection::PROGRAM_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/pg#lib/pg/connection.rb:675
module PG::Connection::Pollable
  private

  # pkg:gem/pg#lib/pg/connection.rb:686
  def polling_loop(poll_meth); end

  # pkg:gem/pg#lib/pg/connection.rb:762
  def remove_current_host(iopts); end
end

class PG::ConnectionBad < ::PG::Error; end
class PG::ConnectionDoesNotExist < ::PG::ConnectionException; end
class PG::ConnectionException < ::PG::ServerError; end
class PG::ConnectionFailure < ::PG::ConnectionException; end
module PG::Constants; end
PG::Constants::CONNECTION_ALLOCATED = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_AUTH_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_AWAITING_RESPONSE = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_BAD = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_CHECK_STANDBY = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_CHECK_TARGET = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_CHECK_WRITABLE = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_CONSUME = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_GSS_STARTUP = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_MADE = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_NEEDED = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_SETENV = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_SSL_STARTUP = T.let(T.unsafe(nil), Integer)
PG::Constants::CONNECTION_STARTED = T.let(T.unsafe(nil), Integer)
PG::Constants::DEF_PGPORT = T.let(T.unsafe(nil), Integer)
PG::Constants::INVALID_OID = T.let(T.unsafe(nil), Integer)
PG::Constants::INV_READ = T.let(T.unsafe(nil), Integer)
PG::Constants::INV_WRITE = T.let(T.unsafe(nil), Integer)
PG::Constants::InvalidOid = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_BAD_RESPONSE = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_COMMAND_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_COPY_BOTH = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_COPY_IN = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_COPY_OUT = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_EMPTY_QUERY = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_FATAL_ERROR = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_NONFATAL_ERROR = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_PIPELINE_ABORTED = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_PIPELINE_SYNC = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_POLLING_FAILED = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_POLLING_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_POLLING_READING = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_POLLING_WRITING = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_SINGLE_TUPLE = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_TUPLES_CHUNK = T.let(T.unsafe(nil), Integer)
PG::Constants::PGRES_TUPLES_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_COLUMN_NAME = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_CONSTRAINT_NAME = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_CONTEXT = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_DATATYPE_NAME = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_INTERNAL_POSITION = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_INTERNAL_QUERY = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_MESSAGE_DETAIL = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_MESSAGE_HINT = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_MESSAGE_PRIMARY = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SCHEMA_NAME = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SEVERITY = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SEVERITY_NONLOCALIZED = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SOURCE_FILE = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SOURCE_FUNCTION = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SOURCE_LINE = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_SQLSTATE = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_STATEMENT_POSITION = T.let(T.unsafe(nil), Integer)
PG::Constants::PG_DIAG_TABLE_NAME = T.let(T.unsafe(nil), Integer)
PG::Constants::PQERRORS_DEFAULT = T.let(T.unsafe(nil), Integer)
PG::Constants::PQERRORS_SQLSTATE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQERRORS_TERSE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQERRORS_VERBOSE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQPING_NO_ATTEMPT = T.let(T.unsafe(nil), Integer)
PG::Constants::PQPING_NO_RESPONSE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQPING_OK = T.let(T.unsafe(nil), Integer)
PG::Constants::PQPING_REJECT = T.let(T.unsafe(nil), Integer)
PG::Constants::PQSHOW_CONTEXT_ALWAYS = T.let(T.unsafe(nil), Integer)
PG::Constants::PQSHOW_CONTEXT_ERRORS = T.let(T.unsafe(nil), Integer)
PG::Constants::PQSHOW_CONTEXT_NEVER = T.let(T.unsafe(nil), Integer)
PG::Constants::PQTRANS_ACTIVE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQTRANS_IDLE = T.let(T.unsafe(nil), Integer)
PG::Constants::PQTRANS_INERROR = T.let(T.unsafe(nil), Integer)
PG::Constants::PQTRANS_INTRANS = T.let(T.unsafe(nil), Integer)
PG::Constants::PQTRANS_UNKNOWN = T.let(T.unsafe(nil), Integer)
PG::Constants::PQ_PIPELINE_ABORTED = T.let(T.unsafe(nil), Integer)
PG::Constants::PQ_PIPELINE_OFF = T.let(T.unsafe(nil), Integer)
PG::Constants::PQ_PIPELINE_ON = T.let(T.unsafe(nil), Integer)
PG::Constants::SEEK_CUR = T.let(T.unsafe(nil), Integer)
PG::Constants::SEEK_END = T.let(T.unsafe(nil), Integer)
PG::Constants::SEEK_SET = T.let(T.unsafe(nil), Integer)

# pkg:gem/pg#lib/pg/coder.rb:91
class PG::CopyCoder < ::PG::Coder
  # pkg:gem/pg#lib/pg.rb:52
  def delimiter; end

  # pkg:gem/pg#lib/pg.rb:52
  def delimiter=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def null_string; end

  # pkg:gem/pg#lib/pg.rb:52
  def null_string=(_arg0); end

  # pkg:gem/pg#lib/pg/coder.rb:92
  def to_h; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map=(_arg0); end
end

class PG::CopyDecoder < ::PG::CopyCoder; end
class PG::CopyEncoder < ::PG::CopyCoder; end
class PG::CrashShutdown < ::PG::OperatorIntervention; end
class PG::DataCorrupted < ::PG::InternalError; end
class PG::DataException < ::PG::ServerError; end
class PG::DatabaseDropped < ::PG::OperatorIntervention; end
class PG::DatatypeMismatch < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DatetimeFieldOverflow < ::PG::DataException; end
class PG::DependentObjectsStillExist < ::PG::DependentPrivilegeDescriptorsStillExist; end
class PG::DependentPrivilegeDescriptorsStillExist < ::PG::ServerError; end
class PG::DiagnosticsException < ::PG::ServerError; end
class PG::DiskFull < ::PG::InsufficientResources; end
class PG::DivisionByZero < ::PG::DataException; end
class PG::DuplicateAlias < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateColumn < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateCursor < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateDatabase < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateFile < ::PG::SystemError; end
class PG::DuplicateFunction < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateJsonObjectKeyValue < ::PG::DataException; end
class PG::DuplicateObject < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicatePstatement < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateSchema < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::DuplicateTable < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::EREContainingSqlNotPermitted < ::PG::ExternalRoutineException; end
class PG::EREModifyingSqlDataNotPermitted < ::PG::ExternalRoutineException; end
class PG::EREProhibitedSqlStatementAttempted < ::PG::ExternalRoutineException; end
class PG::EREReadingSqlDataNotPermitted < ::PG::ExternalRoutineException; end
class PG::ERIEEventTriggerProtocolViolated < ::PG::ExternalRoutineInvocationException; end
class PG::ERIEInvalidSqlstateReturned < ::PG::ExternalRoutineInvocationException; end
class PG::ERIENullValueNotAllowed < ::PG::ExternalRoutineInvocationException; end
class PG::ERIESrfProtocolViolated < ::PG::ExternalRoutineInvocationException; end
class PG::ERIETriggerProtocolViolated < ::PG::ExternalRoutineInvocationException; end
PG::ERROR_CLASSES = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg#lib/pg/exceptions.rb:9
class PG::Error < ::StandardError
  # pkg:gem/pg#lib/pg/exceptions.rb:10
  def initialize(msg = T.unsafe(nil), connection: T.unsafe(nil), result: T.unsafe(nil)); end

  # pkg:gem/pg#lib/pg.rb:52
  def connection; end

  # pkg:gem/pg#lib/pg.rb:52
  def error; end

  # pkg:gem/pg#lib/pg.rb:52
  def result; end
end

class PG::ErrorInAssignment < ::PG::DataException; end
class PG::EscapeCharacterConflict < ::PG::DataException; end
class PG::ExclusionViolation < ::PG::IntegrityConstraintViolation; end
class PG::ExternalRoutineException < ::PG::ServerError; end
class PG::ExternalRoutineInvocationException < ::PG::ServerError; end
class PG::FdwColumnNameNotFound < ::PG::FdwError; end
class PG::FdwDynamicParameterValueNeeded < ::PG::FdwError; end
class PG::FdwError < ::PG::ServerError; end
class PG::FdwFunctionSequenceError < ::PG::FdwError; end
class PG::FdwInconsistentDescriptorInformation < ::PG::FdwError; end
class PG::FdwInvalidAttributeValue < ::PG::FdwError; end
class PG::FdwInvalidColumnName < ::PG::FdwError; end
class PG::FdwInvalidColumnNumber < ::PG::FdwError; end
class PG::FdwInvalidDataType < ::PG::FdwError; end
class PG::FdwInvalidDataTypeDescriptors < ::PG::FdwError; end
class PG::FdwInvalidDescriptorFieldIdentifier < ::PG::FdwError; end
class PG::FdwInvalidHandle < ::PG::FdwError; end
class PG::FdwInvalidOptionIndex < ::PG::FdwError; end
class PG::FdwInvalidOptionName < ::PG::FdwError; end
class PG::FdwInvalidStringFormat < ::PG::FdwError; end
class PG::FdwInvalidStringLengthOrBufferLength < ::PG::FdwError; end
class PG::FdwInvalidUseOfNullPointer < ::PG::FdwError; end
class PG::FdwNoSchemas < ::PG::FdwError; end
class PG::FdwOptionNameNotFound < ::PG::FdwError; end
class PG::FdwOutOfMemory < ::PG::FdwError; end
class PG::FdwReplyHandle < ::PG::FdwError; end
class PG::FdwSchemaNotFound < ::PG::FdwError; end
class PG::FdwTableNotFound < ::PG::FdwError; end
class PG::FdwTooManyHandles < ::PG::FdwError; end
class PG::FdwUnableToCreateExecution < ::PG::FdwError; end
class PG::FdwUnableToCreateReply < ::PG::FdwError; end
class PG::FdwUnableToEstablishConnection < ::PG::FdwError; end
class PG::FeatureNotSupported < ::PG::ServerError; end
class PG::FileNameTooLong < ::PG::SystemError; end
class PG::FloatingPointException < ::PG::DataException; end
class PG::ForeignKeyViolation < ::PG::IntegrityConstraintViolation; end
class PG::GeneratedAlways < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::GroupingError < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::HeldCursorRequiresSameIsolationLevel < ::PG::InvalidTransactionState; end
PG::IS_BINARY_GEM = T.let(T.unsafe(nil), TrueClass)
class PG::IdleInTransactionSessionTimeout < ::PG::InvalidTransactionState; end
class PG::IdleSessionTimeout < ::PG::OperatorIntervention; end
class PG::InFailedSqlTransaction < ::PG::InvalidTransactionState; end
class PG::InappropriateAccessModeForBranchTransaction < ::PG::InvalidTransactionState; end
class PG::InappropriateIsolationLevelForBranchTransaction < ::PG::InvalidTransactionState; end
class PG::IndeterminateCollation < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::IndeterminateDatatype < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::IndexCorrupted < ::PG::InternalError; end
class PG::IndicatorOverflow < ::PG::DataException; end
class PG::InsufficientPrivilege < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InsufficientResources < ::PG::ServerError; end
class PG::IntegrityConstraintViolation < ::PG::ServerError; end
class PG::InternalError < ::PG::ServerError; end
class PG::IntervalFieldOverflow < ::PG::DataException; end
class PG::InvalidArgumentForLog < ::PG::DataException; end
class PG::InvalidArgumentForNthValue < ::PG::DataException; end
class PG::InvalidArgumentForNtile < ::PG::DataException; end
class PG::InvalidArgumentForPowerFunction < ::PG::DataException; end
class PG::InvalidArgumentForSqlJsonDatetimeFunction < ::PG::DataException; end
class PG::InvalidArgumentForWidthBucketFunction < ::PG::DataException; end
class PG::InvalidArgumentForXquery < ::PG::ServerError; end
class PG::InvalidAuthorizationSpecification < ::PG::ServerError; end
class PG::InvalidBinaryRepresentation < ::PG::DataException; end
class PG::InvalidCatalogName < ::PG::ServerError; end
class PG::InvalidChangeOfResultFields < ::PG::Error; end
class PG::InvalidCharacterValueForCast < ::PG::DataException; end
class PG::InvalidColumnDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidColumnReference < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidCursorDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidCursorName < ::PG::ServerError; end
class PG::InvalidCursorState < ::PG::ServerError; end
class PG::InvalidDatabaseDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidDatetimeFormat < ::PG::DataException; end
class PG::InvalidEscapeCharacter < ::PG::DataException; end
class PG::InvalidEscapeOctet < ::PG::DataException; end
class PG::InvalidEscapeSequence < ::PG::DataException; end
class PG::InvalidForeignKey < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidFunctionDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidGrantOperation < ::PG::InvalidGrantor; end
class PG::InvalidGrantor < ::PG::ServerError; end
class PG::InvalidIndicatorParameterValue < ::PG::DataException; end
class PG::InvalidJsonText < ::PG::DataException; end
class PG::InvalidName < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidObjectDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidParameterValue < ::PG::DataException; end
class PG::InvalidPassword < ::PG::InvalidAuthorizationSpecification; end
class PG::InvalidPrecedingOrFollowingSize < ::PG::DataException; end
class PG::InvalidPstatementDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidRecursion < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidRegularExpression < ::PG::DataException; end
class PG::InvalidResultStatus < ::PG::Error; end
class PG::InvalidRoleSpecification < ::PG::ServerError; end
class PG::InvalidRowCountInLimitClause < ::PG::DataException; end
class PG::InvalidRowCountInResultOffsetClause < ::PG::DataException; end
class PG::InvalidSchemaDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidSchemaName < ::PG::ServerError; end
class PG::InvalidSqlJsonSubscript < ::PG::DataException; end
class PG::InvalidSqlStatementName < ::PG::ServerError; end
class PG::InvalidTableDefinition < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::InvalidTablesampleArgument < ::PG::DataException; end
class PG::InvalidTablesampleRepeat < ::PG::DataException; end
class PG::InvalidTextRepresentation < ::PG::DataException; end
class PG::InvalidTimeZoneDisplacementValue < ::PG::DataException; end
class PG::InvalidTransactionInitiation < ::PG::ServerError; end
class PG::InvalidTransactionState < ::PG::ServerError; end
class PG::InvalidTransactionTermination < ::PG::ServerError; end
class PG::InvalidUseOfEscapeCharacter < ::PG::DataException; end
class PG::InvalidXmlComment < ::PG::DataException; end
class PG::InvalidXmlContent < ::PG::DataException; end
class PG::InvalidXmlDocument < ::PG::DataException; end
class PG::InvalidXmlProcessingInstruction < ::PG::DataException; end
class PG::IoError < ::PG::SystemError; end
class PG::LEInvalidSpecification < ::PG::LocatorException; end
class PG::LocatorException < ::PG::ServerError; end
class PG::LockFileExists < ::PG::ConfigFileError; end
class PG::LockNotAvailable < ::PG::ObjectNotInPrerequisiteState; end

# pkg:gem/pg#lib/pg/exceptions.rb:19
class PG::LostCopyState < ::PG::Error; end

class PG::MoreThanOneSqlJsonItem < ::PG::DataException; end
class PG::MostSpecificTypeMismatch < ::PG::DataException; end
class PG::NameTooLong < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::NoActiveSqlTransaction < ::PG::InvalidTransactionState; end
class PG::NoActiveSqlTransactionForBranchTransaction < ::PG::InvalidTransactionState; end
class PG::NoDataFound < ::PG::PlpgsqlError; end
class PG::NoResultError < ::PG::Error; end
class PG::NoSqlJsonItem < ::PG::DataException; end
class PG::NonNumericSqlJsonItem < ::PG::DataException; end
class PG::NonUniqueKeysInAJsonObject < ::PG::DataException; end
class PG::NonstandardUseOfEscapeCharacter < ::PG::DataException; end

# pkg:gem/pg#lib/pg/exceptions.rb:17
class PG::NotAllCopyDataRetrieved < ::PG::Error; end

class PG::NotAnXmlDocument < ::PG::DataException; end

# pkg:gem/pg#lib/pg/exceptions.rb:21
class PG::NotInBlockingMode < ::PG::Error; end

class PG::NotNullViolation < ::PG::IntegrityConstraintViolation; end
class PG::NullValueNoIndicatorParameter < ::PG::DataException; end
class PG::NullValueNotAllowed < ::PG::DataException; end
class PG::NumericValueOutOfRange < ::PG::DataException; end
class PG::ObjectInUse < ::PG::ObjectNotInPrerequisiteState; end
class PG::ObjectNotInPrerequisiteState < ::PG::ServerError; end
class PG::OperatorIntervention < ::PG::ServerError; end
class PG::OutOfMemory < ::PG::InsufficientResources; end

# pkg:gem/pg#lib/pg.rb:13
PG::POSTGRESQL_LIB_PATH = T.let(T.unsafe(nil), String)

class PG::PlpgsqlError < ::PG::ServerError; end
class PG::ProgramLimitExceeded < ::PG::ServerError; end
class PG::ProtocolViolation < ::PG::ConnectionException; end
class PG::QueryCanceled < ::PG::OperatorIntervention; end
class PG::RaiseException < ::PG::PlpgsqlError; end
class PG::ReadOnlySqlTransaction < ::PG::InvalidTransactionState; end

# pkg:gem/pg#lib/pg/coder.rb:101
class PG::RecordCoder < ::PG::Coder
  # pkg:gem/pg#lib/pg/coder.rb:102
  def to_h; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map=(_arg0); end
end

class PG::RecordDecoder < ::PG::RecordCoder; end
class PG::RecordEncoder < ::PG::RecordCoder; end
class PG::ReservedName < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::RestrictViolation < ::PG::IntegrityConstraintViolation; end

# pkg:gem/pg#lib/pg/result.rb:7
class PG::Result
  include ::Enumerable
  include ::PG::Constants

  # pkg:gem/pg#lib/pg.rb:52
  def [](_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def autoclear?; end

  # pkg:gem/pg#lib/pg.rb:52
  def binary_tuples; end

  # pkg:gem/pg#lib/pg.rb:52
  def check; end

  # pkg:gem/pg#lib/pg.rb:52
  def check_result; end

  # pkg:gem/pg#lib/pg.rb:52
  def clear; end

  # pkg:gem/pg#lib/pg.rb:52
  def cleared?; end

  # pkg:gem/pg#lib/pg.rb:52
  def cmd_status; end

  # pkg:gem/pg#lib/pg.rb:52
  def cmd_tuples; end

  # pkg:gem/pg#lib/pg.rb:52
  def cmdtuples; end

  # pkg:gem/pg#lib/pg.rb:52
  def column_values(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def each; end

  # pkg:gem/pg#lib/pg.rb:52
  def each_row; end

  # pkg:gem/pg#lib/pg.rb:52
  def error_field(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def error_message; end

  # pkg:gem/pg#lib/pg.rb:52
  def fformat(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def field_name_type; end

  # pkg:gem/pg#lib/pg.rb:52
  def field_name_type=(_arg0); end

  # pkg:gem/pg#lib/pg/result.rb:26
  def field_names_as(type); end

  # pkg:gem/pg#lib/pg.rb:52
  def field_values(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def fields; end

  # pkg:gem/pg#lib/pg.rb:52
  def fmod(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def fname(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def fnumber(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def freeze; end

  # pkg:gem/pg#lib/pg.rb:52
  def fsize(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def ftable(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def ftablecol(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def ftype(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def getisnull(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def getlength(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def getvalue(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg/result.rb:32
  def inspect; end

  # pkg:gem/pg#lib/pg/result.rb:16
  def map_types!(type_map); end

  # pkg:gem/pg#lib/pg.rb:52
  def nfields; end

  # pkg:gem/pg#lib/pg.rb:52
  def nparams; end

  # pkg:gem/pg#lib/pg.rb:52
  def ntuples; end

  # pkg:gem/pg#lib/pg.rb:52
  def num_fields; end

  # pkg:gem/pg#lib/pg.rb:52
  def num_tuples; end

  # pkg:gem/pg#lib/pg.rb:52
  def oid_value; end

  # pkg:gem/pg#lib/pg.rb:52
  def paramtype(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def res_status(*_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def result_error_field(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def result_error_message; end

  # pkg:gem/pg#lib/pg.rb:52
  def result_status; end

  # pkg:gem/pg#lib/pg.rb:52
  def result_verbose_error_message(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def stream_each; end

  # pkg:gem/pg#lib/pg.rb:52
  def stream_each_row; end

  # pkg:gem/pg#lib/pg.rb:52
  def stream_each_tuple; end

  # pkg:gem/pg#lib/pg.rb:52
  def tuple(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def tuple_values(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map; end

  # pkg:gem/pg#lib/pg.rb:52
  def type_map=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def values; end

  # pkg:gem/pg#lib/pg.rb:52
  def verbose_error_message(_arg0, _arg1); end

  class << self
    def res_status(_arg0); end
  end
end

# pkg:gem/pg#lib/pg/exceptions.rb:27
class PG::RollbackTransaction < ::StandardError; end

class PG::SEInvalidSpecification < ::PG::SavepointException; end
class PG::SREFunctionExecutedNoReturnStatement < ::PG::SqlRoutineException; end
class PG::SREModifyingSqlDataNotPermitted < ::PG::SqlRoutineException; end
class PG::SREProhibitedSqlStatementAttempted < ::PG::SqlRoutineException; end
class PG::SREReadingSqlDataNotPermitted < ::PG::SqlRoutineException; end
class PG::SavepointException < ::PG::ServerError; end
class PG::SchemaAndDataStatementMixingNotSupported < ::PG::InvalidTransactionState; end
class PG::SequenceGeneratorLimitExceeded < ::PG::DataException; end
class PG::ServerError < ::PG::Error; end
class PG::SimpleCoder < ::PG::Coder; end
class PG::SimpleDecoder < ::PG::SimpleCoder; end
class PG::SimpleEncoder < ::PG::SimpleCoder; end
class PG::SingletonSqlJsonItemRequired < ::PG::DataException; end
class PG::SqlJsonArrayNotFound < ::PG::DataException; end
class PG::SqlJsonItemCannotBeCastToTargetType < ::PG::DataException; end
class PG::SqlJsonMemberNotFound < ::PG::DataException; end
class PG::SqlJsonNumberNotFound < ::PG::DataException; end
class PG::SqlJsonObjectNotFound < ::PG::DataException; end
class PG::SqlJsonScalarRequired < ::PG::DataException; end
class PG::SqlRoutineException < ::PG::ServerError; end
class PG::SqlStatementNotYetComplete < ::PG::ServerError; end
class PG::SqlclientUnableToEstablishSqlconnection < ::PG::ConnectionException; end
class PG::SqlserverRejectedEstablishmentOfSqlconnection < ::PG::ConnectionException; end
class PG::StackedDiagnosticsAccessedWithoutActiveHandler < ::PG::DiagnosticsException; end
class PG::StatementTooComplex < ::PG::ProgramLimitExceeded; end
class PG::StringDataLengthMismatch < ::PG::DataException; end
class PG::StringDataRightTruncation < ::PG::DataException; end
class PG::SubstringError < ::PG::DataException; end
class PG::SyntaxError < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::SyntaxErrorOrAccessRuleViolation < ::PG::ServerError; end
class PG::SystemError < ::PG::ServerError; end
class PG::TRDeadlockDetected < ::PG::TransactionRollback; end
class PG::TRIntegrityConstraintViolation < ::PG::TransactionRollback; end
class PG::TRSerializationFailure < ::PG::TransactionRollback; end
class PG::TRStatementCompletionUnknown < ::PG::TransactionRollback; end

# pkg:gem/pg#lib/pg.rb:112
module PG::TextDecoder
  class << self
    private

    def init_inet; end
    def init_numeric; end
  end
end

class PG::TextDecoder::Array < ::PG::CompositeDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Array::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::Boolean < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Boolean::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::Bytea < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Bytea::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::CopyRow < ::PG::CopyDecoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::CopyRow::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_decoder/date.rb:11
class PG::TextDecoder::Date < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg/text_decoder/date.rb:12
  def decode(string, tuple = T.unsafe(nil), field = T.unsafe(nil)); end
end

class PG::TextDecoder::Float < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Float::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::FromBase64 < ::PG::CompositeDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::FromBase64::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::Identifier < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Identifier::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_decoder/inet.rb:7
class PG::TextDecoder::Inet < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg/text_decoder/inet.rb:7
  def decode(*_arg0); end
end

# pkg:gem/pg#lib/pg/text_decoder/inet.rb:7
PG::TextDecoder::Inet::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::Integer < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Integer::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_decoder/json.rb:11
class PG::TextDecoder::JSON < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg/text_decoder/json.rb:12
  def decode(string, tuple = T.unsafe(nil), field = T.unsafe(nil)); end
end

# pkg:gem/pg#lib/pg/text_decoder/numeric.rb:7
class PG::TextDecoder::Numeric < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg/text_decoder/numeric.rb:7
  def decode(*_arg0); end
end

# pkg:gem/pg#lib/pg/text_decoder/numeric.rb:7
PG::TextDecoder::Numeric::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::Record < ::PG::RecordDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Record::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextDecoder::String < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::String::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:28
class PG::TextDecoder::Timestamp < ::PG::SimpleDecoder
  # pkg:gem/pg#lib/pg.rb:52
  def decode(*_arg0); end
end

PG::TextDecoder::Timestamp::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:19
class PG::TextDecoder::TimestampLocal < ::PG::TextDecoder::Timestamp
  # pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:20
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:7
class PG::TextDecoder::TimestampUtc < ::PG::TextDecoder::Timestamp
  # pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:8
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:13
class PG::TextDecoder::TimestampUtcToLocal < ::PG::TextDecoder::Timestamp
  # pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:14
  def initialize(hash = T.unsafe(nil), **kwargs); end
end

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:28
PG::TextDecoder::TimestampWithTimeZone = PG::TextDecoder::Timestamp

# pkg:gem/pg#lib/pg/text_decoder/timestamp.rb:27
PG::TextDecoder::TimestampWithoutTimeZone = PG::TextDecoder::TimestampLocal

# pkg:gem/pg#lib/pg.rb:121
module PG::TextEncoder
  class << self
    private

    def init_numeric; end
  end
end

class PG::TextEncoder::Array < ::PG::CompositeEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Array::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::Boolean < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Boolean::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::Bytea < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Bytea::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::CopyRow < ::PG::CopyEncoder
  include ::PG::Coder::BinaryFormatting

  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::CopyRow::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_encoder/date.rb:7
class PG::TextEncoder::Date < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/date.rb:8
  def encode(value); end
end

class PG::TextEncoder::Float < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Float::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::Identifier < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Identifier::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_encoder/inet.rb:11
class PG::TextEncoder::Inet < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/inet.rb:12
  def encode(value); end
end

class PG::TextEncoder::Integer < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Integer::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_encoder/json.rb:11
class PG::TextEncoder::JSON < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/json.rb:12
  def encode(value); end
end

# pkg:gem/pg#lib/pg/text_encoder/numeric.rb:7
class PG::TextEncoder::Numeric < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/numeric.rb:7
  def encode(*_arg0); end
end

# pkg:gem/pg#lib/pg/text_encoder/numeric.rb:7
PG::TextEncoder::Numeric::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::QuotedLiteral < ::PG::CompositeEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::QuotedLiteral::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::Record < ::PG::RecordEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::Record::CFUNC = T.let(T.unsafe(nil), Object)

class PG::TextEncoder::String < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::String::CFUNC = T.let(T.unsafe(nil), Object)

# pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:12
class PG::TextEncoder::TimestampUtc < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:13
  def encode(value); end
end

# pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:18
class PG::TextEncoder::TimestampWithTimeZone < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:19
  def encode(value); end
end

# pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:6
class PG::TextEncoder::TimestampWithoutTimeZone < ::PG::SimpleEncoder
  # pkg:gem/pg#lib/pg/text_encoder/timestamp.rb:7
  def encode(value); end
end

class PG::TextEncoder::ToBase64 < ::PG::CompositeEncoder
  # pkg:gem/pg#lib/pg.rb:52
  def encode(*_arg0); end
end

PG::TextEncoder::ToBase64::CFUNC = T.let(T.unsafe(nil), Object)
class PG::TooManyArguments < ::PG::ProgramLimitExceeded; end
class PG::TooManyColumns < ::PG::ProgramLimitExceeded; end
class PG::TooManyConnections < ::PG::InsufficientResources; end
class PG::TooManyJsonArrayElements < ::PG::DataException; end
class PG::TooManyJsonObjectMembers < ::PG::DataException; end
class PG::TooManyRows < ::PG::PlpgsqlError; end
class PG::TransactionResolutionUnknown < ::PG::ConnectionException; end
class PG::TransactionRollback < ::PG::ServerError; end
class PG::TransactionTimeout < ::PG::InvalidTransactionState; end
class PG::TriggeredActionException < ::PG::ServerError; end
class PG::TriggeredDataChangeViolation < ::PG::ServerError; end
class PG::TrimError < ::PG::DataException; end

# pkg:gem/pg#lib/pg/tuple.rb:7
class PG::Tuple
  include ::Enumerable

  # pkg:gem/pg#lib/pg.rb:52
  def [](_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def each; end

  # pkg:gem/pg#lib/pg/tuple.rb:23
  def each_key(&block); end

  # pkg:gem/pg#lib/pg.rb:52
  def each_value; end

  # pkg:gem/pg#lib/pg.rb:52
  def fetch(*_arg0); end

  # pkg:gem/pg#lib/pg/tuple.rb:14
  def has_key?(key); end

  # pkg:gem/pg#lib/pg.rb:52
  def index(_arg0); end

  # pkg:gem/pg#lib/pg/tuple.rb:10
  def inspect; end

  # pkg:gem/pg#lib/pg/tuple.rb:17
  def key?(key); end

  # pkg:gem/pg#lib/pg/tuple.rb:19
  def keys; end

  # pkg:gem/pg#lib/pg.rb:52
  def length; end

  # pkg:gem/pg#lib/pg.rb:52
  def size; end

  # pkg:gem/pg#lib/pg.rb:52
  def values; end

  private

  # pkg:gem/pg#lib/pg.rb:52
  def field_map; end

  # pkg:gem/pg#lib/pg.rb:52
  def field_names; end

  # pkg:gem/pg#lib/pg.rb:52
  def marshal_dump; end

  # pkg:gem/pg#lib/pg.rb:52
  def marshal_load(_arg0); end
end

class PG::TypeMap; end

module PG::TypeMap::DefaultTypeMappable
  # pkg:gem/pg#lib/pg.rb:52
  def default_type_map; end

  # pkg:gem/pg#lib/pg.rb:52
  def default_type_map=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def with_default_type_map(_arg0); end
end

class PG::TypeMapAllStrings < ::PG::TypeMap; end

class PG::TypeMapByClass < ::PG::TypeMap
  include ::PG::TypeMap::DefaultTypeMappable

  # pkg:gem/pg#lib/pg.rb:52
  def [](_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def []=(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def coders; end
end

# pkg:gem/pg#lib/pg/type_map_by_column.rb:6
class PG::TypeMapByColumn < ::PG::TypeMap
  include ::PG::TypeMap::DefaultTypeMappable

  # pkg:gem/pg#lib/pg.rb:52
  def initialize(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def coders; end

  # pkg:gem/pg#lib/pg/type_map_by_column.rb:12
  def inspect; end

  # pkg:gem/pg#lib/pg/type_map_by_column.rb:8
  def oids; end
end

class PG::TypeMapByMriType < ::PG::TypeMap
  include ::PG::TypeMap::DefaultTypeMappable

  # pkg:gem/pg#lib/pg.rb:52
  def [](_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def []=(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def coders; end
end

class PG::TypeMapByOid < ::PG::TypeMap
  include ::PG::TypeMap::DefaultTypeMappable

  # pkg:gem/pg#lib/pg.rb:52
  def add_coder(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def build_column_map(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def coders; end

  # pkg:gem/pg#lib/pg.rb:52
  def max_rows_for_online_lookup; end

  # pkg:gem/pg#lib/pg.rb:52
  def max_rows_for_online_lookup=(_arg0); end

  # pkg:gem/pg#lib/pg.rb:52
  def rm_coder(_arg0, _arg1); end
end

class PG::TypeMapInRuby < ::PG::TypeMap
  include ::PG::TypeMap::DefaultTypeMappable

  # pkg:gem/pg#lib/pg.rb:52
  def typecast_copy_get(_arg0, _arg1, _arg2, _arg3); end

  # pkg:gem/pg#lib/pg.rb:52
  def typecast_query_param(_arg0, _arg1); end

  # pkg:gem/pg#lib/pg.rb:52
  def typecast_result_value(_arg0, _arg1, _arg2); end
end

class PG::UnableToSend < ::PG::Error; end
class PG::UndefinedColumn < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::UndefinedFile < ::PG::SystemError; end
class PG::UndefinedFunction < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::UndefinedObject < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::UndefinedParameter < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::UndefinedTable < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::UniqueViolation < ::PG::IntegrityConstraintViolation; end
class PG::UnsafeNewEnumValueUsage < ::PG::ObjectNotInPrerequisiteState; end
class PG::UnterminatedCString < ::PG::DataException; end
class PG::UntranslatableCharacter < ::PG::DataException; end

# pkg:gem/pg#lib/pg/version.rb:4
PG::VERSION = T.let(T.unsafe(nil), String)

class PG::WindowingError < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::WithCheckOptionViolation < ::PG::ServerError; end
class PG::WrongObjectType < ::PG::SyntaxErrorOrAccessRuleViolation; end
class PG::ZeroLengthCharacterString < ::PG::DataException; end
