# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack` gem.
# Please instead update this file by running `bin/tapioca gem rack`.


# pkg:gem/rack#lib/rack/version.rb:8
module Rack
  class << self
    # pkg:gem/rack#lib/rack/version.rb:14
    def release; end
  end
end

# pkg:gem/rack#lib/rack.rb:59
module Rack::Auth; end

# pkg:gem/rack#lib/rack/auth/abstract/handler.rb:11
class Rack::Auth::AbstractHandler
  # pkg:gem/rack#lib/rack/auth/abstract/handler.rb:15
  def initialize(app, realm = T.unsafe(nil), &authenticator); end

  # pkg:gem/rack#lib/rack/auth/abstract/handler.rb:13
  def realm; end

  # pkg:gem/rack#lib/rack/auth/abstract/handler.rb:13
  def realm=(_arg0); end

  private

  # pkg:gem/rack#lib/rack/auth/abstract/handler.rb:31
  def bad_request; end

  # pkg:gem/rack#lib/rack/auth/abstract/handler.rb:22
  def unauthorized(www_authenticate = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/auth/abstract/request.rb:8
class Rack::Auth::AbstractRequest
  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:10
  def initialize(env); end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:35
  def params; end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:27
  def parts; end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:19
  def provided?; end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:14
  def request; end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:31
  def scheme; end

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:23
  def valid?; end

  private

  # pkg:gem/rack#lib/rack/auth/abstract/request.rb:44
  def authorization_key; end
end

# pkg:gem/rack#lib/rack/auth/abstract/request.rb:42
Rack::Auth::AbstractRequest::AUTHORIZATION_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/auth/basic.rb:13
class Rack::Auth::Basic < ::Rack::Auth::AbstractHandler
  # pkg:gem/rack#lib/rack/auth/basic.rb:15
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/auth/basic.rb:34
  def challenge; end

  # pkg:gem/rack#lib/rack/auth/basic.rb:38
  def valid?(auth); end
end

# pkg:gem/rack#lib/rack/auth/basic.rb:42
class Rack::Auth::Basic::Request < ::Rack::Auth::AbstractRequest
  # pkg:gem/rack#lib/rack/auth/basic.rb:43
  def basic?; end

  # pkg:gem/rack#lib/rack/auth/basic.rb:47
  def credentials; end

  # pkg:gem/rack#lib/rack/auth/basic.rb:51
  def username; end
end

# pkg:gem/rack#lib/rack/builder.rb:6
Rack::BUILDER_TOPLEVEL_BINDING = T.let(T.unsafe(nil), Proc)

# pkg:gem/rack#lib/rack/bad_request.rb:6
module Rack::BadRequest; end

# pkg:gem/rack#lib/rack/body_proxy.rb:7
class Rack::BodyProxy
  # pkg:gem/rack#lib/rack/body_proxy.rb:10
  def initialize(body, &block); end

  # pkg:gem/rack#lib/rack/body_proxy.rb:28
  def close; end

  # pkg:gem/rack#lib/rack/body_proxy.rb:40
  def closed?; end

  # pkg:gem/rack#lib/rack/body_proxy.rb:45
  def method_missing(method_name, *args, **_arg2, &block); end

  private

  # pkg:gem/rack#lib/rack/body_proxy.rb:17
  def respond_to_missing?(method_name, include_all = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/builder.rb:36
class Rack::Builder
  # pkg:gem/rack#lib/rack/builder.rb:116
  def initialize(default_app = T.unsafe(nil), **options, &block); end

  # pkg:gem/rack#lib/rack/builder.rb:282
  def call(env); end

  # pkg:gem/rack#lib/rack/builder.rb:265
  def freeze_app; end

  # pkg:gem/rack#lib/rack/builder.rb:256
  def map(path, &block); end

  # pkg:gem/rack#lib/rack/builder.rb:132
  def options; end

  # pkg:gem/rack#lib/rack/builder.rb:195
  def run(app = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/builder.rb:270
  def to_app; end

  # pkg:gem/rack#lib/rack/builder.rb:159
  def use(middleware, *args, **_arg2, &block); end

  # pkg:gem/rack#lib/rack/builder.rb:213
  def warmup(prc = T.unsafe(nil), &block); end

  private

  # pkg:gem/rack#lib/rack/builder.rb:290
  def generate_map(default_app, mapping); end

  class << self
    # pkg:gem/rack#lib/rack/builder.rb:136
    def app(default_app = T.unsafe(nil), &block); end

    # pkg:gem/rack#lib/rack/builder.rb:87
    def load_file(path, **options); end

    # pkg:gem/rack#lib/rack/builder.rb:102
    def new_from_string(builder_script, path = T.unsafe(nil), **options); end

    # pkg:gem/rack#lib/rack/builder.rb:65
    def parse_file(path, **options); end
  end
end

# pkg:gem/rack#lib/rack/builder.rb:39
Rack::Builder::UTF_8_BOM = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:19
Rack::CACHE_CONTROL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:35
Rack::CONNECT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:20
Rack::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:21
Rack::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/cascade.rb:11
class Rack::Cascade
  # pkg:gem/rack#lib/rack/cascade.rb:21
  def initialize(apps, cascade_for = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/cascade.rb:65
  def <<(app); end

  # pkg:gem/rack#lib/rack/cascade.rb:56
  def add(app); end

  # pkg:gem/rack#lib/rack/cascade.rb:13
  def apps; end

  # pkg:gem/rack#lib/rack/cascade.rb:32
  def call(env); end

  # pkg:gem/rack#lib/rack/cascade.rb:61
  def include?(app); end
end

# pkg:gem/rack#lib/rack/common_logger.rb:13
class Rack::CommonLogger
  # pkg:gem/rack#lib/rack/common_logger.rb:29
  def initialize(app, logger = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/common_logger.rb:41
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/common_logger.rb:84
  def extract_content_length(headers); end

  # pkg:gem/rack#lib/rack/common_logger.rb:52
  def log(env, status, response_headers, began_at); end
end

# pkg:gem/rack#lib/rack/common_logger.rb:23
Rack::CommonLogger::FORMAT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/conditional_get.rb:21
class Rack::ConditionalGet
  # pkg:gem/rack#lib/rack/conditional_get.rb:22
  def initialize(app); end

  # pkg:gem/rack#lib/rack/conditional_get.rb:28
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/conditional_get.rb:63
  def etag_matches?(none_match, headers); end

  # pkg:gem/rack#lib/rack/conditional_get.rb:52
  def fresh?(env, headers); end

  # pkg:gem/rack#lib/rack/conditional_get.rb:69
  def modified_since?(modified_since, headers); end

  # pkg:gem/rack#lib/rack/conditional_get.rb:76
  def to_rfc2822(since); end
end

# pkg:gem/rack#lib/rack/config.rb:11
class Rack::Config
  # pkg:gem/rack#lib/rack/config.rb:12
  def initialize(app, &block); end

  # pkg:gem/rack#lib/rack/config.rb:17
  def call(env); end
end

# pkg:gem/rack#lib/rack/content_length.rb:12
class Rack::ContentLength
  include ::Rack::Utils

  # pkg:gem/rack#lib/rack/content_length.rb:15
  def initialize(app); end

  # pkg:gem/rack#lib/rack/content_length.rb:19
  def call(env); end
end

# pkg:gem/rack#lib/rack/content_type.rb:15
class Rack::ContentType
  include ::Rack::Utils

  # pkg:gem/rack#lib/rack/content_type.rb:18
  def initialize(app, content_type = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/content_type.rb:23
  def call(env); end
end

# pkg:gem/rack#lib/rack/constants.rb:32
Rack::DELETE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/deflater.rb:28
class Rack::Deflater
  # pkg:gem/rack#lib/rack/deflater.rb:39
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/deflater.rb:46
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/deflater.rb:136
  def should_deflate?(env, status, headers, body); end
end

# pkg:gem/rack#lib/rack/deflater.rb:83
class Rack::Deflater::GzipStream
  # pkg:gem/rack#lib/rack/deflater.rb:92
  def initialize(body, mtime, sync); end

  # pkg:gem/rack#lib/rack/deflater.rb:128
  def close; end

  # pkg:gem/rack#lib/rack/deflater.rb:99
  def each(&block); end

  # pkg:gem/rack#lib/rack/deflater.rb:123
  def write(data); end
end

# pkg:gem/rack#lib/rack/deflater.rb:85
Rack::Deflater::GzipStream::BUFFER_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/directory.rb:19
class Rack::Directory
  # pkg:gem/rack#lib/rack/directory.rb:83
  def initialize(root, app = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/directory.rb:90
  def call(env); end

  # pkg:gem/rack#lib/rack/directory.rb:110
  def check_bad_request(path_info); end

  # pkg:gem/rack#lib/rack/directory.rb:120
  def check_forbidden(path_info); end

  # pkg:gem/rack#lib/rack/directory.rb:184
  def entity_not_found(path_info); end

  # pkg:gem/rack#lib/rack/directory.rb:200
  def filesize_format(int); end

  # pkg:gem/rack#lib/rack/directory.rb:97
  def get(env); end

  # pkg:gem/rack#lib/rack/directory.rb:133
  def list_directory(path_info, path, script_name); end

  # pkg:gem/rack#lib/rack/directory.rb:174
  def list_path(env, path, path_info, script_name); end

  # pkg:gem/rack#lib/rack/directory.rb:80
  def root; end

  # pkg:gem/rack#lib/rack/directory.rb:166
  def stat(path); end
end

# pkg:gem/rack#lib/rack/directory.rb:20
Rack::Directory::DIR_FILE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/directory.rb:43
Rack::Directory::DIR_PAGE_FOOTER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/directory.rb:21
Rack::Directory::DIR_PAGE_HEADER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/directory.rb:51
class Rack::Directory::DirectoryBody < ::Struct
  # pkg:gem/rack#lib/rack/directory.rb:53
  def each; end

  private

  # pkg:gem/rack#lib/rack/directory.rb:73
  def DIR_FILE_escape(htmls); end
end

# pkg:gem/rack#lib/rack/directory.rb:192
Rack::Directory::FILESIZE_FORMAT = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/constants.rb:22
Rack::ETAG = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/etag.rb:18
class Rack::ETag
  # pkg:gem/rack#lib/rack/etag.rb:22
  def initialize(app, no_cache_control = T.unsafe(nil), cache_control = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/etag.rb:28
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/etag.rb:61
  def digest_body(body); end

  # pkg:gem/rack#lib/rack/etag.rb:53
  def etag_status?(status); end

  # pkg:gem/rack#lib/rack/etag.rb:57
  def skip_caching?(headers); end
end

# pkg:gem/rack#lib/rack/etag.rb:20
Rack::ETag::DEFAULT_CACHE_CONTROL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/etag.rb:19
Rack::ETag::ETAG_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:23
Rack::EXPIRES = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/events.rb:62
class Rack::Events
  # pkg:gem/rack#lib/rack/events.rb:121
  def initialize(app, handlers); end

  # pkg:gem/rack#lib/rack/events.rb:126
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/events.rb:164
  def make_request(env); end

  # pkg:gem/rack#lib/rack/events.rb:168
  def make_response(status, headers, body); end

  # pkg:gem/rack#lib/rack/events.rb:152
  def on_commit(request, response); end

  # pkg:gem/rack#lib/rack/events.rb:148
  def on_error(request, response, e); end

  # pkg:gem/rack#lib/rack/events.rb:160
  def on_finish(request, response); end

  # pkg:gem/rack#lib/rack/events.rb:156
  def on_start(request, response); end
end

# pkg:gem/rack#lib/rack/events.rb:63
module Rack::Events::Abstract
  # pkg:gem/rack#lib/rack/events.rb:67
  def on_commit(req, res); end

  # pkg:gem/rack#lib/rack/events.rb:76
  def on_error(req, res, e); end

  # pkg:gem/rack#lib/rack/events.rb:73
  def on_finish(req, res); end

  # pkg:gem/rack#lib/rack/events.rb:70
  def on_send(req, res); end

  # pkg:gem/rack#lib/rack/events.rb:64
  def on_start(req, res); end
end

# pkg:gem/rack#lib/rack/events.rb:110
class Rack::Events::BufferedResponse < ::Rack::Response::Raw
  # pkg:gem/rack#lib/rack/events.rb:113
  def initialize(status, headers, body); end

  # pkg:gem/rack#lib/rack/events.rb:111
  def body; end

  # pkg:gem/rack#lib/rack/events.rb:118
  def to_a; end
end

# pkg:gem/rack#lib/rack/events.rb:80
class Rack::Events::EventedBodyProxy < ::Rack::BodyProxy
  # pkg:gem/rack#lib/rack/events.rb:83
  def initialize(body, request, response, handlers, &block); end

  # pkg:gem/rack#lib/rack/events.rb:95
  def call(stream); end

  # pkg:gem/rack#lib/rack/events.rb:90
  def each; end

  # pkg:gem/rack#lib/rack/events.rb:81
  def request; end

  # pkg:gem/rack#lib/rack/events.rb:100
  def respond_to?(method_name, include_all = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/events.rb:81
  def response; end
end

# pkg:gem/rack#lib/rack/files.rb:20
class Rack::Files
  # pkg:gem/rack#lib/rack/files.rb:27
  def initialize(root, headers = T.unsafe(nil), default_mime = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/files.rb:34
  def call(env); end

  # pkg:gem/rack#lib/rack/files.rb:39
  def get(env); end

  # pkg:gem/rack#lib/rack/files.rb:25
  def root; end

  # pkg:gem/rack#lib/rack/files.rb:68
  def serving(request, path); end

  private

  # pkg:gem/rack#lib/rack/files.rb:190
  def fail(status, body, headers = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/files.rb:209
  def filesize(path); end

  # pkg:gem/rack#lib/rack/files.rb:205
  def mime_type(path, default_mime); end
end

# pkg:gem/rack#lib/rack/files.rb:21
Rack::Files::ALLOWED_VERBS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/files.rb:22
Rack::Files::ALLOW_HEADER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/files.rb:121
class Rack::Files::BaseIterator
  # pkg:gem/rack#lib/rack/files.rb:124
  def initialize(path, ranges, options); end

  # pkg:gem/rack#lib/rack/files.rb:144
  def bytesize; end

  # pkg:gem/rack#lib/rack/files.rb:153
  def close; end

  # pkg:gem/rack#lib/rack/files.rb:130
  def each; end

  # pkg:gem/rack#lib/rack/files.rb:122
  def options; end

  # pkg:gem/rack#lib/rack/files.rb:122
  def path; end

  # pkg:gem/rack#lib/rack/files.rb:122
  def ranges; end

  private

  # pkg:gem/rack#lib/rack/files.rb:171
  def each_range_part(file, range); end

  # pkg:gem/rack#lib/rack/files.rb:157
  def multipart?; end

  # pkg:gem/rack#lib/rack/files.rb:161
  def multipart_heading(range); end
end

# pkg:gem/rack#lib/rack/files.rb:184
class Rack::Files::Iterator < ::Rack::Files::BaseIterator
  # pkg:gem/rack#lib/rack/files.rb:185
  def to_path; end
end

# pkg:gem/rack#lib/rack/files.rb:23
Rack::Files::MULTIPART_BOUNDARY = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/recursive.rb:14
class Rack::ForwardRequest < ::Exception
  # pkg:gem/rack#lib/rack/recursive.rb:17
  def initialize(url, env = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/recursive.rb:15
  def env; end

  # pkg:gem/rack#lib/rack/recursive.rb:15
  def url; end
end

# pkg:gem/rack#lib/rack/constants.rb:28
Rack::GET = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:33
Rack::HEAD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:7
Rack::HTTPS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:16
Rack::HTTP_COOKIE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:5
Rack::HTTP_HOST = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:6
Rack::HTTP_PORT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/head.rb:9
class Rack::Head
  # pkg:gem/rack#lib/rack/head.rb:10
  def initialize(app); end

  # pkg:gem/rack#lib/rack/head.rb:14
  def call(env); end
end

# pkg:gem/rack#lib/rack/headers.rb:8
class Rack::Headers < ::Hash
  # pkg:gem/rack#lib/rack/headers.rb:110
  def [](key); end

  # pkg:gem/rack#lib/rack/headers.rb:114
  def []=(key, value); end

  # pkg:gem/rack#lib/rack/headers.rb:119
  def assoc(key); end

  # pkg:gem/rack#lib/rack/headers.rb:123
  def compare_by_identity; end

  # pkg:gem/rack#lib/rack/headers.rb:127
  def delete(key); end

  # pkg:gem/rack#lib/rack/headers.rb:131
  def dig(key, *a); end

  # pkg:gem/rack#lib/rack/headers.rb:227
  def except(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:135
  def fetch(key, *default, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:140
  def fetch_values(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:144
  def has_key?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:147
  def include?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:151
  def invert; end

  # pkg:gem/rack#lib/rack/headers.rb:148
  def key?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:149
  def member?(key); end

  # pkg:gem/rack#lib/rack/headers.rb:157
  def merge(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:196
  def merge!(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:161
  def reject(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:167
  def replace(hash); end

  # pkg:gem/rack#lib/rack/headers.rb:172
  def select(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:205
  def slice(*a); end

  # pkg:gem/rack#lib/rack/headers.rb:117
  def store(key, value); end

  # pkg:gem/rack#lib/rack/headers.rb:178
  def to_proc; end

  # pkg:gem/rack#lib/rack/headers.rb:211
  def transform_keys(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:215
  def transform_keys!; end

  # pkg:gem/rack#lib/rack/headers.rb:182
  def transform_values(&block); end

  # pkg:gem/rack#lib/rack/headers.rb:186
  def update(hash, &block); end

  # pkg:gem/rack#lib/rack/headers.rb:198
  def values_at(*keys); end

  private

  # pkg:gem/rack#lib/rack/headers.rb:234
  def downcase_key(key); end

  class << self
    # pkg:gem/rack#lib/rack/headers.rb:91
    def [](*items); end
  end
end

# pkg:gem/rack#lib/rack/headers.rb:9
Rack::Headers::KNOWN_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/constants.rb:36
Rack::LINK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/lint.rb:10
class Rack::Lint
  # pkg:gem/rack#lib/rack/lint.rb:65
  def initialize(app); end

  # pkg:gem/rack#lib/rack/lint.rb:15
  def call(env = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/lint.rb:21
Rack::Lint::ALLOWED_SCHEMES = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/lint.rb:29
Rack::Lint::HOST_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:52
Rack::Lint::HTTP_HOST_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:12
class Rack::Lint::LintError < ::RuntimeError; end

# pkg:gem/rack#lib/rack/lint.rb:24
Rack::Lint::REQUEST_PATH_ABSOLUTE_FORM = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:26
Rack::Lint::REQUEST_PATH_ASTERISK_FORM = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/lint.rb:25
Rack::Lint::REQUEST_PATH_AUTHORITY_FORM = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:23
Rack::Lint::REQUEST_PATH_ORIGIN_FORM = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:51
Rack::Lint::SERVER_NAME_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/lint.rb:71
class Rack::Lint::Wrapper
  # pkg:gem/rack#lib/rack/lint.rb:72
  def initialize(app, env); end

  # pkg:gem/rack#lib/rack/lint.rb:918
  def call(stream); end

  # pkg:gem/rack#lib/rack/lint.rb:768
  def check_content_length_header(status, headers); end

  # pkg:gem/rack#lib/rack/lint.rb:753
  def check_content_type_header(status, headers); end

  # pkg:gem/rack#lib/rack/lint.rb:670
  def check_early_hints(env); end

  # pkg:gem/rack#lib/rack/lint.rb:136
  def check_environment(env); end

  # pkg:gem/rack#lib/rack/lint.rb:571
  def check_error_stream(error); end

  # pkg:gem/rack#lib/rack/lint.rb:743
  def check_header_value(key, value); end

  # pkg:gem/rack#lib/rack/lint.rb:704
  def check_headers(headers); end

  # pkg:gem/rack#lib/rack/lint.rb:618
  def check_hijack(env); end

  # pkg:gem/rack#lib/rack/lint.rb:639
  def check_hijack_response(headers, env); end

  # pkg:gem/rack#lib/rack/lint.rb:478
  def check_input_stream(input); end

  # pkg:gem/rack#lib/rack/lint.rb:795
  def check_rack_protocol_header(status, headers); end

  # pkg:gem/rack#lib/rack/lint.rb:694
  def check_status(status); end

  # pkg:gem/rack#lib/rack/lint.rb:821
  def close; end

  # pkg:gem/rack#lib/rack/lint.rb:852
  def each; end

  # pkg:gem/rack#lib/rack/lint.rb:895
  def respond_to?(name, *_arg1); end

  # pkg:gem/rack#lib/rack/lint.rb:87
  def response; end

  # pkg:gem/rack#lib/rack/lint.rb:905
  def to_ary; end

  # pkg:gem/rack#lib/rack/lint.rb:891
  def to_path; end

  # pkg:gem/rack#lib/rack/lint.rb:780
  def verify_content_length(size); end

  # pkg:gem/rack#lib/rack/lint.rb:835
  def verify_to_path; end

  private

  # pkg:gem/rack#lib/rack/lint.rb:126
  def assert_required(key); end
end

# pkg:gem/rack#lib/rack/lint.rb:889
Rack::Lint::Wrapper::BODY_METHODS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/lint.rb:580
class Rack::Lint::Wrapper::ErrorWrapper
  # pkg:gem/rack#lib/rack/lint.rb:581
  def initialize(error); end

  # pkg:gem/rack#lib/rack/lint.rb:602
  def close(*args); end

  # pkg:gem/rack#lib/rack/lint.rb:597
  def flush; end

  # pkg:gem/rack#lib/rack/lint.rb:586
  def puts(str); end

  # pkg:gem/rack#lib/rack/lint.rb:591
  def write(str); end
end

# pkg:gem/rack#lib/rack/lint.rb:495
class Rack::Lint::Wrapper::InputWrapper
  # pkg:gem/rack#lib/rack/lint.rb:496
  def initialize(input); end

  # pkg:gem/rack#lib/rack/lint.rb:563
  def close(*args); end

  # pkg:gem/rack#lib/rack/lint.rb:552
  def each(*args); end

  # pkg:gem/rack#lib/rack/lint.rb:501
  def gets(*args); end

  # pkg:gem/rack#lib/rack/lint.rb:519
  def read(*args); end
end

# pkg:gem/rack#lib/rack/lint.rb:936
class Rack::Lint::Wrapper::StreamWrapper
  extend ::Forwardable

  # pkg:gem/rack#lib/rack/lint.rb:947
  def initialize(stream); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def <<(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def close(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def close_read(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def close_write(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def closed?(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def flush(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def read(*args, **_arg1, &block); end

  # pkg:gem/rack#lib/rack/lint.rb:945
  def write(*args, **_arg1, &block); end
end

# pkg:gem/rack#lib/rack/lint.rb:940
Rack::Lint::Wrapper::StreamWrapper::REQUIRED_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/lock.rb:8
class Rack::Lock
  # pkg:gem/rack#lib/rack/lock.rb:9
  def initialize(app, mutex = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/lock.rb:13
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/lock.rb:25
  def unlock; end
end

# pkg:gem/rack#lib/rack/media_type.rb:6
class Rack::MediaType
  class << self
    # pkg:gem/rack#lib/rack/media_type.rb:34
    def params(content_type); end

    # pkg:gem/rack#lib/rack/media_type.rb:16
    def type(content_type); end

    private

    # pkg:gem/rack#lib/rack/media_type.rb:47
    def strip_doublequotes(str); end
  end
end

# pkg:gem/rack#lib/rack/media_type.rb:7
Rack::MediaType::SPLIT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/method_override.rb:8
class Rack::MethodOverride
  # pkg:gem/rack#lib/rack/method_override.rb:15
  def initialize(app); end

  # pkg:gem/rack#lib/rack/method_override.rb:19
  def call(env); end

  # pkg:gem/rack#lib/rack/method_override.rb:31
  def method_override(env); end

  private

  # pkg:gem/rack#lib/rack/method_override.rb:44
  def allowed_methods; end

  # pkg:gem/rack#lib/rack/method_override.rb:48
  def method_override_param(req); end
end

# pkg:gem/rack#lib/rack/method_override.rb:13
Rack::MethodOverride::ALLOWED_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/method_override.rb:9
Rack::MethodOverride::HTTP_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/method_override.rb:12
Rack::MethodOverride::HTTP_METHOD_OVERRIDE_HEADER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/method_override.rb:11
Rack::MethodOverride::METHOD_OVERRIDE_PARAM_KEY = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/mime.rb:4
module Rack::Mime
  private

  # pkg:gem/rack#lib/rack/mime.rb:30
  def match?(value, matcher); end

  # pkg:gem/rack#lib/rack/mime.rb:18
  def mime_type(ext, fallback = T.unsafe(nil)); end

  class << self
    # pkg:gem/rack#lib/rack/mime.rb:36
    def match?(value, matcher); end

    # pkg:gem/rack#lib/rack/mime.rb:21
    def mime_type(ext, fallback = T.unsafe(nil)); end
  end
end

# pkg:gem/rack#lib/rack/mime.rb:51
Rack::Mime::MIME_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/mock_request.rb:23
class Rack::MockRequest
  # pkg:gem/rack#lib/rack/mock_request.rb:44
  def initialize(app); end

  # pkg:gem/rack#lib/rack/mock_request.rb:57
  def delete(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:49
  def get(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:59
  def head(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:61
  def options(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:55
  def patch(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:51
  def post(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:53
  def put(uri, opts = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_request.rb:66
  def request(method = T.unsafe(nil), uri = T.unsafe(nil), opts = T.unsafe(nil)); end

  class << self
    # pkg:gem/rack#lib/rack/mock_request.rb:98
    def env_for(uri = T.unsafe(nil), opts = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/mock_request.rb:84
    def parse_uri_rfc2396(uri); end
  end
end

# pkg:gem/rack#lib/rack/mock_request.rb:27
class Rack::MockRequest::FatalWarner
  # pkg:gem/rack#lib/rack/mock_request.rb:36
  def flush; end

  # pkg:gem/rack#lib/rack/mock_request.rb:28
  def puts(warning); end

  # pkg:gem/rack#lib/rack/mock_request.rb:39
  def string; end

  # pkg:gem/rack#lib/rack/mock_request.rb:32
  def write(warning); end
end

# pkg:gem/rack#lib/rack/mock_request.rb:24
class Rack::MockRequest::FatalWarning < ::RuntimeError; end

# pkg:gem/rack#lib/rack/mock_response.rb:13
class Rack::MockResponse < ::Rack::Response
  # pkg:gem/rack#lib/rack/mock_response.rb:48
  def initialize(status, headers, body, errors = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/mock_response.rb:63
  def =~(other); end

  # pkg:gem/rack#lib/rack/mock_response.rb:71
  def body; end

  # pkg:gem/rack#lib/rack/mock_response.rb:105
  def cookie(name); end

  # pkg:gem/rack#lib/rack/mock_response.rb:43
  def cookies; end

  # pkg:gem/rack#lib/rack/mock_response.rb:101
  def empty?; end

  # pkg:gem/rack#lib/rack/mock_response.rb:46
  def errors; end

  # pkg:gem/rack#lib/rack/mock_response.rb:46
  def errors=(_arg0); end

  # pkg:gem/rack#lib/rack/mock_response.rb:67
  def match(other); end

  # pkg:gem/rack#lib/rack/mock_response.rb:43
  def original_headers; end

  private

  # pkg:gem/rack#lib/rack/mock_response.rb:132
  def identify_cookie_attributes(cookie_filling); end

  # pkg:gem/rack#lib/rack/mock_response.rb:111
  def parse_cookies_from_header; end

  class << self
    # pkg:gem/rack#lib/rack/mock_response.rb:39
    def [](*_arg0); end
  end
end

# pkg:gem/rack#lib/rack/mock_response.rb:14
class Rack::MockResponse::Cookie
  # pkg:gem/rack#lib/rack/mock_response.rb:17
  def initialize(args); end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def domain; end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def expires; end

  # pkg:gem/rack#lib/rack/mock_response.rb:26
  def method_missing(method_name, *args, **_arg2, &block); end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def name; end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def path; end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def secure; end

  # pkg:gem/rack#lib/rack/mock_response.rb:15
  def value; end

  private

  # pkg:gem/rack#lib/rack/mock_response.rb:33
  def respond_to_missing?(method_name, include_all = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:9
module Rack::Multipart
  class << self
    # pkg:gem/rack#lib/rack/multipart.rb:72
    def build_multipart(params, first = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/multipart.rb:68
    def extract_multipart(request, params = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/multipart.rb:48
    def parse_multipart(env, params = T.unsafe(nil)); end
  end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:26
class Rack::Multipart::BoundaryTooLongError < ::StandardError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:33
Rack::Multipart::EOL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/multipart/parser.rb:20
class Rack::Multipart::EmptyContentError < ::EOFError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:31
Rack::Multipart::Error = Rack::Multipart::BoundaryTooLongError

# pkg:gem/rack#lib/rack/multipart/parser.rb:34
Rack::Multipart::FWS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart/generator.rb:7
class Rack::Multipart::Generator
  # pkg:gem/rack#lib/rack/multipart/generator.rb:8
  def initialize(params, first = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/multipart/generator.rb:16
  def dump; end

  private

  # pkg:gem/rack#lib/rack/multipart/generator.rb:89
  def content_for_other(file, name); end

  # pkg:gem/rack#lib/rack/multipart/generator.rb:77
  def content_for_tempfile(io, file, name); end

  # pkg:gem/rack#lib/rack/multipart/generator.rb:52
  def flattened_params; end

  # pkg:gem/rack#lib/rack/multipart/generator.rb:37
  def multipart?; end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:35
Rack::Multipart::HEADER_VALUE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/multipart/parser.rb:36
Rack::Multipart::MULTIPART = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart.rb:16
Rack::Multipart::MULTIPART_BOUNDARY = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/multipart/parser.rb:38
Rack::Multipart::MULTIPART_CONTENT_DISPOSITION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart/parser.rb:39
Rack::Multipart::MULTIPART_CONTENT_ID = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart/parser.rb:37
Rack::Multipart::MULTIPART_CONTENT_TYPE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart.rb:18
class Rack::Multipart::MissingInputError < ::StandardError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:10
class Rack::Multipart::MultipartPartLimitError < ::Errno::EMFILE
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:14
class Rack::Multipart::MultipartTotalPartLimitError < ::StandardError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/multipart.rb:25
class Rack::Multipart::ParamList
  # pkg:gem/rack#lib/rack/multipart.rb:34
  def initialize; end

  # pkg:gem/rack#lib/rack/multipart.rb:38
  def <<(pair); end

  # pkg:gem/rack#lib/rack/multipart.rb:42
  def to_params_hash; end

  class << self
    # pkg:gem/rack#lib/rack/multipart.rb:26
    def make_params; end

    # pkg:gem/rack#lib/rack/multipart.rb:30
    def normalize_params(params, key, value); end
  end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:53
class Rack::Multipart::Parser
  # pkg:gem/rack#lib/rack/multipart/parser.rb:254
  def initialize(boundary, tempfile, bufsize, query_parser); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:275
  def parse(io); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:299
  def result; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:252
  def state; end

  private

  # pkg:gem/rack#lib/rack/multipart/parser.rb:534
  def consume_boundary; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:589
  def find_encoding(enc); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:358
  def handle_consume_token; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:604
  def handle_dummy_encoding(name, body); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:614
  def handle_empty_content!(content); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:331
  def handle_fast_forward; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:501
  def handle_mime_body; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:373
  def handle_mime_head; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:543
  def normalize_filename(filename); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:312
  def read_data(io, outbuf); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:556
  def tag_multipart_encoding(filename, content_type, name, body); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:523
  def update_retained_size(size); end

  class << self
    # pkg:gem/rack#lib/rack/multipart/parser.rb:137
    def parse(io, content_length, content_type, tmpfile, bufsize, qp); end

    # pkg:gem/rack#lib/rack/multipart/parser.rb:122
    def parse_boundary(content_type); end
  end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:62
Rack::Multipart::Parser::BOUNDARY_START_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:80
Rack::Multipart::Parser::BUFFERED_UPLOAD_BYTESIZE_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:54
Rack::Multipart::Parser::BUFSIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:90
class Rack::Multipart::Parser::BoundedIO
  # pkg:gem/rack#lib/rack/multipart/parser.rb:91
  def initialize(io, content_length); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:97
  def read(size, outbuf = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:553
Rack::Multipart::Parser::CHARSET = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/multipart/parser.rb:369
Rack::Multipart::Parser::CONTENT_DISPOSITION_MAX_BYTES = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:368
Rack::Multipart::Parser::CONTENT_DISPOSITION_MAX_PARAMS = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:87
Rack::Multipart::Parser::CONTENT_DISPOSITION_QUOTED_ESCAPES_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:161
class Rack::Multipart::Parser::Collector
  include ::Enumerable

  # pkg:gem/rack#lib/rack/multipart/parser.rb:197
  def initialize(tempfile); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:203
  def each; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:223
  def on_mime_body(mime_index, content); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:227
  def on_mime_finish(mime_index); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:207
  def on_mime_head(mime_index, head, filename, content_type, name); end

  private

  # pkg:gem/rack#lib/rack/multipart/parser.rb:232
  def check_part_limits; end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:185
class Rack::Multipart::Parser::Collector::BufferPart < ::Rack::Multipart::Parser::Collector::MimePart
  # pkg:gem/rack#lib/rack/multipart/parser.rb:187
  def close; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:186
  def file?; end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:162
class Rack::Multipart::Parser::Collector::MimePart < ::Struct
  # pkg:gem/rack#lib/rack/multipart/parser.rb:163
  def get_data; end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:190
class Rack::Multipart::Parser::Collector::TempfilePart < ::Rack::Multipart::Parser::Collector::MimePart
  # pkg:gem/rack#lib/rack/multipart/parser.rb:192
  def close; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:191
  def file?; end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:120
Rack::Multipart::Parser::EMPTY = T.let(T.unsafe(nil), Rack::Multipart::Parser::MultipartInfo)

# pkg:gem/rack#lib/rack/multipart/parser.rb:65
Rack::Multipart::Parser::MIME_HEADER_BYTESIZE_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:119
class Rack::Multipart::Parser::MultipartInfo < ::Struct
  # pkg:gem/rack#lib/rack/multipart/parser.rb:119
  def params; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:119
  def params=(_); end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:119
  def tmp_files; end

  # pkg:gem/rack#lib/rack/multipart/parser.rb:119
  def tmp_files=(_); end

  class << self
    # pkg:gem/rack#lib/rack/multipart/parser.rb:119
    def [](*_arg0); end

    # pkg:gem/rack#lib/rack/multipart/parser.rb:119
    def inspect; end

    # pkg:gem/rack#lib/rack/multipart/parser.rb:119
    def keyword_init?; end

    # pkg:gem/rack#lib/rack/multipart/parser.rb:119
    def members; end

    # pkg:gem/rack#lib/rack/multipart/parser.rb:119
    def new(*_arg0); end
  end
end

# pkg:gem/rack#lib/rack/multipart/parser.rb:370
Rack::Multipart::Parser::OBS_UNFOLD = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/multipart/parser.rb:84
Rack::Multipart::Parser::PARSER_BYTESIZE_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/multipart/parser.rb:595
Rack::Multipart::Parser::REENCODE_DUMMY_ENCODINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/multipart/parser.rb:56
Rack::Multipart::Parser::TEMPFILE_FACTORY = T.let(T.unsafe(nil), Proc)

# pkg:gem/rack#lib/rack/multipart/parser.rb:55
Rack::Multipart::Parser::TEXT_PLAIN = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:19
class Rack::Multipart::UploadedFile
  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:49
  def initialize(filepath = T.unsafe(nil), ct = T.unsafe(nil), bin = T.unsafe(nil), path: T.unsafe(nil), content_type: T.unsafe(nil), binary: T.unsafe(nil), filename: T.unsafe(nil), io: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:26
  def content_type; end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:26
  def content_type=(_arg0); end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:69
  def local_path; end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:77
  def method_missing(method_name, *args, &block); end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:23
  def original_filename; end

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:66
  def path; end

  private

  # pkg:gem/rack#lib/rack/multipart/uploaded_file.rb:72
  def respond_to_missing?(*args); end
end

# pkg:gem/rack#lib/rack/null_logger.rb:6
class Rack::NullLogger
  # pkg:gem/rack#lib/rack/null_logger.rb:7
  def initialize(app); end

  # pkg:gem/rack#lib/rack/null_logger.rb:45
  def <<(msg); end

  # pkg:gem/rack#lib/rack/null_logger.rb:43
  def add(severity, message = T.unsafe(nil), progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:11
  def call(env); end

  # pkg:gem/rack#lib/rack/null_logger.rb:42
  def close; end

  # pkg:gem/rack#lib/rack/null_logger.rb:34
  def datetime_format; end

  # pkg:gem/rack#lib/rack/null_logger.rb:39
  def datetime_format=(datetime_format); end

  # pkg:gem/rack#lib/rack/null_logger.rb:17
  def debug(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:27
  def debug!; end

  # pkg:gem/rack#lib/rack/null_logger.rb:23
  def debug?; end

  # pkg:gem/rack#lib/rack/null_logger.rb:19
  def error(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:28
  def error!; end

  # pkg:gem/rack#lib/rack/null_logger.rb:25
  def error?; end

  # pkg:gem/rack#lib/rack/null_logger.rb:20
  def fatal(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:29
  def fatal!; end

  # pkg:gem/rack#lib/rack/null_logger.rb:26
  def fatal?; end

  # pkg:gem/rack#lib/rack/null_logger.rb:35
  def formatter; end

  # pkg:gem/rack#lib/rack/null_logger.rb:40
  def formatter=(formatter); end

  # pkg:gem/rack#lib/rack/null_logger.rb:16
  def info(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:30
  def info!; end

  # pkg:gem/rack#lib/rack/null_logger.rb:22
  def info?; end

  # pkg:gem/rack#lib/rack/null_logger.rb:32
  def level; end

  # pkg:gem/rack#lib/rack/null_logger.rb:37
  def level=(level); end

  # pkg:gem/rack#lib/rack/null_logger.rb:44
  def log(severity, message = T.unsafe(nil), progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:33
  def progname; end

  # pkg:gem/rack#lib/rack/null_logger.rb:38
  def progname=(progname); end

  # pkg:gem/rack#lib/rack/null_logger.rb:46
  def reopen(logdev = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/null_logger.rb:36
  def sev_threshold; end

  # pkg:gem/rack#lib/rack/null_logger.rb:41
  def sev_threshold=(sev_threshold); end

  # pkg:gem/rack#lib/rack/null_logger.rb:21
  def unknown(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:18
  def warn(progname = T.unsafe(nil), &block); end

  # pkg:gem/rack#lib/rack/null_logger.rb:31
  def warn!; end

  # pkg:gem/rack#lib/rack/null_logger.rb:24
  def warn?; end
end

# pkg:gem/rack#lib/rack/constants.rb:34
Rack::OPTIONS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:31
Rack::PATCH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:8
Rack::PATH_INFO = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:29
Rack::POST = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:30
Rack::PUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:12
Rack::QUERY_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/query_parser.rb:7
class Rack::QueryParser
  # pkg:gem/rack#lib/rack/query_parser.rb:62
  def initialize(params_class, param_depth_limit, bytesize_limit: T.unsafe(nil), params_limit: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:60
  def bytesize_limit; end

  # pkg:gem/rack#lib/rack/query_parser.rb:196
  def make_params; end

  # pkg:gem/rack#lib/rack/query_parser.rb:200
  def new_depth_limit(param_depth_limit); end

  # pkg:gem/rack#lib/rack/query_parser.rb:124
  def normalize_params(params, name, v, _depth = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:40
  def param_depth_limit; end

  # pkg:gem/rack#lib/rack/query_parser.rb:109
  def parse_nested_query(qs, separator = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:73
  def parse_query(qs, separator = T.unsafe(nil), &unescaper); end

  # pkg:gem/rack#lib/rack/query_parser.rb:94
  def parse_query_pairs(qs, separator = T.unsafe(nil)); end

  private

  # pkg:gem/rack#lib/rack/query_parser.rb:128
  def _normalize_params(params, name, v, depth); end

  # pkg:gem/rack#lib/rack/query_parser.rb:222
  def each_query_pair(qs, separator, unescaper = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/query_parser.rb:210
  def params_hash_has_key?(hash, key); end

  # pkg:gem/rack#lib/rack/query_parser.rb:206
  def params_hash_type?(obj); end

  # pkg:gem/rack#lib/rack/query_parser.rb:253
  def unescape(string, encoding = T.unsafe(nil)); end

  class << self
    # pkg:gem/rack#lib/rack/query_parser.rb:36
    def make_default(param_depth_limit, **options); end
  end
end

# pkg:gem/rack#lib/rack/query_parser.rb:54
Rack::QueryParser::BYTESIZE_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/query_parser.rb:9
Rack::QueryParser::COMMON_SEP = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/query_parser.rb:8
Rack::QueryParser::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/query_parser.rb:20
class Rack::QueryParser::InvalidParameterError < ::ArgumentError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/query_parser.rb:57
Rack::QueryParser::PARAMS_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/query_parser.rb:13
class Rack::QueryParser::ParameterTypeError < ::TypeError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/query_parser.rb:257
class Rack::QueryParser::Params < ::Hash
  # pkg:gem/rack#lib/rack/query_parser.rb:258
  def to_params_hash; end
end

# pkg:gem/rack#lib/rack/query_parser.rb:34
Rack::QueryParser::ParamsTooDeepError = Rack::QueryParser::QueryLimitError

# pkg:gem/rack#lib/rack/query_parser.rb:26
class Rack::QueryParser::QueryLimitError < ::RangeError
  include ::Rack::BadRequest
end

# pkg:gem/rack#lib/rack/constants.rb:43
Rack::RACK_EARLY_HINTS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:44
Rack::RACK_ERRORS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:51
Rack::RACK_HIJACK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:46
Rack::RACK_INPUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:52
Rack::RACK_IS_HIJACK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:45
Rack::RACK_LOGGER = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:67
Rack::RACK_METHODOVERRIDE_ORIGINAL_METHOD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:54
Rack::RACK_MULTIPART_BUFFER_SIZE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:55
Rack::RACK_MULTIPART_TEMPFILE_FACTORY = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:57
Rack::RACK_PROTOCOL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:53
Rack::RACK_RECURSIVE_INCLUDE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:63
Rack::RACK_REQUEST_COOKIE_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:64
Rack::RACK_REQUEST_COOKIE_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:62
Rack::RACK_REQUEST_FORM_ERROR = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:59
Rack::RACK_REQUEST_FORM_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:58
Rack::RACK_REQUEST_FORM_INPUT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:60
Rack::RACK_REQUEST_FORM_PAIRS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:61
Rack::RACK_REQUEST_FORM_VARS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:65
Rack::RACK_REQUEST_QUERY_HASH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:66
Rack::RACK_REQUEST_QUERY_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:56
Rack::RACK_RESPONSE_FINISHED = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:47
Rack::RACK_SESSION = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:48
Rack::RACK_SESSION_OPTIONS = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:49
Rack::RACK_SHOWSTATUS_DETAIL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:42
Rack::RACK_TEMPFILES = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:50
Rack::RACK_URL_SCHEME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:41
Rack::RACK_VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/version.rb:11
Rack::RELEASE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:9
Rack::REQUEST_METHOD = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:10
Rack::REQUEST_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/recursive.rb:36
class Rack::Recursive
  # pkg:gem/rack#lib/rack/recursive.rb:37
  def initialize(app); end

  # pkg:gem/rack#lib/rack/recursive.rb:45
  def _call(env); end

  # pkg:gem/rack#lib/rack/recursive.rb:41
  def call(env); end

  # pkg:gem/rack#lib/rack/recursive.rb:52
  def include(env, path); end
end

# pkg:gem/rack#lib/rack/reloader.rb:24
class Rack::Reloader
  # pkg:gem/rack#lib/rack/reloader.rb:25
  def initialize(app, cooldown = T.unsafe(nil), backend = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/reloader.rb:36
  def call(env); end

  # pkg:gem/rack#lib/rack/reloader.rb:50
  def reload!(stderr = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/reloader.rb:58
  def safe_load(file, mtime, stderr = T.unsafe(nil)); end
end

# pkg:gem/rack#lib/rack/reloader.rb:68
module Rack::Reloader::Stat
  # pkg:gem/rack#lib/rack/reloader.rb:88
  def figure_path(file, paths); end

  # pkg:gem/rack#lib/rack/reloader.rb:69
  def rotation; end

  # pkg:gem/rack#lib/rack/reloader.rb:103
  def safe_stat(file); end
end

# pkg:gem/rack#lib/rack/request.rb:16
class Rack::Request
  include ::Rack::Request::Env
  include ::Rack::Request::Helpers

  # pkg:gem/rack#lib/rack/request.rb:62
  def initialize(env); end

  # pkg:gem/rack#lib/rack/request.rb:81
  def delete_param(k); end

  # pkg:gem/rack#lib/rack/request.rb:68
  def ip; end

  # pkg:gem/rack#lib/rack/request.rb:72
  def params; end

  # pkg:gem/rack#lib/rack/request.rb:76
  def update_param(k, v); end

  class << self
    # pkg:gem/rack#lib/rack/request.rb:31
    def forwarded_priority; end

    # pkg:gem/rack#lib/rack/request.rb:31
    def forwarded_priority=(_arg0); end

    # pkg:gem/rack#lib/rack/request.rb:18
    def ip_filter; end

    # pkg:gem/rack#lib/rack/request.rb:18
    def ip_filter=(_arg0); end

    # pkg:gem/rack#lib/rack/request.rb:40
    def x_forwarded_proto_priority; end

    # pkg:gem/rack#lib/rack/request.rb:40
    def x_forwarded_proto_priority=(_arg0); end
  end
end

# pkg:gem/rack#lib/rack/request.rb:60
Rack::Request::ALLOWED_SCHEMES = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/request.rb:87
module Rack::Request::Env
  # pkg:gem/rack#lib/rack/request.rb:91
  def initialize(env); end

  # pkg:gem/rack#lib/rack/request.rb:134
  def add_header(key, v); end

  # pkg:gem/rack#lib/rack/request.rb:145
  def delete_header(name); end

  # pkg:gem/rack#lib/rack/request.rb:116
  def each_header(&block); end

  # pkg:gem/rack#lib/rack/request.rb:89
  def env; end

  # pkg:gem/rack#lib/rack/request.rb:111
  def fetch_header(name, &block); end

  # pkg:gem/rack#lib/rack/request.rb:105
  def get_header(name); end

  # pkg:gem/rack#lib/rack/request.rb:100
  def has_header?(name); end

  # pkg:gem/rack#lib/rack/request.rb:121
  def set_header(name, v); end

  private

  # pkg:gem/rack#lib/rack/request.rb:149
  def initialize_copy(other); end
end

# pkg:gem/rack#lib/rack/request.rb:154
module Rack::Request::Helpers
  # pkg:gem/rack#lib/rack/request.rb:491
  def GET; end

  # pkg:gem/rack#lib/rack/request.rb:542
  def POST; end

  # pkg:gem/rack#lib/rack/request.rb:611
  def accept_encoding; end

  # pkg:gem/rack#lib/rack/request.rb:615
  def accept_language; end

  # pkg:gem/rack#lib/rack/request.rb:271
  def authority; end

  # pkg:gem/rack#lib/rack/request.rb:594
  def base_url; end

  # pkg:gem/rack#lib/rack/request.rb:195
  def body; end

  # pkg:gem/rack#lib/rack/request.rb:465
  def content_charset; end

  # pkg:gem/rack#lib/rack/request.rb:204
  def content_length; end

  # pkg:gem/rack#lib/rack/request.rb:313
  def content_type; end

  # pkg:gem/rack#lib/rack/request.rb:298
  def cookies; end

  # pkg:gem/rack#lib/rack/request.rb:225
  def delete?; end

  # pkg:gem/rack#lib/rack/request.rb:589
  def delete_param(k); end

  # pkg:gem/rack#lib/rack/request.rb:477
  def form_data?; end

  # pkg:gem/rack#lib/rack/request.rb:499
  def form_pairs; end

  # pkg:gem/rack#lib/rack/request.rb:398
  def forwarded_authority; end

  # pkg:gem/rack#lib/rack/request.rb:358
  def forwarded_for; end

  # pkg:gem/rack#lib/rack/request.rb:379
  def forwarded_port; end

  # pkg:gem/rack#lib/rack/request.rb:607
  def fullpath; end

  # pkg:gem/rack#lib/rack/request.rb:228
  def get?; end

  # pkg:gem/rack#lib/rack/request.rb:231
  def head?; end

  # pkg:gem/rack#lib/rack/request.rb:338
  def host; end

  # pkg:gem/rack#lib/rack/request.rb:323
  def host_authority; end

  # pkg:gem/rack#lib/rack/request.rb:327
  def host_with_port(authority = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/request.rb:346
  def hostname; end

  # pkg:gem/rack#lib/rack/request.rb:419
  def ip; end

  # pkg:gem/rack#lib/rack/request.rb:237
  def link?; end

  # pkg:gem/rack#lib/rack/request.rb:205
  def logger; end

  # pkg:gem/rack#lib/rack/request.rb:448
  def media_type; end

  # pkg:gem/rack#lib/rack/request.rb:457
  def media_type_params; end

  # pkg:gem/rack#lib/rack/request.rb:234
  def options?; end

  # pkg:gem/rack#lib/rack/request.rb:556
  def params; end

  # pkg:gem/rack#lib/rack/request.rb:486
  def parseable_data?; end

  # pkg:gem/rack#lib/rack/request.rb:240
  def patch?; end

  # pkg:gem/rack#lib/rack/request.rb:603
  def path; end

  # pkg:gem/rack#lib/rack/request.rb:199
  def path_info; end

  # pkg:gem/rack#lib/rack/request.rb:200
  def path_info=(s); end

  # pkg:gem/rack#lib/rack/request.rb:350
  def port; end

  # pkg:gem/rack#lib/rack/request.rb:243
  def post?; end

  # pkg:gem/rack#lib/rack/request.rb:246
  def put?; end

  # pkg:gem/rack#lib/rack/request.rb:562
  def query_parser=(_arg0); end

  # pkg:gem/rack#lib/rack/request.rb:203
  def query_string; end

  # pkg:gem/rack#lib/rack/request.rb:209
  def referer; end

  # pkg:gem/rack#lib/rack/request.rb:210
  def referrer; end

  # pkg:gem/rack#lib/rack/request.rb:202
  def request_method; end

  # pkg:gem/rack#lib/rack/request.rb:254
  def scheme; end

  # pkg:gem/rack#lib/rack/request.rb:196
  def script_name; end

  # pkg:gem/rack#lib/rack/request.rb:197
  def script_name=(s); end

  # pkg:gem/rack#lib/rack/request.rb:277
  def server_authority; end

  # pkg:gem/rack#lib/rack/request.rb:290
  def server_name; end

  # pkg:gem/rack#lib/rack/request.rb:294
  def server_port; end

  # pkg:gem/rack#lib/rack/request.rb:212
  def session; end

  # pkg:gem/rack#lib/rack/request.rb:218
  def session_options; end

  # pkg:gem/rack#lib/rack/request.rb:415
  def ssl?; end

  # pkg:gem/rack#lib/rack/request.rb:249
  def trace?; end

  # pkg:gem/rack#lib/rack/request.rb:619
  def trusted_proxy?(ip); end

  # pkg:gem/rack#lib/rack/request.rb:252
  def unlink?; end

  # pkg:gem/rack#lib/rack/request.rb:569
  def update_param(k, v); end

  # pkg:gem/rack#lib/rack/request.rb:599
  def url; end

  # pkg:gem/rack#lib/rack/request.rb:206
  def user_agent; end

  # pkg:gem/rack#lib/rack/request.rb:318
  def xhr?; end

  private

  # pkg:gem/rack#lib/rack/request.rb:770
  def allowed_scheme(header); end

  # pkg:gem/rack#lib/rack/request.rb:625
  def default_session; end

  # pkg:gem/rack#lib/rack/request.rb:682
  def expand_param_pairs(pairs, query_parser = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/request.rb:774
  def forwarded_priority; end

  # pkg:gem/rack#lib/rack/request.rb:746
  def forwarded_scheme; end

  # pkg:gem/rack#lib/rack/request.rb:665
  def get_http_forwarded(token); end

  # pkg:gem/rack#lib/rack/request.rb:641
  def parse_http_accept_header(header); end

  # pkg:gem/rack#lib/rack/request.rb:677
  def parse_multipart; end

  # pkg:gem/rack#lib/rack/request.rb:673
  def parse_query(qs, d = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/request.rb:669
  def query_parser; end

  # pkg:gem/rack#lib/rack/request.rb:735
  def split_authority(authority); end

  # pkg:gem/rack#lib/rack/request.rb:692
  def split_header(value); end

  # pkg:gem/rack#lib/rack/request.rb:628
  def wrap_ipv6(host); end

  # pkg:gem/rack#lib/rack/request.rb:778
  def x_forwarded_proto_priority; end
end

# pkg:gem/rack#lib/rack/request.rb:720
Rack::Request::Helpers::AUTHORITY = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/request.rb:173
Rack::Request::Helpers::DEFAULT_PORTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/request.rb:158
Rack::Request::Helpers::FORM_DATA_MEDIA_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/request.rb:741
Rack::Request::Helpers::FORWARDED_SCHEME_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/request.rb:181
Rack::Request::Helpers::HTTP_FORWARDED = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:176
Rack::Request::Helpers::HTTP_X_FORWARDED_FOR = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:179
Rack::Request::Helpers::HTTP_X_FORWARDED_HOST = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:190
Rack::Request::Helpers::HTTP_X_FORWARDED_PORT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:187
Rack::Request::Helpers::HTTP_X_FORWARDED_PROTO = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:184
Rack::Request::Helpers::HTTP_X_FORWARDED_SCHEME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:193
Rack::Request::Helpers::HTTP_X_FORWARDED_SSL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/request.rb:166
Rack::Request::Helpers::PARSEABLE_DATA_MEDIA_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/rack#lib/rack/response.rb:23
class Rack::Response
  include ::Rack::Response::Helpers

  # pkg:gem/rack#lib/rack/response.rb:54
  def initialize(body = T.unsafe(nil), status = T.unsafe(nil), headers = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/response.rb:177
  def [](key); end

  # pkg:gem/rack#lib/rack/response.rb:178
  def []=(key, value); end

  # pkg:gem/rack#lib/rack/response.rb:31
  def body; end

  # pkg:gem/rack#lib/rack/response.rb:31
  def body=(_arg0); end

  # pkg:gem/rack#lib/rack/response.rb:95
  def chunked?; end

  # pkg:gem/rack#lib/rack/response.rb:152
  def close; end

  # pkg:gem/rack#lib/rack/response.rb:172
  def delete_header(key); end

  # pkg:gem/rack#lib/rack/response.rb:130
  def each(&callback); end

  # pkg:gem/rack#lib/rack/response.rb:156
  def empty?; end

  # pkg:gem/rack#lib/rack/response.rb:107
  def finish(&block); end

  # pkg:gem/rack#lib/rack/response.rb:164
  def get_header(key); end

  # pkg:gem/rack#lib/rack/response.rb:160
  def has_header?(key); end

  # pkg:gem/rack#lib/rack/response.rb:32
  def headers; end

  # pkg:gem/rack#lib/rack/response.rb:31
  def length; end

  # pkg:gem/rack#lib/rack/response.rb:31
  def length=(_arg0); end

  # pkg:gem/rack#lib/rack/response.rb:99
  def no_entity_body?; end

  # pkg:gem/rack#lib/rack/response.rb:90
  def redirect(target, status = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/response.rb:168
  def set_header(key, value); end

  # pkg:gem/rack#lib/rack/response.rb:31
  def status; end

  # pkg:gem/rack#lib/rack/response.rb:31
  def status=(_arg0); end

  # pkg:gem/rack#lib/rack/response.rb:128
  def to_a(&block); end

  # pkg:gem/rack#lib/rack/response.rb:146
  def write(chunk); end

  class << self
    # pkg:gem/rack#lib/rack/response.rb:24
    def [](status, headers, body); end
  end
end

# pkg:gem/rack#lib/rack/response.rb:28
Rack::Response::CHUNKED = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/response.rb:180
module Rack::Response::Helpers
  # pkg:gem/rack#lib/rack/response.rb:191
  def accepted?; end

  # pkg:gem/rack#lib/rack/response.rb:219
  def add_header(key, value); end

  # pkg:gem/rack#lib/rack/response.rb:194
  def bad_request?; end

  # pkg:gem/rack#lib/rack/response.rb:307
  def cache!(duration = T.unsafe(nil), directive: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/response.rb:290
  def cache_control; end

  # pkg:gem/rack#lib/rack/response.rb:294
  def cache_control=(value); end

  # pkg:gem/rack#lib/rack/response.rb:186
  def client_error?; end

  # pkg:gem/rack#lib/rack/response.rb:257
  def content_length; end

  # pkg:gem/rack#lib/rack/response.rb:240
  def content_type; end

  # pkg:gem/rack#lib/rack/response.rb:245
  def content_type=(content_type); end

  # pkg:gem/rack#lib/rack/response.rb:190
  def created?; end

  # pkg:gem/rack#lib/rack/response.rb:274
  def delete_cookie(key, value = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/response.rb:299
  def do_not_cache!; end

  # pkg:gem/rack#lib/rack/response.rb:314
  def etag; end

  # pkg:gem/rack#lib/rack/response.rb:318
  def etag=(value); end

  # pkg:gem/rack#lib/rack/response.rb:196
  def forbidden?; end

  # pkg:gem/rack#lib/rack/response.rb:206
  def include?(header); end

  # pkg:gem/rack#lib/rack/response.rb:183
  def informational?; end

  # pkg:gem/rack#lib/rack/response.rb:181
  def invalid?; end

  # pkg:gem/rack#lib/rack/response.rb:262
  def location; end

  # pkg:gem/rack#lib/rack/response.rb:266
  def location=(location); end

  # pkg:gem/rack#lib/rack/response.rb:249
  def media_type; end

  # pkg:gem/rack#lib/rack/response.rb:253
  def media_type_params; end

  # pkg:gem/rack#lib/rack/response.rb:198
  def method_not_allowed?; end

  # pkg:gem/rack#lib/rack/response.rb:193
  def moved_permanently?; end

  # pkg:gem/rack#lib/rack/response.rb:192
  def no_content?; end

  # pkg:gem/rack#lib/rack/response.rb:199
  def not_acceptable?; end

  # pkg:gem/rack#lib/rack/response.rb:197
  def not_found?; end

  # pkg:gem/rack#lib/rack/response.rb:189
  def ok?; end

  # pkg:gem/rack#lib/rack/response.rb:201
  def precondition_failed?; end

  # pkg:gem/rack#lib/rack/response.rb:204
  def redirect?; end

  # pkg:gem/rack#lib/rack/response.rb:185
  def redirection?; end

  # pkg:gem/rack#lib/rack/response.rb:200
  def request_timeout?; end

  # pkg:gem/rack#lib/rack/response.rb:187
  def server_error?; end

  # pkg:gem/rack#lib/rack/response.rb:270
  def set_cookie(key, value); end

  # pkg:gem/rack#lib/rack/response.rb:282
  def set_cookie_header; end

  # pkg:gem/rack#lib/rack/response.rb:286
  def set_cookie_header=(value); end

  # pkg:gem/rack#lib/rack/response.rb:184
  def successful?; end

  # pkg:gem/rack#lib/rack/response.rb:195
  def unauthorized?; end

  # pkg:gem/rack#lib/rack/response.rb:202
  def unprocessable?; end

  protected

  # pkg:gem/rack#lib/rack/response.rb:359
  def append(chunk); end

  # pkg:gem/rack#lib/rack/response.rb:332
  def buffered_body!; end
end

# pkg:gem/rack#lib/rack/response.rb:375
class Rack::Response::Raw
  include ::Rack::Response::Helpers

  # pkg:gem/rack#lib/rack/response.rb:381
  def initialize(status, headers); end

  # pkg:gem/rack#lib/rack/response.rb:398
  def delete_header(key); end

  # pkg:gem/rack#lib/rack/response.rb:390
  def get_header(key); end

  # pkg:gem/rack#lib/rack/response.rb:386
  def has_header?(key); end

  # pkg:gem/rack#lib/rack/response.rb:378
  def headers; end

  # pkg:gem/rack#lib/rack/response.rb:394
  def set_header(key, value); end

  # pkg:gem/rack#lib/rack/response.rb:379
  def status; end

  # pkg:gem/rack#lib/rack/response.rb:379
  def status=(_arg0); end
end

# pkg:gem/rack#lib/rack/response.rb:29
Rack::Response::STATUS_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/rewindable_input.rb:14
class Rack::RewindableInput
  # pkg:gem/rack#lib/rack/rewindable_input.rb:32
  def initialize(io); end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:68
  def close; end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:48
  def each(&block); end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:38
  def gets; end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:43
  def read(*args); end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:53
  def rewind; end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:58
  def size; end

  private

  # pkg:gem/rack#lib/rack/rewindable_input.rb:112
  def filesystem_has_posix_semantics?; end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:81
  def make_rewindable; end
end

# pkg:gem/rack#lib/rack/rewindable_input.rb:18
class Rack::RewindableInput::Middleware
  # pkg:gem/rack#lib/rack/rewindable_input.rb:19
  def initialize(app); end

  # pkg:gem/rack#lib/rack/rewindable_input.rb:23
  def call(env); end
end

# pkg:gem/rack#lib/rack/runtime.rb:12
class Rack::Runtime
  # pkg:gem/rack#lib/rack/runtime.rb:16
  def initialize(app, name = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/runtime.rb:22
  def call(env); end
end

# pkg:gem/rack#lib/rack/runtime.rb:13
Rack::Runtime::FORMAT_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/runtime.rb:14
Rack::Runtime::HEADER_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:11
Rack::SCRIPT_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:14
Rack::SERVER_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:15
Rack::SERVER_PORT = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:13
Rack::SERVER_PROTOCOL = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:24
Rack::SET_COOKIE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/sendfile.rb:121
class Rack::Sendfile
  # pkg:gem/rack#lib/rack/sendfile.rb:122
  def initialize(app, variation = T.unsafe(nil), mappings = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/sendfile.rb:130
  def call(env); end

  private

  # pkg:gem/rack#lib/rack/sendfile.rb:182
  def map_accel_path(env, path); end

  # pkg:gem/rack#lib/rack/sendfile.rb:166
  def variation(env); end

  # pkg:gem/rack#lib/rack/sendfile.rb:172
  def x_accel_mapping(env); end
end

# pkg:gem/rack#lib/rack/show_exceptions.rb:18
class Rack::ShowExceptions
  # pkg:gem/rack#lib/rack/show_exceptions.rb:26
  def initialize(app); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:30
  def call(env); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:65
  def dump_exception(exception); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:120
  def h(obj); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:56
  def prefers_plaintext?(env); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:80
  def pretty(env, exception); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:116
  def template; end

  private

  # pkg:gem/rack#lib/rack/show_exceptions.rb:60
  def accepts_html?(env); end
end

# pkg:gem/rack#lib/rack/show_exceptions.rb:19
Rack::ShowExceptions::CONTEXT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rack#lib/rack/show_exceptions.rb:21
class Rack::ShowExceptions::Frame < ::Struct
  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def context_line; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def context_line=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def filename; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def filename=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def function; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def function=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def lineno; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def lineno=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def post_context; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def post_context=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def post_context_lineno; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def post_context_lineno=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def pre_context; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def pre_context=(_); end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def pre_context_lineno; end

  # pkg:gem/rack#lib/rack/show_exceptions.rb:21
  def pre_context_lineno=(_); end

  class << self
    # pkg:gem/rack#lib/rack/show_exceptions.rb:21
    def [](*_arg0); end

    # pkg:gem/rack#lib/rack/show_exceptions.rb:21
    def inspect; end

    # pkg:gem/rack#lib/rack/show_exceptions.rb:21
    def keyword_init?; end

    # pkg:gem/rack#lib/rack/show_exceptions.rb:21
    def members; end

    # pkg:gem/rack#lib/rack/show_exceptions.rb:21
    def new(*_arg0); end
  end
end

# pkg:gem/rack#lib/rack/show_exceptions.rb:135
Rack::ShowExceptions::TEMPLATE = T.let(T.unsafe(nil), ERB)

# pkg:gem/rack#lib/rack/show_status.rb:18
class Rack::ShowStatus
  # pkg:gem/rack#lib/rack/show_status.rb:19
  def initialize(app); end

  # pkg:gem/rack#lib/rack/show_status.rb:24
  def call(env); end

  # pkg:gem/rack#lib/rack/show_status.rb:54
  def h(obj); end
end

# pkg:gem/rack#lib/rack/show_status.rb:69
Rack::ShowStatus::TEMPLATE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/static.rb:92
class Rack::Static
  # pkg:gem/rack#lib/rack/static.rb:93
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/static.rb:112
  def add_index_root?(path); end

  # pkg:gem/rack#lib/rack/static.rb:170
  def applicable_rules(path); end

  # pkg:gem/rack#lib/rack/static.rb:128
  def call(env); end

  # pkg:gem/rack#lib/rack/static.rb:124
  def can_serve(path); end

  # pkg:gem/rack#lib/rack/static.rb:116
  def overwrite_file_path(path); end

  # pkg:gem/rack#lib/rack/static.rb:120
  def route_file(path); end
end

# pkg:gem/rack#lib/rack/constants.rb:38
Rack::TRACE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/constants.rb:25
Rack::TRANSFER_ENCODING = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/tempfile_reaper.rb:11
class Rack::TempfileReaper
  # pkg:gem/rack#lib/rack/tempfile_reaper.rb:12
  def initialize(app); end

  # pkg:gem/rack#lib/rack/tempfile_reaper.rb:16
  def call(env); end
end

# pkg:gem/rack#lib/rack/constants.rb:37
Rack::UNLINK = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/urlmap.rb:20
class Rack::URLMap
  # pkg:gem/rack#lib/rack/urlmap.rb:21
  def initialize(map = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/urlmap.rb:48
  def call(env); end

  # pkg:gem/rack#lib/rack/urlmap.rb:25
  def remap(map); end

  private

  # pkg:gem/rack#lib/rack/urlmap.rb:87
  def casecmp?(v1, v2); end
end

# pkg:gem/rack#lib/rack/utils.rb:20
module Rack::Utils
  private

  # pkg:gem/rack#lib/rack/utils.rb:227
  def best_q_match(q_value_header, available_mimes); end

  # pkg:gem/rack#lib/rack/utils.rb:120
  def build_nested_query(value, prefix = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:110
  def build_query(params); end

  # pkg:gem/rack#lib/rack/utils.rb:492
  def byte_ranges(env, size, max_ranges: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:692
  def clean_path_info(path_info); end

  # pkg:gem/rack#lib/rack/utils.rb:91
  def clock_time; end

  # pkg:gem/rack#lib/rack/utils.rb:450
  def delete_cookie_header!(headers, key, value = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:446
  def delete_set_cookie_header(key, value = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:474
  def delete_set_cookie_header!(header, key, value = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:40
  def escape(s); end

  # pkg:gem/rack#lib/rack/utils.rb:243
  def escape_html(_arg0); end

  # pkg:gem/rack#lib/rack/utils.rb:46
  def escape_path(s); end

  # pkg:gem/rack#lib/rack/utils.rb:152
  def forwarded_values(forwarded_header); end

  # pkg:gem/rack#lib/rack/utils.rb:496
  def get_byte_ranges(http_range, size, max_ranges: T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:347
  def parse_cookies(env); end

  # pkg:gem/rack#lib/rack/utils.rb:328
  def parse_cookies_header(value); end

  # pkg:gem/rack#lib/rack/utils.rb:106
  def parse_nested_query(qs, d = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:102
  def parse_query(qs, d = T.unsafe(nil), &unescaper); end

  # pkg:gem/rack#lib/rack/utils.rb:138
  def q_values(q_value_header); end

  # pkg:gem/rack#lib/rack/utils.rb:485
  def rfc2822(time); end

  # pkg:gem/rack#lib/rack/utils.rb:540
  def secure_compare(a, b); end

  # pkg:gem/rack#lib/rack/utils.rb:274
  def select_best_encoding(available_encodings, accept_encoding); end

  # pkg:gem/rack#lib/rack/utils.rb:376
  def set_cookie_header(key, value); end

  # pkg:gem/rack#lib/rack/utils.rb:420
  def set_cookie_header!(headers, key, value); end

  # pkg:gem/rack#lib/rack/utils.rb:674
  def status_code(status); end

  # pkg:gem/rack#lib/rack/utils.rb:58
  def unescape(s, encoding = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:52
  def unescape_path(s); end

  # pkg:gem/rack#lib/rack/utils.rb:709
  def valid_path?(path); end

  class << self
    # pkg:gem/rack#lib/rack/utils.rb:227
    def best_q_match(q_value_header, available_mimes); end

    # pkg:gem/rack#lib/rack/utils.rb:120
    def build_nested_query(value, prefix = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:110
    def build_query(params); end

    # pkg:gem/rack#lib/rack/utils.rb:492
    def byte_ranges(env, size, max_ranges: T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:692
    def clean_path_info(path_info); end

    # pkg:gem/rack#lib/rack/utils.rb:91
    def clock_time; end

    # pkg:gem/rack#lib/rack/utils.rb:30
    def default_query_parser; end

    # pkg:gem/rack#lib/rack/utils.rb:30
    def default_query_parser=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:450
    def delete_cookie_header!(headers, key, value = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:446
    def delete_set_cookie_header(key, value = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:474
    def delete_set_cookie_header!(header, key, value = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:40
    def escape(s); end

    # pkg:gem/rack#lib/rack/utils.rb:243
    def escape_html(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:46
    def escape_path(s); end

    # pkg:gem/rack#lib/rack/utils.rb:152
    def forwarded_values(forwarded_header); end

    # pkg:gem/rack#lib/rack/utils.rb:496
    def get_byte_ranges(http_range, size, max_ranges: T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:65
    def multipart_file_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:65
    def multipart_file_limit=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:69
    def multipart_part_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:70
    def multipart_part_limit=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:63
    def multipart_total_part_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:63
    def multipart_total_part_limit=(_arg0); end

    # pkg:gem/rack#lib/rack/utils.rb:82
    def param_depth_limit; end

    # pkg:gem/rack#lib/rack/utils.rb:86
    def param_depth_limit=(v); end

    # pkg:gem/rack#lib/rack/utils.rb:347
    def parse_cookies(env); end

    # pkg:gem/rack#lib/rack/utils.rb:328
    def parse_cookies_header(value); end

    # pkg:gem/rack#lib/rack/utils.rb:106
    def parse_nested_query(qs, d = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:102
    def parse_query(qs, d = T.unsafe(nil), &unescaper); end

    # pkg:gem/rack#lib/rack/utils.rb:138
    def q_values(q_value_header); end

    # pkg:gem/rack#lib/rack/utils.rb:485
    def rfc2822(time); end

    # pkg:gem/rack#lib/rack/utils.rb:540
    def secure_compare(a, b); end

    # pkg:gem/rack#lib/rack/utils.rb:274
    def select_best_encoding(available_encodings, accept_encoding); end

    # pkg:gem/rack#lib/rack/utils.rb:376
    def set_cookie_header(key, value); end

    # pkg:gem/rack#lib/rack/utils.rb:420
    def set_cookie_header!(headers, key, value); end

    # pkg:gem/rack#lib/rack/utils.rb:674
    def status_code(status); end

    # pkg:gem/rack#lib/rack/utils.rb:58
    def unescape(s, encoding = T.unsafe(nil)); end

    # pkg:gem/rack#lib/rack/utils.rb:52
    def unescape_path(s); end

    # pkg:gem/rack#lib/rack/utils.rb:709
    def valid_path?(path); end
  end
end

# pkg:gem/rack#lib/rack/utils.rb:149
Rack::Utils::ALLOWED_FORWARDED_PARAMS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:25
Rack::Utils::COMMON_SEP = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:563
class Rack::Utils::Context
  # pkg:gem/rack#lib/rack/utils.rb:566
  def initialize(app_f, app_r); end

  # pkg:gem/rack#lib/rack/utils.rb:564
  def app; end

  # pkg:gem/rack#lib/rack/utils.rb:571
  def call(env); end

  # pkg:gem/rack#lib/rack/utils.rb:579
  def context(env, app = T.unsafe(nil)); end

  # pkg:gem/rack#lib/rack/utils.rb:564
  def for; end

  # pkg:gem/rack#lib/rack/utils.rb:575
  def recontext(app); end
end

# pkg:gem/rack#lib/rack/utils.rb:24
Rack::Utils::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/utils.rb:590
Rack::Utils::HTTP_STATUS_CODES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:22
Rack::Utils::InvalidParameterError = Rack::QueryParser::InvalidParameterError

# pkg:gem/rack#lib/rack/utils.rb:26
Rack::Utils::KeySpaceConstrainedParams = Rack::QueryParser::Params

# pkg:gem/rack#lib/rack/utils.rb:707
Rack::Utils::NULL_BYTE = T.let(T.unsafe(nil), String)

# pkg:gem/rack#lib/rack/utils.rb:660
Rack::Utils::OBSOLETE_SYMBOLS_TO_STATUS_CODES = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:668
Rack::Utils::OBSOLETE_SYMBOL_MAPPINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:690
Rack::Utils::PATH_SEPS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/utils.rb:21
Rack::Utils::ParameterTypeError = Rack::QueryParser::ParameterTypeError

# pkg:gem/rack#lib/rack/utils.rb:23
Rack::Utils::ParamsTooDeepError = Rack::QueryParser::QueryLimitError

# pkg:gem/rack#lib/rack/utils.rb:654
Rack::Utils::STATUS_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:656
Rack::Utils::SYMBOL_TO_STATUS_CODE = T.let(T.unsafe(nil), Hash)

# pkg:gem/rack#lib/rack/utils.rb:27
Rack::Utils::URI_PARSER = T.let(T.unsafe(nil), URI::RFC2396_Parser)

# pkg:gem/rack#lib/rack/utils.rb:353
Rack::Utils::VALID_COOKIE_KEY = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rack#lib/rack/version.rb:9
Rack::VERSION = T.let(T.unsafe(nil), String)
