# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `require-hooks` gem.
# Please instead update this file by running `bin/tapioca gem require-hooks`.


# pkg:gem/require-hooks#lib/require-hooks/api.rb:3
module RequireHooks
  class << self
    # pkg:gem/require-hooks#lib/require-hooks/api.rb:103
    def around_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:139
    def context_for(path); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:168
    def contexts; end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:135
    def hijack_load(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:93
    def print_warnings; end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:93
    def print_warnings=(_arg0); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:160
    def setup_path_coverage(path, contents = T.unsafe(nil)); end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:117
    def source_transform(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil), &block); end

    private

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:184
    def eval_coverage_enabled?; end

    # pkg:gem/require-hooks#lib/require-hooks/api.rb:174
    def register_hook(type, block, patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil)); end
  end
end

# pkg:gem/require-hooks#lib/require-hooks/api.rb:4
class RequireHooks::Context
  # pkg:gem/require-hooks#lib/require-hooks/api.rb:8
  def initialize(patterns: T.unsafe(nil), exclude_patterns: T.unsafe(nil)); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def around_load; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:30
  def empty?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def exclude_patterns; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:45
  def hijack?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def hijack_load; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:24
  def match?(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:81
  def merge!(another_ctx); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def patterns; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:59
  def perform_source_transform(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:35
  def readonly?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:49
  def run_around_load_callbacks(path); end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:5
  def source_transform; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:41
  def source_transform?; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:20
  def to_key; end

  # pkg:gem/require-hooks#lib/require-hooks/api.rb:71
  def try_hijack_load(path, source); end
end

# pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:6
RequireHooks::EMPTY_ISEQ = T.let(T.unsafe(nil), RubyVM::InstructionSequence)

# pkg:gem/require-hooks#lib/require-hooks/iseq.rb:4
module RequireHooks::Iseq
  class << self
    # pkg:gem/require-hooks#lib/require-hooks/iseq.rb:6
    def compile_with_coverage(ctx, path); end
  end
end

# pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:8
module RequireHooks::LoadIseq
  # pkg:gem/require-hooks#lib/require-hooks/mode/load_iseq.rb:9
  def load_iseq(path); end
end

class RubyVM::InstructionSequence
  extend ::RequireHooks::LoadIseq
  extend ::Bootsnap::CompileCache::ISeq::InstructionSequenceMixin
end
