# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rqrcode` gem.
# Please instead update this file by running `bin/tapioca gem rqrcode`.


# pkg:gem/rqrcode#lib/rqrcode.rb:3
module RQRCode; end

# pkg:gem/rqrcode#lib/rqrcode/export/ansi.rb:4
module RQRCode::Export; end

# pkg:gem/rqrcode#lib/rqrcode/export/ansi.rb:5
module RQRCode::Export::ANSI
  # pkg:gem/rqrcode#lib/rqrcode/export/ansi.rb:16
  def as_ansi(options = T.unsafe(nil)); end
end

# pkg:gem/rqrcode#lib/rqrcode/export/html.rb:5
module RQRCode::Export::HTML
  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:8
  def as_html; end

  private

  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:14
  def rows; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/html.rb:38
class RQRCode::Export::HTML::Cell < ::Struct
  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:39
  def as_html; end

  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:43
  def html_class; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/html.rb:28
class RQRCode::Export::HTML::Row < ::Struct
  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:29
  def as_html; end

  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:33
  def cells; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/html.rb:18
class RQRCode::Export::HTML::Rows < ::Struct
  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:19
  def as_html; end

  # pkg:gem/rqrcode#lib/rqrcode/export/html.rb:23
  def rows; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/png.rb:8
module RQRCode::Export::PNG
  # pkg:gem/rqrcode#lib/rqrcode/export/png.rb:48
  def as_png(options = T.unsafe(nil)); end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:7
module RQRCode::Export::SVG
  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:164
  def as_svg(options = T.unsafe(nil)); end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:8
class RQRCode::Export::SVG::BaseOutputSVG
  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:11
  def initialize(qrcode); end

  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:9
  def result; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:124
RQRCode::Export::SVG::DEFAULT_SVG_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:106
class RQRCode::Export::SVG::Edge < ::Struct
  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:107
  def end_x; end

  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:115
  def end_y; end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:17
class RQRCode::Export::SVG::Path < ::RQRCode::Export::SVG::BaseOutputSVG
  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:18
  def build(module_size, offset, color); end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:86
class RQRCode::Export::SVG::Rect < ::RQRCode::Export::SVG::BaseOutputSVG
  # pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:87
  def build(module_size, offset, color); end
end

# pkg:gem/rqrcode#lib/rqrcode/export/svg.rb:131
RQRCode::Export::SVG::SVG_PATH_COMMANDS = T.let(T.unsafe(nil), Hash)

# pkg:gem/rqrcode#lib/rqrcode/qrcode/qrcode.rb:6
class RQRCode::QRCode
  include ::RQRCode::Export::ANSI
  include ::RQRCode::Export::HTML
  include ::RQRCode::Export::PNG
  include ::RQRCode::Export::SVG
  extend ::Forwardable

  # pkg:gem/rqrcode#lib/rqrcode/qrcode/qrcode.rb:13
  def initialize(string, *args); end

  # pkg:gem/rqrcode#lib/rqrcode/qrcode/qrcode.rb:9
  def modules(*args, **_arg1, &block); end

  # pkg:gem/rqrcode#lib/rqrcode/qrcode/qrcode.rb:11
  def qrcode; end

  # pkg:gem/rqrcode#lib/rqrcode/qrcode/qrcode.rb:8
  def to_s(*args, **_arg1, &block); end
end

# pkg:gem/rqrcode#lib/rqrcode/version.rb:4
RQRCode::VERSION = T.let(T.unsafe(nil), String)
