# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `thor` gem.
# Please instead update this file by running `bin/tapioca gem thor`.


# pkg:gem/thor#lib/thor/shell/lcs_diff.rb:1
module LCSDiff
  protected

  # pkg:gem/thor#lib/thor/shell/lcs_diff.rb:6
  def show_diff(destination, content); end

  private

  # pkg:gem/thor#lib/thor/shell/lcs_diff.rb:37
  def diff_lcs_loaded?; end

  # pkg:gem/thor#lib/thor/shell/lcs_diff.rb:21
  def output_diff_line(diff); end
end

# pkg:gem/thor#lib/thor/command.rb:1
class Thor
  include ::Thor::Base
  include ::Thor::Invocation
  include ::Thor::Shell
  extend ::Thor::Base::ClassMethods
  extend ::Thor::Invocation::ClassMethods

  # pkg:gem/thor#lib/thor.rb:663
  def help(command = T.unsafe(nil), subcommand = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor.rb:678
  def tree; end

  private

  # pkg:gem/thor#lib/thor.rb:684
  def build_command_tree(klass, indent); end

  class << self
    # pkg:gem/thor#lib/thor.rb:250
    def at_least_one(*args, &block); end

    # pkg:gem/thor#lib/thor.rb:350
    def check_unknown_options!(options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:363
    def check_unknown_options?(config); end

    # pkg:gem/thor#lib/thor.rb:449
    def command_exists?(command_name); end

    # pkg:gem/thor#lib/thor.rb:258
    def command_help(shell, command_name); end

    # pkg:gem/thor#lib/thor.rb:21
    def default_command(meth = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:28
    def default_task(meth = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/base.rb:27
    def deprecation_warning(message); end

    # pkg:gem/thor#lib/thor.rb:54
    def desc(usage, description, options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:434
    def disable_required_check!(*command_names); end

    # pkg:gem/thor#lib/thor.rb:438
    def disable_required_check?(command); end

    # pkg:gem/thor#lib/thor.rb:207
    def exclusive(*args, &block); end

    # pkg:gem/thor#lib/thor.rb:288
    def help(shell, subcommand = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:78
    def long_desc(long_description, options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:101
    def map(mappings = T.unsafe(nil), **kw); end

    # pkg:gem/thor#lib/thor.rb:246
    def method_at_least_one(*args, &block); end

    # pkg:gem/thor#lib/thor.rb:203
    def method_exclusive(*args, &block); end

    # pkg:gem/thor#lib/thor.rb:163
    def method_option(name, options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:129
    def method_options(options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:175
    def option(name, options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:135
    def options(options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:12
    def package_name(name, _ = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:309
    def printable_commands(all = T.unsafe(nil), subcommand = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:318
    def printable_tasks(all = T.unsafe(nil), subcommand = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:37
    def register(klass, subcommand_name, usage, description, options = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:420
    def stop_on_unknown_option!(*command_names); end

    # pkg:gem/thor#lib/thor.rb:424
    def stop_on_unknown_option?(command); end

    # pkg:gem/thor#lib/thor.rb:329
    def subcommand(subcommand, subcommand_class); end

    # pkg:gem/thor#lib/thor.rb:325
    def subcommand_classes; end

    # pkg:gem/thor#lib/thor.rb:320
    def subcommands; end

    # pkg:gem/thor#lib/thor.rb:344
    def subtask(subcommand, subcommand_class); end

    # pkg:gem/thor#lib/thor.rb:323
    def subtasks; end

    # pkg:gem/thor#lib/thor.rb:281
    def task_help(shell, command_name); end

    protected

    # pkg:gem/thor#lib/thor.rb:546
    def banner(command, namespace = T.unsafe(nil), subcommand = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:552
    def baseclass; end

    # pkg:gem/thor#lib/thor.rb:560
    def create_command(meth); end

    # pkg:gem/thor#lib/thor.rb:584
    def create_task(meth); end

    # pkg:gem/thor#lib/thor.rb:478
    def disable_required_check; end

    # pkg:gem/thor#lib/thor.rb:505
    def dispatch(meth, given_args, given_opts, config); end

    # pkg:gem/thor#lib/thor.rb:556
    def dynamic_command_class; end

    # pkg:gem/thor#lib/thor.rb:626
    def find_command_possibilities(meth); end

    # pkg:gem/thor#lib/thor.rb:639
    def find_task_possibilities(meth); end

    # pkg:gem/thor#lib/thor.rb:586
    def initialize_added; end

    # pkg:gem/thor#lib/thor.rb:469
    def method_at_least_one_option_names; end

    # pkg:gem/thor#lib/thor.rb:460
    def method_exclusive_option_names; end

    # pkg:gem/thor#lib/thor.rb:605
    def normalize_command_name(meth); end

    # pkg:gem/thor#lib/thor.rb:621
    def normalize_task_name(meth); end

    # pkg:gem/thor#lib/thor.rb:493
    def print_at_least_one_required_options(shell, command = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:482
    def print_exclusive_options(shell, command = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor.rb:592
    def retrieve_command_name(args); end

    # pkg:gem/thor#lib/thor.rb:596
    def retrieve_task_name(args); end

    # pkg:gem/thor#lib/thor.rb:653
    def sort_commands!(list); end

    # pkg:gem/thor#lib/thor.rb:473
    def stop_on_unknown_option; end

    # pkg:gem/thor#lib/thor.rb:641
    def subcommand_help(cmd); end

    # pkg:gem/thor#lib/thor.rb:647
    def subtask_help(cmd); end
  end
end

# pkg:gem/thor#lib/thor/actions/empty_directory.rb:2
module Thor::Actions
  mixes_in_class_methods ::Thor::Actions::ClassMethods

  # pkg:gem/thor#lib/thor/actions.rb:72
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil), config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:89
  def action(instance); end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:27
  def add_file(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/create_link.rb:22
  def add_link(destination, *args); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:197
  def append_file(path, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:192
  def append_to_file(path, *args, &block); end

  # pkg:gem/thor#lib/thor/actions.rb:216
  def apply(path, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:10
  def behavior; end

  # pkg:gem/thor#lib/thor/actions.rb:10
  def behavior=(_arg0); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:145
  def chmod(path, mode, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:333
  def comment_lines(path, flag, *args); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:20
  def copy_file(source, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:22
  def create_file(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/create_link.rb:17
  def create_link(destination, *args); end

  # pkg:gem/thor#lib/thor/actions.rb:99
  def destination_root; end

  # pkg:gem/thor#lib/thor/actions.rb:106
  def destination_root=(root); end

  # pkg:gem/thor#lib/thor/actions/directory.rb:49
  def directory(source, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:13
  def empty_directory(destination, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:133
  def find_in_source_paths(file); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:81
  def get(source, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:291
  def gsub_file(path, flag, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:263
  def gsub_file!(path, flag, *args, &block); end

  # pkg:gem/thor#lib/thor/actions.rb:200
  def in_root; end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:216
  def inject_into_class(path, klass, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:64
  def inject_into_file(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:35
  def inject_into_file!(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:239
  def inject_into_module(path, module_name, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:56
  def insert_into_file(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:26
  def insert_into_file!(destination, *args, &block); end

  # pkg:gem/thor#lib/thor/actions.rb:170
  def inside(dir = T.unsafe(nil), config = T.unsafe(nil), &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:50
  def link_file(source, *args); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:175
  def prepend_file(path, *args, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:170
  def prepend_to_file(path, *args, &block); end

  # pkg:gem/thor#lib/thor/actions.rb:114
  def relative_to_original_destination_root(path, remove_dot = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:360
  def remove_dir(path, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:350
  def remove_file(path, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:248
  def run(command, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:285
  def run_ruby_script(command, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions.rb:127
  def source_paths; end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:117
  def template(source, *args, &block); end

  # pkg:gem/thor#lib/thor/actions.rb:308
  def thor(command, *args); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:314
  def uncomment_lines(path, flag, *args); end

  protected

  # pkg:gem/thor#lib/thor/actions.rb:329
  def _cleanup_options_and_set(options, key); end

  # pkg:gem/thor#lib/thor/actions.rb:325
  def _shared_configuration; end

  private

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:385
  def actually_gsub_file(path, flag, args, error_on_no_change, &block); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:371
  def capture(*args); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:367
  def concat(string); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:362
  def output_buffer; end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:362
  def output_buffer=(_arg0); end

  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:375
  def with_output_buffer(buf = T.unsafe(nil)); end

  class << self
    # pkg:gem/thor#lib/thor/actions.rb:12
    def included(base); end
  end
end

# pkg:gem/thor#lib/thor/actions/file_manipulation.rb:398
class Thor::Actions::CapturableERB < ::ERB
  # pkg:gem/thor#lib/thor/actions/file_manipulation.rb:399
  def set_eoutvar(compiler, eoutvar = T.unsafe(nil)); end
end

# pkg:gem/thor#lib/thor/actions.rb:17
module Thor::Actions::ClassMethods
  # pkg:gem/thor#lib/thor/actions.rb:48
  def add_runtime_options!; end

  # pkg:gem/thor#lib/thor/actions.rb:22
  def source_paths; end

  # pkg:gem/thor#lib/thor/actions.rb:38
  def source_paths_for_search; end

  # pkg:gem/thor#lib/thor/actions.rb:27
  def source_root(path = T.unsafe(nil)); end
end

# pkg:gem/thor#lib/thor/actions/create_file.rb:32
class Thor::Actions::CreateFile < ::Thor::Actions::EmptyDirectory
  # pkg:gem/thor#lib/thor/actions/create_file.rb:35
  def initialize(base, destination, data, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:33
  def data; end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:45
  def identical?; end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:60
  def invoke!; end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:52
  def render; end

  protected

  # pkg:gem/thor#lib/thor/actions/create_file.rb:100
  def force_on_collision?; end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:86
  def force_or_skip_or_conflict(force, skip, &block); end

  # pkg:gem/thor#lib/thor/actions/create_file.rb:73
  def on_conflict_behavior(&block); end
end

# pkg:gem/thor#lib/thor/actions/create_link.rb:27
class Thor::Actions::CreateLink < ::Thor::Actions::CreateFile
  # pkg:gem/thor#lib/thor/actions/create_link.rb:28
  def data; end

  # pkg:gem/thor#lib/thor/actions/create_link.rb:56
  def exists?; end

  # pkg:gem/thor#lib/thor/actions/create_link.rb:35
  def identical?; end

  # pkg:gem/thor#lib/thor/actions/create_link.rb:40
  def invoke!; end
end

# pkg:gem/thor#lib/thor/actions/directory.rb:55
class Thor::Actions::Directory < ::Thor::Actions::EmptyDirectory
  # pkg:gem/thor#lib/thor/actions/directory.rb:58
  def initialize(base, source, destination = T.unsafe(nil), config = T.unsafe(nil), &block); end

  # pkg:gem/thor#lib/thor/actions/directory.rb:64
  def invoke!; end

  # pkg:gem/thor#lib/thor/actions/directory.rb:69
  def revoke!; end

  # pkg:gem/thor#lib/thor/actions/directory.rb:56
  def source; end

  protected

  # pkg:gem/thor#lib/thor/actions/directory.rb:75
  def execute!; end

  # pkg:gem/thor#lib/thor/actions/directory.rb:99
  def file_level_lookup(previous_lookup); end

  # pkg:gem/thor#lib/thor/actions/directory.rb:103
  def files(lookup); end
end

# pkg:gem/thor#lib/thor/actions/empty_directory.rb:23
class Thor::Actions::EmptyDirectory
  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:34
  def initialize(base, destination, config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:24
  def base; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:24
  def config; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:24
  def destination; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:45
  def exists?; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:24
  def given_destination; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:49
  def invoke!; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:24
  def relative_destination; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:56
  def revoke!; end

  protected

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:103
  def convert_encoded_instructions(filename); end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:85
  def destination=(destination); end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:113
  def invoke_with_conflict_check(&block); end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:132
  def on_conflict_behavior; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:126
  def on_file_clash_behavior; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:67
  def pretend?; end

  # pkg:gem/thor#lib/thor/actions/empty_directory.rb:138
  def say_status(status, color); end
end

# pkg:gem/thor#lib/thor/actions/inject_into_file.rb:66
class Thor::Actions::InjectIntoFile < ::Thor::Actions::EmptyDirectory
  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:69
  def initialize(base, destination, data, config); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:67
  def behavior; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:67
  def flag; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:83
  def invoke!; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:67
  def replacement; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:107
  def revoke!; end

  protected

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:143
  def content; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:153
  def replace!(regexp, string, force); end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:147
  def replacement_present?; end

  # pkg:gem/thor#lib/thor/actions/inject_into_file.rb:123
  def say_status(behavior, warning: T.unsafe(nil), color: T.unsafe(nil)); end
end

# pkg:gem/thor#lib/thor/actions/inject_into_file.rb:5
Thor::Actions::WARNINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/thor#lib/thor/error.rb:57
class Thor::AmbiguousCommandError < ::Thor::Error; end

# pkg:gem/thor#lib/thor/error.rb:59
Thor::AmbiguousTaskError = Thor::AmbiguousCommandError

# pkg:gem/thor#lib/thor/parser/argument.rb:2
class Thor::Argument
  # pkg:gem/thor#lib/thor/parser/argument.rb:8
  def initialize(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def banner; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def default; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def description; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def enum; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:52
  def enum_to_s; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:6
  def human_name; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def name; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:27
  def print_default; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def required; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:39
  def required?; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:43
  def show_default?; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:5
  def type; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:35
  def usage; end

  protected

  # pkg:gem/thor#lib/thor/parser/argument.rb:71
  def default_banner; end

  # pkg:gem/thor#lib/thor/parser/argument.rb:67
  def valid_type?(type); end

  # pkg:gem/thor#lib/thor/parser/argument.rb:62
  def validate!; end
end

# pkg:gem/thor#lib/thor/parser/argument.rb:3
Thor::Argument::VALID_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/parser/arguments.rb:2
class Thor::Arguments
  # pkg:gem/thor#lib/thor/parser/arguments.rb:26
  def initialize(arguments = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:40
  def parse(args); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:53
  def remaining; end

  private

  # pkg:gem/thor#lib/thor/parser/arguments.rb:186
  def check_requirement!; end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:84
  def current_is_value?; end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:64
  def last?; end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:59
  def no_or_skip?(arg); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:118
  def parse_array(name); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:97
  def parse_hash(name); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:139
  def parse_numeric(name); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:158
  def parse_string(name); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:68
  def peek; end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:72
  def shift; end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:76
  def unshift(arg); end

  # pkg:gem/thor#lib/thor/parser/arguments.rb:172
  def validate_enum_value!(name, value, message); end

  class << self
    # pkg:gem/thor#lib/thor/parser/arguments.rb:19
    def parse(*args); end

    # pkg:gem/thor#lib/thor/parser/arguments.rb:8
    def split(args); end
  end
end

# pkg:gem/thor#lib/thor/parser/arguments.rb:3
Thor::Arguments::NUMERIC = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/error.rb:104
class Thor::AtLeastOneRequiredArgumentError < ::Thor::InvocationError; end

# pkg:gem/thor#lib/thor/shell.rb:4
module Thor::Base
  include ::Thor::Invocation
  include ::Thor::Shell

  mixes_in_class_methods ::Thor::Base::ClassMethods
  mixes_in_class_methods ::Thor::Invocation::ClassMethods

  # pkg:gem/thor#lib/thor/base.rb:54
  def initialize(args = T.unsafe(nil), local_options = T.unsafe(nil), config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:36
  def args; end

  # pkg:gem/thor#lib/thor/base.rb:36
  def args=(_arg0); end

  # pkg:gem/thor#lib/thor/base.rb:36
  def options; end

  # pkg:gem/thor#lib/thor/base.rb:36
  def options=(_arg0); end

  # pkg:gem/thor#lib/thor/base.rb:36
  def parent_options; end

  # pkg:gem/thor#lib/thor/base.rb:36
  def parent_options=(_arg0); end

  class << self
    # pkg:gem/thor#lib/thor/base.rb:117
    def included(base); end

    # pkg:gem/thor#lib/thor/base.rb:145
    def register_klass_file(klass); end

    # pkg:gem/thor#lib/thor/shell.rb:11
    def shell; end

    # pkg:gem/thor#lib/thor/shell.rb:6
    def shell=(_arg0); end

    # pkg:gem/thor#lib/thor/base.rb:138
    def subclass_files; end

    # pkg:gem/thor#lib/thor/base.rb:129
    def subclasses; end
  end
end

# pkg:gem/thor#lib/thor/base.rb:154
module Thor::Base::ClassMethods
  # pkg:gem/thor#lib/thor/base.rb:483
  def all_commands; end

  # pkg:gem/thor#lib/thor/base.rb:487
  def all_tasks; end

  # pkg:gem/thor#lib/thor/base.rb:190
  def allow_incompatible_default_type!; end

  # pkg:gem/thor#lib/thor/base.rb:262
  def argument(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:294
  def arguments; end

  # pkg:gem/thor#lib/thor/base.rb:163
  def attr_accessor(*_arg0); end

  # pkg:gem/thor#lib/thor/base.rb:155
  def attr_reader(*_arg0); end

  # pkg:gem/thor#lib/thor/base.rb:159
  def attr_writer(*_arg0); end

  # pkg:gem/thor#lib/thor/base.rb:194
  def check_default_type; end

  # pkg:gem/thor#lib/thor/base.rb:184
  def check_default_type!; end

  # pkg:gem/thor#lib/thor/base.rb:173
  def check_unknown_options; end

  # pkg:gem/thor#lib/thor/base.rb:169
  def check_unknown_options!; end

  # pkg:gem/thor#lib/thor/base.rb:177
  def check_unknown_options?(config); end

  # pkg:gem/thor#lib/thor/base.rb:393
  def class_at_least_one(*args, &block); end

  # pkg:gem/thor#lib/thor/base.rb:412
  def class_at_least_one_option_names; end

  # pkg:gem/thor#lib/thor/base.rb:358
  def class_exclusive(*args, &block); end

  # pkg:gem/thor#lib/thor/base.rb:403
  def class_exclusive_option_names; end

  # pkg:gem/thor#lib/thor/base.rb:329
  def class_option(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:307
  def class_options(options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:472
  def commands; end

  # pkg:gem/thor#lib/thor/base.rb:208
  def disable_required_check?(command_name); end

  # pkg:gem/thor#lib/thor/base.rb:629
  def exit_on_failure?; end

  # pkg:gem/thor#lib/thor/base.rb:458
  def group(name = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:619
  def handle_argument_error(command, error, args, arity); end

  # pkg:gem/thor#lib/thor/base.rb:614
  def handle_no_command_error(command, has_namespace = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:617
  def handle_no_task_error(command, has_namespace = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:567
  def namespace(name = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:531
  def no_commands(&block); end

  # pkg:gem/thor#lib/thor/base.rb:541
  def no_commands?; end

  # pkg:gem/thor#lib/thor/base.rb:537
  def no_commands_context; end

  # pkg:gem/thor#lib/thor/base.rb:535
  def no_tasks(&block); end

  # pkg:gem/thor#lib/thor/base.rb:607
  def public_command(*names); end

  # pkg:gem/thor#lib/thor/base.rb:612
  def public_task(*names); end

  # pkg:gem/thor#lib/thor/base.rb:427
  def remove_argument(*names); end

  # pkg:gem/thor#lib/thor/base.rb:446
  def remove_class_option(*names); end

  # pkg:gem/thor#lib/thor/base.rb:501
  def remove_command(*names); end

  # pkg:gem/thor#lib/thor/base.rb:510
  def remove_task(*names); end

  # pkg:gem/thor#lib/thor/base.rb:583
  def start(given_args = T.unsafe(nil), config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:202
  def stop_on_unknown_option?(command_name); end

  # pkg:gem/thor#lib/thor/base.rb:219
  def strict_args_position; end

  # pkg:gem/thor#lib/thor/base.rb:215
  def strict_args_position!; end

  # pkg:gem/thor#lib/thor/base.rb:223
  def strict_args_position?(config); end

  # pkg:gem/thor#lib/thor/base.rb:475
  def tasks; end

  protected

  # pkg:gem/thor#lib/thor/base.rb:778
  def baseclass; end

  # pkg:gem/thor#lib/thor/base.rb:772
  def basename; end

  # pkg:gem/thor#lib/thor/base.rb:689
  def build_option(name, options, scope); end

  # pkg:gem/thor#lib/thor/base.rb:700
  def build_options(options, scope); end

  # pkg:gem/thor#lib/thor/base.rb:809
  def built_option_names(target, opt = T.unsafe(nil), &block); end

  # pkg:gem/thor#lib/thor/base.rb:639
  def class_options_help(shell, groups = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:817
  def command_scope_member(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:783
  def create_command(meth); end

  # pkg:gem/thor#lib/thor/base.rb:785
  def create_task(meth); end

  # pkg:gem/thor#lib/thor/base.rb:793
  def dispatch(command, given_args, given_opts, config); end

  # pkg:gem/thor#lib/thor/base.rb:709
  def find_and_refresh_command(name); end

  # pkg:gem/thor#lib/thor/base.rb:718
  def find_and_refresh_task(name); end

  # pkg:gem/thor#lib/thor/base.rb:750
  def from_superclass(method, default = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:722
  def inherited(klass); end

  # pkg:gem/thor#lib/thor/base.rb:789
  def initialize_added; end

  # pkg:gem/thor#lib/thor/base.rb:678
  def is_thor_reserved_word?(word, type); end

  # pkg:gem/thor#lib/thor/base.rb:730
  def method_added(meth); end

  # pkg:gem/thor#lib/thor/base.rb:657
  def print_options(shell, options, group_name = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/base.rb:799
  def register_options_relation_for(target, relation, *args, &block); end
end

# pkg:gem/thor#lib/thor/command.rb:2
class Thor::Command < ::Struct
  # pkg:gem/thor#lib/thor/command.rb:5
  def initialize(name, description, long_description, wrap_long_description, usage, options = T.unsafe(nil), options_relation = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/command.rb:42
  def formatted_usage(klass, namespace = T.unsafe(nil), subcommand = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/command.rb:15
  def hidden?; end

  # pkg:gem/thor#lib/thor/command.rb:70
  def method_at_least_one_option_names; end

  # pkg:gem/thor#lib/thor/command.rb:66
  def method_exclusive_option_names; end

  # pkg:gem/thor#lib/thor/command.rb:21
  def run(instance, args = T.unsafe(nil)); end

  protected

  # pkg:gem/thor#lib/thor/command.rb:114
  def handle_argument_error?(instance, error, caller); end

  # pkg:gem/thor#lib/thor/command.rb:121
  def handle_no_method_error?(instance, error, caller); end

  # pkg:gem/thor#lib/thor/command.rb:104
  def local_method?(instance, name); end

  # pkg:gem/thor#lib/thor/command.rb:87
  def not_debugging?(instance); end

  # pkg:gem/thor#lib/thor/command.rb:100
  def private_method?(instance); end

  # pkg:gem/thor#lib/thor/command.rb:96
  def public_method?(instance); end

  # pkg:gem/thor#lib/thor/command.rb:77
  def required_arguments_for(klass, usage); end

  # pkg:gem/thor#lib/thor/command.rb:91
  def required_options; end

  # pkg:gem/thor#lib/thor/command.rb:109
  def sans_backtrace(backtrace, caller); end

  private

  # pkg:gem/thor#lib/thor/command.rb:9
  def initialize_copy(other); end
end

# pkg:gem/thor#lib/thor/command.rb:3
Thor::Command::FILE_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:2
module Thor::CoreExt; end

# pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:11
class Thor::CoreExt::HashWithIndifferentAccess < ::Hash
  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:12
  def initialize(hash = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:19
  def [](key); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:23
  def []=(key, value); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:27
  def delete(key); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:31
  def except(*keys); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:37
  def fetch(key, *args); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:45
  def key?(key); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:53
  def merge(other); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:57
  def merge!(other); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:72
  def replace(other_hash); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:64
  def reverse_merge(other); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:68
  def reverse_merge!(other_hash); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:41
  def slice(*keys); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:77
  def to_hash; end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:49
  def values_at(*indices); end

  protected

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:83
  def convert_key(key); end

  # pkg:gem/thor#lib/thor/core_ext/hash_with_indifferent_access.rb:93
  def method_missing(method, *args); end
end

# pkg:gem/thor#lib/thor/error.rb:3
module Thor::Correctable
  # pkg:gem/thor#lib/thor/error.rb:8
  def corrections; end

  # pkg:gem/thor#lib/thor/error.rb:4
  def to_s; end
end

# pkg:gem/thor#lib/thor/command.rb:137
class Thor::DynamicCommand < ::Thor::Command
  # pkg:gem/thor#lib/thor/command.rb:138
  def initialize(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/command.rb:142
  def run(instance, args = T.unsafe(nil)); end
end

# pkg:gem/thor#lib/thor/command.rb:150
Thor::DynamicTask = Thor::DynamicCommand

# pkg:gem/thor#lib/thor/error.rb:20
class Thor::Error < ::StandardError; end

# pkg:gem/thor#lib/thor/error.rb:101
class Thor::ExclusiveArgumentError < ::Thor::InvocationError; end

# pkg:gem/thor#lib/thor/group.rb:7
class Thor::Group
  include ::Thor::Base
  include ::Thor::Invocation
  include ::Thor::Shell
  extend ::Thor::Base::ClassMethods
  extend ::Thor::Invocation::ClassMethods

  protected

  # pkg:gem/thor#lib/thor/group.rb:276
  def _invoke_for_class_method(klass, command = T.unsafe(nil), *args, &block); end

  class << self
    # pkg:gem/thor#lib/thor/group.rb:161
    def class_options_help(shell, groups = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/group.rb:221
    def command_exists?(command_name); end

    # pkg:gem/thor#lib/thor/group.rb:16
    def desc(description = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/group.rb:172
    def get_options_from_invocations(group_options, base_options); end

    # pkg:gem/thor#lib/thor/group.rb:207
    def handle_argument_error(command, error, _args, arity); end

    # pkg:gem/thor#lib/thor/group.rb:29
    def help(shell); end

    # pkg:gem/thor#lib/thor/group.rb:45
    def invocation_blocks; end

    # pkg:gem/thor#lib/thor/group.rb:39
    def invocations; end

    # pkg:gem/thor#lib/thor/group.rb:56
    def invoke(*names, &block); end

    # pkg:gem/thor#lib/thor/group.rb:110
    def invoke_from_option(*names, &block); end

    # pkg:gem/thor#lib/thor/group.rb:199
    def printable_commands(*_arg0); end

    # pkg:gem/thor#lib/thor/group.rb:205
    def printable_tasks(*_arg0); end

    # pkg:gem/thor#lib/thor/group.rb:149
    def remove_invocation(*names); end

    protected

    # pkg:gem/thor#lib/thor/group.rb:249
    def banner; end

    # pkg:gem/thor#lib/thor/group.rb:259
    def baseclass; end

    # pkg:gem/thor#lib/thor/group.rb:263
    def create_command(meth); end

    # pkg:gem/thor#lib/thor/group.rb:267
    def create_task(meth); end

    # pkg:gem/thor#lib/thor/group.rb:228
    def dispatch(command, given_args, given_opts, config); end

    # pkg:gem/thor#lib/thor/group.rb:254
    def self_command; end

    # pkg:gem/thor#lib/thor/group.rb:257
    def self_task; end
  end
end

# pkg:gem/thor#lib/thor/base.rb:17
Thor::HELP_MAPPINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/command.rb:129
class Thor::HiddenCommand < ::Thor::Command
  # pkg:gem/thor#lib/thor/command.rb:130
  def hidden?; end
end

# pkg:gem/thor#lib/thor/command.rb:134
Thor::HiddenTask = Thor::HiddenCommand

# pkg:gem/thor#lib/thor/invocation.rb:2
module Thor::Invocation
  mixes_in_class_methods ::Thor::Invocation::ClassMethods

  # pkg:gem/thor#lib/thor/invocation.rb:23
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil), config = T.unsafe(nil), &block); end

  # pkg:gem/thor#lib/thor/invocation.rb:30
  def current_command_chain; end

  # pkg:gem/thor#lib/thor/invocation.rb:102
  def invoke(name = T.unsafe(nil), *args); end

  # pkg:gem/thor#lib/thor/invocation.rb:133
  def invoke_all; end

  # pkg:gem/thor#lib/thor/invocation.rb:122
  def invoke_command(command, *args); end

  # pkg:gem/thor#lib/thor/invocation.rb:130
  def invoke_task(command, *args); end

  # pkg:gem/thor#lib/thor/invocation.rb:138
  def invoke_with_padding(*args); end

  protected

  # pkg:gem/thor#lib/thor/invocation.rb:166
  def _parse_initialization_options(args, opts, config); end

  # pkg:gem/thor#lib/thor/invocation.rb:153
  def _retrieve_class_and_command(name, sent_command = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/invocation.rb:163
  def _retrieve_class_and_task(name, sent_command = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/invocation.rb:145
  def _shared_configuration; end

  class << self
    # pkg:gem/thor#lib/thor/invocation.rb:3
    def included(base); end
  end
end

# pkg:gem/thor#lib/thor/invocation.rb:8
module Thor::Invocation::ClassMethods
  # pkg:gem/thor#lib/thor/invocation.rb:12
  def prepare_for_invocation(key, name); end
end

# pkg:gem/thor#lib/thor/error.rb:62
class Thor::InvocationError < ::Thor::Error; end

# pkg:gem/thor#lib/thor/line_editor/basic.rb:2
module Thor::LineEditor
  class << self
    # pkg:gem/thor#lib/thor/line_editor.rb:10
    def best_available; end

    # pkg:gem/thor#lib/thor/line_editor.rb:6
    def readline(prompt, options = T.unsafe(nil)); end
  end
end

# pkg:gem/thor#lib/thor/line_editor/basic.rb:3
class Thor::LineEditor::Basic
  # pkg:gem/thor#lib/thor/line_editor/basic.rb:10
  def initialize(prompt, options); end

  # pkg:gem/thor#lib/thor/line_editor/basic.rb:4
  def options; end

  # pkg:gem/thor#lib/thor/line_editor/basic.rb:4
  def prompt; end

  # pkg:gem/thor#lib/thor/line_editor/basic.rb:15
  def readline; end

  private

  # pkg:gem/thor#lib/thor/line_editor/basic.rb:32
  def echo?; end

  # pkg:gem/thor#lib/thor/line_editor/basic.rb:22
  def get_input; end

  class << self
    # pkg:gem/thor#lib/thor/line_editor/basic.rb:6
    def available?; end
  end
end

# pkg:gem/thor#lib/thor/line_editor/readline.rb:3
class Thor::LineEditor::Readline < ::Thor::LineEditor::Basic
  # pkg:gem/thor#lib/thor/line_editor/readline.rb:13
  def readline; end

  private

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:28
  def add_to_history?; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:42
  def completion_options; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:32
  def completion_proc; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:46
  def use_path_completion?; end

  class << self
    # pkg:gem/thor#lib/thor/line_editor/readline.rb:4
    def available?; end
  end
end

# pkg:gem/thor#lib/thor/line_editor/readline.rb:50
class Thor::LineEditor::Readline::PathCompletion
  # pkg:gem/thor#lib/thor/line_editor/readline.rb:54
  def initialize(text); end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:58
  def matches; end

  private

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:68
  def absolute_matches; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:82
  def base_path; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:78
  def glob_pattern; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:64
  def relative_matches; end

  # pkg:gem/thor#lib/thor/line_editor/readline.rb:51
  def text; end
end

# pkg:gem/thor#lib/thor/error.rb:98
class Thor::MalformattedArgumentError < ::Thor::InvocationError; end

# pkg:gem/thor#lib/thor/nested_context.rb:2
class Thor::NestedContext
  # pkg:gem/thor#lib/thor/nested_context.rb:3
  def initialize; end

  # pkg:gem/thor#lib/thor/nested_context.rb:7
  def enter; end

  # pkg:gem/thor#lib/thor/nested_context.rb:15
  def entered?; end

  private

  # pkg:gem/thor#lib/thor/nested_context.rb:25
  def pop; end

  # pkg:gem/thor#lib/thor/nested_context.rb:21
  def push; end
end

# pkg:gem/thor#lib/thor/parser/option.rb:2
class Thor::Option < ::Thor::Argument
  # pkg:gem/thor#lib/thor/parser/option.rb:7
  def initialize(name, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/parser/option.rb:3
  def aliases; end

  # pkg:gem/thor#lib/thor/parser/option.rb:99
  def aliases_for_usage; end

  # pkg:gem/thor#lib/thor/parser/option.rb:117
  def array?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:117
  def boolean?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:3
  def group; end

  # pkg:gem/thor#lib/thor/parser/option.rb:117
  def hash?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:3
  def hide; end

  # pkg:gem/thor#lib/thor/parser/option.rb:79
  def human_name; end

  # pkg:gem/thor#lib/thor/parser/option.rb:3
  def lazy_default; end

  # pkg:gem/thor#lib/thor/parser/option.rb:117
  def numeric?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:3
  def repeatable; end

  # pkg:gem/thor#lib/thor/parser/option.rb:107
  def show_default?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:117
  def string?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:75
  def switch_name; end

  # pkg:gem/thor#lib/thor/parser/option.rb:83
  def usage(padding = T.unsafe(nil)); end

  protected

  # pkg:gem/thor#lib/thor/parser/option.rb:168
  def dasherize(str); end

  # pkg:gem/thor#lib/thor/parser/option.rb:160
  def dasherized?; end

  # pkg:gem/thor#lib/thor/parser/option.rb:164
  def undasherize(str); end

  # pkg:gem/thor#lib/thor/parser/option.rb:126
  def validate!; end

  # pkg:gem/thor#lib/thor/parser/option.rb:131
  def validate_default_type!; end

  private

  # pkg:gem/thor#lib/thor/parser/option.rb:174
  def normalize_aliases(aliases); end

  class << self
    # pkg:gem/thor#lib/thor/parser/option.rb:45
    def parse(key, value); end
  end
end

# pkg:gem/thor#lib/thor/parser/option.rb:5
Thor::Option::VALID_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/parser/options.rb:2
class Thor::Options < ::Thor::Arguments
  # pkg:gem/thor#lib/thor/parser/options.rb:32
  def initialize(hash_options = T.unsafe(nil), defaults = T.unsafe(nil), stop_on_unknown = T.unsafe(nil), disable_required_check = T.unsafe(nil), relations = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/parser/options.rb:156
  def check_at_least_one!; end

  # pkg:gem/thor#lib/thor/parser/options.rb:144
  def check_exclusive!; end

  # pkg:gem/thor#lib/thor/parser/options.rb:168
  def check_unknown!; end

  # pkg:gem/thor#lib/thor/parser/options.rb:89
  def parse(args); end

  # pkg:gem/thor#lib/thor/parser/options.rb:65
  def peek; end

  # pkg:gem/thor#lib/thor/parser/options.rb:61
  def remaining; end

  # pkg:gem/thor#lib/thor/parser/options.rb:79
  def shift; end

  # pkg:gem/thor#lib/thor/parser/options.rb:84
  def unshift(arg, is_value: T.unsafe(nil)); end

  protected

  # pkg:gem/thor#lib/thor/parser/options.rb:189
  def assign_result!(option, result); end

  # pkg:gem/thor#lib/thor/parser/options.rb:203
  def current_is_switch?; end

  # pkg:gem/thor#lib/thor/parser/options.rb:215
  def current_is_switch_formatted?; end

  # pkg:gem/thor#lib/thor/parser/options.rb:225
  def current_is_value?; end

  # pkg:gem/thor#lib/thor/parser/options.rb:179
  def names_to_switch_names(names = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/parser/options.rb:244
  def normalize_switch(arg); end

  # pkg:gem/thor#lib/thor/parser/options.rb:256
  def parse_boolean(switch); end

  # pkg:gem/thor#lib/thor/parser/options.rb:274
  def parse_peek(switch, option); end

  # pkg:gem/thor#lib/thor/parser/options.rb:248
  def parsing_options?; end

  # pkg:gem/thor#lib/thor/parser/options.rb:230
  def switch?(arg); end

  # pkg:gem/thor#lib/thor/parser/options.rb:234
  def switch_option(arg); end

  class << self
    # pkg:gem/thor#lib/thor/parser/options.rb:11
    def to_switches(options); end
  end
end

# pkg:gem/thor#lib/thor/parser/options.rb:5
Thor::Options::EQ_RE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/parser/options.rb:3
Thor::Options::LONG_RE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/parser/options.rb:8
Thor::Options::OPTS_END = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/parser/options.rb:7
Thor::Options::SHORT_NUM = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/parser/options.rb:4
Thor::Options::SHORT_RE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/parser/options.rb:6
Thor::Options::SHORT_SQ_RE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/thor#lib/thor/rake_compat.rb:20
module Thor::RakeCompat
  include ::FileUtils::StreamUtils_
  include ::FileUtils
  include ::Rake::FileUtilsExt
  include ::Rake::DSL

  class << self
    # pkg:gem/thor#lib/thor/rake_compat.rb:27
    def included(base); end

    # pkg:gem/thor#lib/thor/rake_compat.rb:23
    def rake_classes; end
  end
end

# pkg:gem/thor#lib/thor/error.rb:95
class Thor::RequiredArgumentMissingError < ::Thor::InvocationError; end

# pkg:gem/thor#lib/thor/util.rb:4
module Thor::Sandbox; end

# pkg:gem/thor#lib/thor/shell.rb:23
module Thor::Shell
  # pkg:gem/thor#lib/thor/shell.rb:44
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil), config = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def ask(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def error(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def file_collision(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def no?(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def print_in_columns(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def print_table(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def print_wrapped(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def say(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def say_error(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def say_status(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def set_color(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:52
  def shell; end

  # pkg:gem/thor#lib/thor/shell.rb:25
  def shell=(_arg0); end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def terminal_width(*args, &block); end

  # pkg:gem/thor#lib/thor/shell.rb:66
  def with_padding; end

  # pkg:gem/thor#lib/thor/shell.rb:58
  def yes?(*args, &block); end

  protected

  # pkg:gem/thor#lib/thor/shell.rb:77
  def _shared_configuration; end
end

# pkg:gem/thor#lib/thor/shell/basic.rb:7
class Thor::Shell::Basic
  # pkg:gem/thor#lib/thor/shell/basic.rb:13
  def initialize; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:80
  def ask(statement, *args); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:8
  def base; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:8
  def base=(_arg0); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:251
  def error(statement); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:207
  def file_collision(destination); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:43
  def indent(count = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:22
  def mute; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:31
  def mute?; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:156
  def no?(statement, color = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:9
  def padding; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:37
  def padding=(value); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:165
  def print_in_columns(array); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:180
  def print_table(array, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:194
  def print_wrapped(message, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:98
  def say(message = T.unsafe(nil), color = T.unsafe(nil), force_new_line = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:115
  def say_error(message = T.unsafe(nil), color = T.unsafe(nil), force_new_line = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:130
  def say_status(status, message, log_status = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:258
  def set_color(string, *_arg1); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:149
  def yes?(statement, color = T.unsafe(nil)); end

  protected

  # pkg:gem/thor#lib/thor/shell/basic.rb:360
  def answer_match(possibilities, answer, case_insensitive); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:347
  def ask_filtered(statement, color, options); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:330
  def ask_simply(statement, color, options); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:269
  def can_display_colors?; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:384
  def diff_tool; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:296
  def file_collision_help(block_given); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:286
  def is?(value); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:273
  def lookup_color(color); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:368
  def merge(destination, content); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:377
  def merge_tool; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:264
  def prepare_message(message, *color); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:322
  def quiet?; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:313
  def show_diff(destination, content); end

  # pkg:gem/thor#lib/thor/shell/basic.rb:282
  def stderr; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:278
  def stdout; end

  # pkg:gem/thor#lib/thor/shell/basic.rb:326
  def unix?; end
end

# pkg:gem/thor#lib/thor/shell/color.rb:11
class Thor::Shell::Color < ::Thor::Shell::Basic
  include ::LCSDiff

  # pkg:gem/thor#lib/thor/shell/color.rb:84
  def set_color(string, *colors); end

  protected

  # pkg:gem/thor#lib/thor/shell/color.rb:112
  def are_colors_disabled?; end

  # pkg:gem/thor#lib/thor/shell/color.rb:108
  def are_colors_supported?; end

  # pkg:gem/thor#lib/thor/shell/color.rb:104
  def can_display_colors?; end
end

# pkg:gem/thor#lib/thor/shell/color.rb:20
Thor::Shell::Color::BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:28
Thor::Shell::Color::BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:17
Thor::Shell::Color::BOLD = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:15
Thor::Shell::Color::CLEAR = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:32
Thor::Shell::Color::CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:24
Thor::Shell::Color::GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:30
Thor::Shell::Color::MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:37
Thor::Shell::Color::ON_BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:45
Thor::Shell::Color::ON_BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:49
Thor::Shell::Color::ON_CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:41
Thor::Shell::Color::ON_GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:47
Thor::Shell::Color::ON_MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:39
Thor::Shell::Color::ON_RED = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:51
Thor::Shell::Color::ON_WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:43
Thor::Shell::Color::ON_YELLOW = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:22
Thor::Shell::Color::RED = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:34
Thor::Shell::Color::WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/color.rb:26
Thor::Shell::Color::YELLOW = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/column_printer.rb:5
class Thor::Shell::ColumnPrinter
  # pkg:gem/thor#lib/thor/shell/column_printer.rb:8
  def initialize(stdout, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/column_printer.rb:6
  def options; end

  # pkg:gem/thor#lib/thor/shell/column_printer.rb:14
  def print(array); end

  # pkg:gem/thor#lib/thor/shell/column_printer.rb:6
  def stdout; end
end

# pkg:gem/thor#lib/thor/shell/html.rb:9
class Thor::Shell::HTML < ::Thor::Shell::Basic
  include ::LCSDiff

  # pkg:gem/thor#lib/thor/shell/html.rb:73
  def ask(statement, color = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/html.rb:54
  def set_color(string, *colors); end

  protected

  # pkg:gem/thor#lib/thor/shell/html.rb:79
  def can_display_colors?; end
end

# pkg:gem/thor#lib/thor/shell/html.rb:16
Thor::Shell::HTML::BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:24
Thor::Shell::HTML::BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:13
Thor::Shell::HTML::BOLD = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:28
Thor::Shell::HTML::CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:20
Thor::Shell::HTML::GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:26
Thor::Shell::HTML::MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:33
Thor::Shell::HTML::ON_BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:41
Thor::Shell::HTML::ON_BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:45
Thor::Shell::HTML::ON_CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:37
Thor::Shell::HTML::ON_GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:43
Thor::Shell::HTML::ON_MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:35
Thor::Shell::HTML::ON_RED = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:47
Thor::Shell::HTML::ON_WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:39
Thor::Shell::HTML::ON_YELLOW = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:18
Thor::Shell::HTML::RED = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:30
Thor::Shell::HTML::WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell/html.rb:22
Thor::Shell::HTML::YELLOW = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/shell.rb:24
Thor::Shell::SHELL_DELEGATED_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/shell/table_printer.rb:6
class Thor::Shell::TablePrinter < ::Thor::Shell::ColumnPrinter
  # pkg:gem/thor#lib/thor/shell/table_printer.rb:9
  def initialize(stdout, options = T.unsafe(nil)); end

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:18
  def print(array); end

  private

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:72
  def format_cell(column, row_size, index); end

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:113
  def indentation; end

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:47
  def prepare(array); end

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:96
  def print_border_separator; end

  # pkg:gem/thor#lib/thor/shell/table_printer.rb:103
  def truncate(string); end
end

# pkg:gem/thor#lib/thor/shell/table_printer.rb:7
Thor::Shell::TablePrinter::BORDER_SEPARATOR = T.let(T.unsafe(nil), Symbol)

# pkg:gem/thor#lib/thor/shell/terminal.rb:3
module Thor::Shell::Terminal
  class << self
    # pkg:gem/thor#lib/thor/shell/terminal.rb:9
    def terminal_width; end

    # pkg:gem/thor#lib/thor/shell/terminal.rb:20
    def unix?; end

    private

    # pkg:gem/thor#lib/thor/shell/terminal.rb:27
    def dynamic_width; end

    # pkg:gem/thor#lib/thor/shell/terminal.rb:31
    def dynamic_width_stty; end

    # pkg:gem/thor#lib/thor/shell/terminal.rb:35
    def dynamic_width_tput; end
  end
end

# pkg:gem/thor#lib/thor/shell/terminal.rb:4
Thor::Shell::Terminal::DEFAULT_TERMINAL_WIDTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/thor#lib/thor/shell/wrapped_printer.rb:6
class Thor::Shell::WrappedPrinter < ::Thor::Shell::ColumnPrinter
  # pkg:gem/thor#lib/thor/shell/wrapped_printer.rb:7
  def print(message); end
end

# pkg:gem/thor#lib/thor/base.rb:24
Thor::TEMPLATE_EXTNAME = T.let(T.unsafe(nil), String)

# pkg:gem/thor#lib/thor/base.rb:21
Thor::THOR_RESERVED_WORDS = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/base.rb:18
Thor::TREE_MAPPINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/thor#lib/thor/command.rb:126
Thor::Task = Thor::Command

# pkg:gem/thor#lib/thor/error.rb:24
class Thor::UndefinedCommandError < ::Thor::Error
  include ::Thor::Correctable

  # pkg:gem/thor#lib/thor/error.rb:43
  def initialize(command, all_commands, namespace); end

  # pkg:gem/thor#lib/thor/error.rb:41
  def all_commands; end

  # pkg:gem/thor#lib/thor/error.rb:41
  def command; end
end

# pkg:gem/thor#lib/thor/error.rb:25
class Thor::UndefinedCommandError::SpellChecker
  # pkg:gem/thor#lib/thor/error.rb:28
  def initialize(error); end

  # pkg:gem/thor#lib/thor/error.rb:32
  def corrections; end

  # pkg:gem/thor#lib/thor/error.rb:26
  def error; end

  # pkg:gem/thor#lib/thor/error.rb:36
  def spell_checker; end
end

# pkg:gem/thor#lib/thor/error.rb:55
Thor::UndefinedTaskError = Thor::UndefinedCommandError

# pkg:gem/thor#lib/thor/error.rb:65
class Thor::UnknownArgumentError < ::Thor::Error
  include ::Thor::Correctable

  # pkg:gem/thor#lib/thor/error.rb:85
  def initialize(switches, unknown); end

  # pkg:gem/thor#lib/thor/error.rb:83
  def switches; end

  # pkg:gem/thor#lib/thor/error.rb:83
  def unknown; end
end

# pkg:gem/thor#lib/thor/error.rb:66
class Thor::UnknownArgumentError::SpellChecker
  # pkg:gem/thor#lib/thor/error.rb:69
  def initialize(error); end

  # pkg:gem/thor#lib/thor/error.rb:73
  def corrections; end

  # pkg:gem/thor#lib/thor/error.rb:67
  def error; end

  # pkg:gem/thor#lib/thor/error.rb:78
  def spell_checker; end
end

# pkg:gem/thor#lib/thor/util.rb:17
module Thor::Util
  class << self
    # pkg:gem/thor#lib/thor/util.rb:104
    def camel_case(str); end

    # pkg:gem/thor#lib/thor/util.rb:264
    def escape_globs(path); end

    # pkg:gem/thor#lib/thor/util.rb:280
    def escape_html(string); end

    # pkg:gem/thor#lib/thor/util.rb:24
    def find_by_namespace(namespace); end

    # pkg:gem/thor#lib/thor/util.rb:131
    def find_class_and_command_by_namespace(namespace, fallback = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/util.rb:148
    def find_class_and_task_by_namespace(namespace, fallback = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/util.rb:213
    def globs_for(path); end

    # pkg:gem/thor#lib/thor/util.rb:153
    def load_thorfile(path, content = T.unsafe(nil), debug = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/util.rb:43
    def namespace_from_thor_class(constant); end

    # pkg:gem/thor#lib/thor/util.rb:58
    def namespaces_in_content(contents, file = T.unsafe(nil)); end

    # pkg:gem/thor#lib/thor/util.rb:221
    def ruby_command; end

    # pkg:gem/thor#lib/thor/util.rb:90
    def snake_case(str); end

    # pkg:gem/thor#lib/thor/util.rb:74
    def thor_classes_in(klass); end

    # pkg:gem/thor#lib/thor/util.rb:192
    def thor_root; end

    # pkg:gem/thor#lib/thor/util.rb:203
    def thor_root_glob; end

    # pkg:gem/thor#lib/thor/util.rb:168
    def user_home; end
  end
end
