# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Authorization`.
# Please instead update this file by running `bin/tapioca dsl Authorization`.


module Authorization
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def authorization_rules; end
    def authorization_rules=(value); end
    def authorization_rules?; end
  end

  module GeneratedInstanceMethods
    def authorization_rules; end
    def authorization_rules?; end
  end
end
