# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OperatorMailer`.
# Please instead update this file by running `bin/tapioca dsl OperatorMailer`.


class OperatorMailer
  class << self
    sig { params(operator: T.untyped, token: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def invite(operator, token); end
  end
end
