# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReconciliationJob`.
# Please instead update this file by running `bin/tapioca dsl ReconciliationJob`.


class ReconciliationJob
  class << self
    sig do
      params(
        since: T.nilable(::String),
        block: T.nilable(T.proc.params(job: ReconciliationJob).void)
      ).returns(T.any(ReconciliationJob, FalseClass))
    end
    def perform_later(since = T.unsafe(nil), &block); end

    sig { params(since: T.nilable(::String)).void }
    def perform_now(since = T.unsafe(nil)); end
  end
end
