# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RefundPaymentJob`.
# Please instead update this file by running `bin/tapioca dsl RefundPaymentJob`.


class RefundPaymentJob
  class << self
    sig do
      params(
        refund_id: ::String,
        block: T.nilable(T.proc.params(job: RefundPaymentJob).void)
      ).returns(T.any(RefundPaymentJob, FalseClass))
    end
    def perform_later(refund_id, &block); end

    sig { params(refund_id: ::String).void }
    def perform_now(refund_id); end
  end
end
