# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SettlementReconciliationJob`.
# Please instead update this file by running `bin/tapioca dsl SettlementReconciliationJob`.


class SettlementReconciliationJob
  class << self
    sig do
      params(
        date: T.nilable(::String),
        block: T.nilable(T.proc.params(job: SettlementReconciliationJob).void)
      ).returns(T.any(SettlementReconciliationJob, FalseClass))
    end
    def perform_later(date = T.unsafe(nil), &block); end

    sig { params(date: T.nilable(::String)).void }
    def perform_now(date = T.unsafe(nil)); end
  end
end
