source "https://rubygems.org"

ruby "3.3.12"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.5"
gem "rackup", "~> 2.2"
gem "csv", "~> 3.2" # the settlement report

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.2"
end
