# frozen_string_literal: true

require "rails_helper"

RSpec.describe CurrencyExport do
  it "exports every supported currency with its exponent" do
    ts = described_class.typescript
    expect(ts).to include('"EUR": 2', '"VND": 0', '"IDR": 2')
    expect(ts).to start_with("// Generated by `bin/rails exports:all`")
  end
end
