# frozen_string_literal: true

require "rails_helper"

RSpec.describe PermissionsExport do
  describe ".markdown" do
    subject(:markdown) { described_class.markdown }

    it "has one row per permission with its description" do
      expect(markdown).to include("| `payments.refund` | Refund a captured payment |")
    end

    it "marks sensitive permissions" do
      expect(markdown).to match(/\| `payments\.refund` \|[^\n]*\| yes \|/)
    end

    it "says it is generated" do
      expect(markdown).to start_with("<!-- Generated by `bin/rails permissions:export`")
    end
  end

  describe ".typescript" do
    subject(:ts) { described_class.typescript }

    it "exports a union type of merchant permissions" do
      expect(ts).to include(%(export type MerchantPermission =\n  | "api_keys.manage"))
    end

    it "exports a union type of operator permissions" do
      expect(ts).to include(%(  | "ops.proposals.decide"))
    end
  end
end
